<a href="https://colab.research.google.com/github/Proton214/hmm_test/blob/master/read_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import pandas as pd
import numpy as np
from hmmlearn import hmm
from sklearn.metrics import confusion_matrix

In [2]:
bt_v = pd.read_csv("application_data/LU_variable.csv")

### state : H_D = 0, L_D = 1, L_U = 2, H_U = 3

In [3]:
bt_v

Unnamed: 0 Application  variable  Perf_node01_power_energy_pkg_  a  \
0           5449          LU        94                              2  2   
1           5450          LU        94                              2  2   
2           5451          LU       127                              2  2   
3           5452          LU       127                              3  2   
4           5453          LU         0                              0  3   
5           5454          LU       127                              3  0   
6           5455          LU       127                              2  3   
7           5456          LU         0                              0  2   
8           5457          LU         1                              0  0   
9           5458          LU       126                              3  0   
10          5459          LU         0                              0  3   
11          5460          LU       127                              3  0   
12          5461          LU         0                              0  3   
13          5462          LU        24                              1  0   
14          5463          LU       127                              3  1   
15          5464          LU         1                              0  3   
16          5465          LU       126                              3  0   
17          5466          LU         1                              0  3   
18          5467          LU       127                              3  0   
19          5468          LU         0                              0  3   
20          5469          LU       126                              2  0   
21          5470          LU         0                              2  2   
22          5471          LU        31                              1  2   
23          5472          LU       127                              3  1   
24          5473          LU         0                              0  3   
25          5474          LU       127                              3  0   
26          5475          LU         1                              0  3   
27          5476          LU       127                              3  0   
28          5477          LU         0                              0  3   
29          5478          LU        24                              1  0   
...          ...         ...       ...                            ... ..   
1078        6527          LU         0                              0  3   
1079        6528          LU       126                              2  0   
1080        6529          LU         0                              1  2   
1081        6530          LU        30                              1  1   
1082        6531          LU        32                              2  1   
1083        6532          LU        31                              1  2   
1084        6533          LU       127                              3  1   
1085        6534          LU         0                              0  3   
1086        6535          LU       126                              3  0   
1087        6536          LU         7                              0  3   
1088        6537          LU       127                              3  0   
1089        6538          LU         0                              0  3   
1090        6539          LU       126                              2  0   
1091        6540          LU         0                              1  2   
1092        6541          LU        94                              1  1   
1093        6542          LU       101                              2  1   
1094        6543          LU        95                              1  2   
1095        6544          LU       127                              3  1   
1096        6545          LU         0                              0  3   
1097        6546          LU       126                              3  0   
1098        6547          LU         0                

# pkg, ram, total power matrix

In [4]:
pkg_matrix = np.zeros((4,4))
ram_matrix = np.zeros((4,4))
total_matrix = np.zeros((4,4))

In [5]:
pkg_matrix = confusion_matrix( bt_v['a'], bt_v['Perf_node01_power_energy_pkg_'])
ram_matrix = confusion_matrix( bt_v['b'], bt_v['Perf_node01_power_energy_ram_'])
total_matrix = confusion_matrix( bt_v['c'], bt_v['Perf_node01_power_energy_total_'])

In [6]:
pkg_matrix = pkg_matrix.astype(float)
ram_matrix = ram_matrix.astype(float)
total_matrix = total_matrix.astype(float)

## 1. pkg_matrix

In [7]:
sum = 0

for i in range(len(pkg_matrix)):
    for j in range(len(pkg_matrix)):
        sum = sum + pkg_matrix[i][j]
    for k in range(len(pkg_matrix)):
        po = pkg_matrix[i][k] / sum
        pkg_matrix[i][k] = po.round(3)
    sum = 0

In [8]:
pkg_matrix

array([[0.003, 0.12 , 0.16 , 0.717],
       [0.009, 0.244, 0.209, 0.538],
       [0.031, 0.803, 0.142, 0.024],
       [0.93 , 0.064, 0.005, 0.   ]])

## 2. ram_matrix

In [9]:
sum = 0

for i in range(len(ram_matrix)):
    for j in range(len(ram_matrix)):
        sum = sum + ram_matrix[i][j]
    for k in range(len(ram_matrix)):
        po = ram_matrix[i][k] / sum
        ram_matrix[i][k] = po.round(3)
    sum = 0

In [10]:
ram_matrix

array([[0.012, 0.044, 0.095, 0.848],
       [0.188, 0.188, 0.286, 0.338],
       [0.4  , 0.192, 0.2  , 0.208],
       [0.752, 0.147, 0.062, 0.039]])

## 3. total_matrix

In [11]:
sum = 0

for i in range(len(total_matrix)):
    for j in range(len(total_matrix)):
        sum = sum + total_matrix[i][j]
    for k in range(len(total_matrix)):
        po = total_matrix[i][k] / sum
        total_matrix[i][k] = po.round(3)
    sum = 0

In [12]:
total_matrix

array([[0.003, 0.104, 0.224, 0.669],
       [0.   , 0.194, 0.245, 0.561],
       [0.077, 0.675, 0.195, 0.053],
       [0.875, 0.117, 0.005, 0.003]])

# Variable count

In [13]:
np.set_printoptions(threshold=sys.maxsize)

In [14]:
q = bt_v['variable'].unique()
le = q.size
print(np.sort(q),"\n",q.size)

[  0   1   3   5   7  11  15  24  26  27  28  30  31  32  33  38  64  80
  88  90  92  94  95  96  97  98  99 100 101 102 103 117 118 119 120 124
 126 127] 
 38


In [18]:
pkg_var_matrix = np.zeros((4,39))
ram_var_matrix = np.zeros((4,39))
total_var_matrix = np.zeros((4,39))

## 1. pkg + variable 

In [19]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_pkg_'], bt_v['variable'])

In [20]:
for i in range(len(pkg_var_matrix)):
    pkg_var_matrix[i] = tem_matrix[i]

In [21]:
pkg_var_matrix

array([[245.,  77.,   0.,  16.,   1.,  13.,   1.,   4.,   0.,   0.,   0.,
          0.,   0.,  10.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [ 56.,   1.,   0.,   0.,   0.,   0.,   0.,   2.,   7.,   2.,   1.,
          2.,  14.,  63.,   0.,   0.,   0.,   0.,   1.,  12.,   2.,   2.,
         22.,  12.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,  18.,   2.,   4.,   3.],
       [ 17.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   6.,   0.,   1.,   1.,   0.,   0.,   0.,   0.,
          2.,   1.,  17.,   4.,   2.,   1.,   3.,   4.,   1.,   3.,   0.,
          0.,   0.,   9.,   5.,  40.,   9.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,  

In [22]:
sum = 0

for i in range(len(pkg_var_matrix)):
    for j in range(len(pkg_var_matrix[0])):
        sum = sum + pkg_var_matrix[i][j]
    for k in range(len(pkg_var_matrix[0])):
        po = pkg_var_matrix[i][k] / sum
        pkg_var_matrix[i][k] = po.round(3)
    sum = 0

In [23]:
pkg_var_matrix

array([[0.666, 0.209, 0.   , 0.043, 0.003, 0.035, 0.003, 0.011, 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.027, 0.   , 0.003, 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   ],
       [0.248, 0.004, 0.   , 0.   , 0.   , 0.   , 0.   , 0.009, 0.031,
        0.009, 0.004, 0.009, 0.062, 0.279, 0.   , 0.   , 0.   , 0.   ,
        0.004, 0.053, 0.009, 0.009, 0.097, 0.053, 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.08 ,
        0.009, 0.018, 0.013],
       [0.135, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.048, 0.   , 0.008, 0.008,
        0.   , 0.   , 0.   , 0.   , 0.016, 0.008, 0.135, 0.032, 0.016,
        0.008, 0.024, 0.032, 0.008, 0.024, 0.   , 0.   , 0.   , 0.071,
        0.04 , 0.317, 0.071],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0

## 2. ram + variable

In [24]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_ram_'], bt_v['variable'])

In [25]:
for i in range(len(ram_var_matrix)):
    ram_var_matrix[i] = tem_matrix[i]

In [26]:
ram_var_matrix

array([[194.,  35.,   0.,   6.,   1.,   6.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   6.,   1.,   1.,   1.,   0.,   0.,   0.,   0.,
          0.,   0.,  17.,   4.,   2.,   1.,   3.,   4.,   2.,   4.,   2.,
          0.,   5.,   0.,   4.,  26.,  85.],
       [ 31.,  12.,   0.,   4.,   0.,   2.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          2.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,   0.,
          1.,   2.,   0.,   0.,  22.,  54.],
       [ 39.,  13.,   0.,   2.,   0.,   2.,   1.,   2.,   0.,   0.,   0.,
          0.,   0.,   5.,   0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,
          1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   4.,   0.,  16.,  44.],
       [ 54.,  18.,   0.,   4.,   0.,   3.,   0.,   4.,   7.,   2.,   1.,
          2.,  14.,  67.,   0.,   0.,   0.,   0.,   1.,  11.,   2.,   2.,
         21.,  13.,   0.,   0.,   0.,   0.,   0.,  

In [27]:
sum = 0

for i in range(len(ram_var_matrix)):
    for j in range(len(ram_var_matrix[0])):
        sum = sum + ram_var_matrix[i][j]
    for k in range(len(ram_var_matrix[0])):
        po = ram_var_matrix[i][k] / sum
        ram_var_matrix[i][k] = po.round(3)
    sum = 0

In [28]:
ram_var_matrix

array([[0.473, 0.085, 0.   , 0.015, 0.002, 0.015, 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.015, 0.002, 0.002, 0.002,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.041, 0.01 , 0.005,
        0.002, 0.007, 0.01 , 0.005, 0.01 , 0.005, 0.   , 0.012, 0.   ,
        0.01 , 0.063, 0.207],
       [0.235, 0.091, 0.   , 0.03 , 0.   , 0.015, 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.008, 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.015, 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.008, 0.   , 0.008, 0.015, 0.   ,
        0.   , 0.167, 0.409],
       [0.3  , 0.1  , 0.   , 0.015, 0.   , 0.015, 0.008, 0.015, 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.038, 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.008, 0.   , 0.   , 0.008, 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.031,
        0.   , 0.123, 0.338],
       [0.124, 0.041, 0.   , 0.009, 0.   , 0.007, 0.   , 0

## 3. total + variable

In [29]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_total_'], bt_v['variable'])

In [30]:
for i in range(len(total_var_matrix)):
    total_var_matrix[i] = tem_matrix[i]

In [31]:
total_var_matrix

array([[236.,  69.,   0.,  15.,   1.,  12.,   0.,   1.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.],
       [ 77.,   9.,   0.,   1.,   0.,   1.,   1.,   5.,   7.,   2.,   1.,
          2.,  11.,  73.,   3.,   0.,   0.,   1.,   1.,   8.,   1.,   1.,
         15.,   9.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   7.,   0.,   1.,   1.],
       [  5.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   3.,   0.,   3.,   0.,   1.,   0.,   0.,   4.,   1.,   1.,
          9.,   4.,  17.,   4.,   2.,   1.,   3.,   4.,   2.,   5.,   1.,
          1.,   6.,  20.,  10.,  36.,  25.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,  

In [32]:
sum = 0

for i in range(len(total_var_matrix)):
    for j in range(len(total_var_matrix[0])):
        sum = sum + total_var_matrix[i][j]
    for k in range(len(total_var_matrix[0])):
        po = total_var_matrix[i][k] / sum
        total_var_matrix[i][k] = po.round(3)
    sum = 0

In [33]:
total_var_matrix

array([[0.704, 0.206, 0.   , 0.045, 0.003, 0.036, 0.   , 0.003, 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.003, 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   ],
       [0.324, 0.038, 0.   , 0.004, 0.   , 0.004, 0.004, 0.021, 0.029,
        0.008, 0.004, 0.008, 0.046, 0.307, 0.013, 0.   , 0.   , 0.004,
        0.004, 0.034, 0.004, 0.004, 0.063, 0.038, 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.029,
        0.   , 0.004, 0.004],
       [0.03 , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.018, 0.   , 0.018, 0.   , 0.006, 0.   ,
        0.   , 0.024, 0.006, 0.006, 0.054, 0.024, 0.101, 0.024, 0.012,
        0.006, 0.018, 0.024, 0.012, 0.03 , 0.006, 0.006, 0.036, 0.119,
        0.06 , 0.214, 0.149],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0