<a href="https://colab.research.google.com/github/Proton214/hmm_test/blob/master/read_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import sys
import pandas as pd
import numpy as np
from hmmlearn import hmm
from sklearn.metrics import confusion_matrix

In [3]:
bt_v = pd.read_csv("application_data/BT_variable.csv")

In [4]:
bt_v

Unnamed: 0 Application  variable  Perf_node01_power_energy_pkg_  a  \
0              0          BT        94                              2  2   
1              1          BT       127                              2  2   
2              2          BT        95                              2  2   
3              3          BT       121                              2  2   
4              4          BT       127                              3  2   
5              5          BT         0                              0  3   
6              6          BT       112                              2  0   
7              7          BT         0                              1  2   
8              8          BT       127                              2  1   
9              9          BT         0                              1  2   
10            10          BT         6                              2  1   
11            11          BT       127                              3  2   
12            12          BT         0                              0  3   
13            13          BT        64                              2  0   
14            14          BT       127                              3  2   
15            15          BT         0                              0  3   
16            16          BT         0                              2  0   
17            17          BT       127                              3  2   
18            18          BT         0                              1  3   
19            19          BT         0                              1  1   
20            20          BT       127                              3  1   
21            21          BT         0                              0  3   
22            22          BT         0                              1  0   
23            23          BT       127                              3  1   
24            24          BT         0                              0  3   
25            25          BT         0                              1  0   
26            26          BT       127                              3  1   
27            27          BT         0                              0  3   
28            28          BT       112                              2  0   
29            29          BT       127                              3  2   
...          ...         ...       ...                            ... ..   
1508        1508          BT         0                              1  2   
1509        1509          BT       102                              1  1   
1510        1510          BT       127                              3  1   
1511        1511          BT         0                              0  3   
1512        1512          BT        96                              2  0   
1513        1513          BT       127                              3  2   
1514        1514          BT         0                              0  3   
1515        1515          BT         0                              2  0   
1516        1516          BT       127                              3  2   
1517        1517          BT         0                              0  3   
1518        1518          BT         0                              1  0   
1519        1519          BT       127                              3  1   
1520        1520          BT         1                              0  3   
1521        1521          BT        64                              1  0   
1522        1522          BT       127                              3  1   
1523        1523          BT         0                              0  3   
1524        1524          BT        96                              2  0   
1525        1525          BT       127                              3  2   
1526        1526          BT         0                              0  3   
1527        1527          BT         0                              1  0   
1528        1528          BT       127                

# pkg, ram, total power matrix

In [5]:
pkg_matrix = np.zeros((4,4))
ram_matrix = np.zeros((4,4))
total_matrix = np.zeros((4,4))

In [6]:
pkg_matrix = confusion_matrix( bt_v['a'], bt_v['Perf_node01_power_energy_pkg_'])
ram_matrix = confusion_matrix( bt_v['b'], bt_v['Perf_node01_power_energy_ram_'])
total_matrix = confusion_matrix( bt_v['c'], bt_v['Perf_node01_power_energy_total_'])

In [7]:
pkg_matrix = pkg_matrix.astype(float)
ram_matrix = ram_matrix.astype(float)
total_matrix = total_matrix.astype(float)

## 1. pkg_matrix

In [8]:
sum = 0

for i in range(len(pkg_matrix)):
    for j in range(len(pkg_matrix)):
        sum = sum + pkg_matrix[i][j]
    for k in range(len(pkg_matrix)):
        po = pkg_matrix[i][k] / sum
        pkg_matrix[i][k] = po.round(3)
    sum = 0

In [9]:
pkg_matrix

array([[0.004, 0.309, 0.686, 0.   ],
       [0.   , 0.106, 0.156, 0.739],
       [0.058, 0.094, 0.163, 0.686],
       [0.964, 0.034, 0.002, 0.   ]])

## 2. ram_matrix

In [10]:
sum = 0

for i in range(len(ram_matrix)):
    for j in range(len(ram_matrix)):
        sum = sum + ram_matrix[i][j]
    for k in range(len(ram_matrix)):
        po = ram_matrix[i][k] / sum
        ram_matrix[i][k] = po.round(3)
    sum = 0

In [11]:
ram_matrix

array([[0.206, 0.352, 0.12 , 0.322],
       [0.151, 0.176, 0.074, 0.599],
       [0.188, 0.188, 0.148, 0.477],
       [0.707, 0.229, 0.033, 0.031]])

## 3. total_matrix

In [12]:
sum = 0

for i in range(len(total_matrix)):
    for j in range(len(total_matrix)):
        sum = sum + total_matrix[i][j]
    for k in range(len(total_matrix)):
        po = total_matrix[i][k] / sum
        total_matrix[i][k] = po.round(3)
    sum = 0

In [13]:
total_matrix

array([[0.004, 0.413, 0.583, 0.   ],
       [0.   , 0.101, 0.149, 0.75 ],
       [0.037, 0.127, 0.13 , 0.705],
       [0.963, 0.035, 0.002, 0.   ]])

# Variable count

In [14]:
np.set_printoptions(threshold=sys.maxsize)

In [15]:
pkg_var_matrix = np.zeros((4,35))
ram_var_matrix = np.zeros((4,35))
total_var_matrix = np.zeros((4,35))

In [28]:
q = bt_v['variable'].unique()
print(np.sort(q),"\n",q.size)

[  0   1   2   3   4   6   7   8  15  24  26  30  31  32  41  57  60  64
  68  70  71  92  94  95  96 102 112 118 120 121 122 123 124 126 127] 
 35


## 1. pkg + variable 

In [16]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_pkg_'], bt_v['variable'])

In [18]:
for i in range(len(pkg_var_matrix)):
    pkg_var_matrix[i] = tem_matrix[i]

In [19]:
pkg_var_matrix

array([[416.,  33.,   0.,   2.,   0.,   0.,   4.,   0.,   1.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.],
       [176.,   6.,   0.,   0.,   0.,   1.,   1.,   0.,   2.,   0.,   0.,
          0.,   1.,   1.,   0.,   0.,   0.,   7.,   0.,   0.,   1.,   0.,
          0.,   2.,   9.,   1.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,
          0.,   9.],
       [ 74.,   0.,   1.,   0.,   1.,   1.,   0.,   1.,   0.,   1.,   1.,
          1.,   0.,  18.,   1.,   1.,   1.,  15.,   2.,   2.,   0.,   1.,
          4.,   1.,  94.,   1.,  77.,   1.,  44.,   2.,   1.,   1.,   4.,
          9.,  55.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0., 447.]])

In [20]:
sum = 0

for i in range(len(pkg_var_matrix)):
    for j in range(len(pkg_var_matrix[0])):
        sum = sum + pkg_var_matrix[i][j]
    for k in range(len(pkg_var_matrix[0])):
        po = pkg_var_matrix[i][k] / sum
        pkg_var_matrix[i][k] = po.round(3)
    sum = 0

In [21]:
pkg_var_matrix

array([[0.91 , 0.072, 0.   , 0.004, 0.   , 0.   , 0.009, 0.   , 0.002,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.807, 0.028, 0.   , 0.   , 0.   , 0.005, 0.005, 0.   , 0.009,
        0.   , 0.   , 0.   , 0.005, 0.005, 0.   , 0.   , 0.   , 0.032,
        0.   , 0.   , 0.005, 0.   , 0.   , 0.009, 0.041, 0.005, 0.   ,
        0.   , 0.005, 0.   , 0.   , 0.   , 0.   , 0.   , 0.041],
       [0.178, 0.   , 0.002, 0.   , 0.002, 0.002, 0.   , 0.002, 0.   ,
        0.002, 0.002, 0.002, 0.   , 0.043, 0.002, 0.002, 0.002, 0.036,
        0.005, 0.005, 0.   , 0.002, 0.01 , 0.002, 0.226, 0.002, 0.185,
        0.002, 0.106, 0.005, 0.002, 0.002, 0.01 , 0.022, 0.132],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.

## 2. ram + variable

In [22]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_ram_'], bt_v['variable'])

In [24]:
for i in range(len(ram_var_matrix)):
    ram_var_matrix[i] = tem_matrix[i]

In [25]:
ram_var_matrix

array([[445.,  16.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,  12.,   0.,   0.,   0.,  11.,   0.,   0.,   1.,   0.,
          0.,   0.,  22.,   0.,  12.,   1.,   9.,   0.,   0.,   0.,   1.,
          2.,   2.],
       [186.,  16.,   1.,   1.,   0.,   2.,   1.,   1.,   0.,   1.,   0.,
          0.,   0.,   5.,   0.,   1.,   0.,   9.,   1.,   2.,   0.,   0.,
          3.,   1.,  68.,   2.,  46.,   0.,  21.,   0.,   1.,   1.,   1.,
          6.,  15.],
       [ 32.,   6.,   0.,   0.,   0.,   0.,   1.,   0.,   1.,   0.,   0.,
          1.,   0.,   2.,   1.,   0.,   1.,   2.,   1.,   0.,   0.,   0.,
          0.,   0.,  13.,   0.,  17.,   0.,  14.,   1.,   0.,   0.,   1.,
          0.,  34.],
       [  3.,   1.,   0.,   1.,   0.,   0.,   3.,   0.,   2.,   0.,   1.,
          0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,   1.,
          1.,   2.,   0.,   0.,   2.,   0.,   1.,   1.,   0.,   0.,   1.,
          1., 460.]])

In [26]:
sum = 0

for i in range(len(ram_var_matrix)):
    for j in range(len(ram_var_matrix[0])):
        sum = sum + ram_var_matrix[i][j]
    for k in range(len(ram_var_matrix[0])):
        po = ram_var_matrix[i][k] / sum
        ram_var_matrix[i][k] = po.round(3)
    sum = 0

In [27]:
ram_var_matrix

array([[0.832, 0.03 , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.022, 0.   , 0.   , 0.   , 0.021,
        0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.041, 0.   , 0.022,
        0.002, 0.017, 0.   , 0.   , 0.   , 0.002, 0.004, 0.004],
       [0.474, 0.041, 0.003, 0.003, 0.   , 0.005, 0.003, 0.003, 0.   ,
        0.003, 0.   , 0.   , 0.   , 0.013, 0.   , 0.003, 0.   , 0.023,
        0.003, 0.005, 0.   , 0.   , 0.008, 0.003, 0.173, 0.005, 0.117,
        0.   , 0.054, 0.   , 0.003, 0.003, 0.003, 0.015, 0.038],
       [0.25 , 0.047, 0.   , 0.   , 0.   , 0.   , 0.008, 0.   , 0.008,
        0.   , 0.   , 0.008, 0.   , 0.016, 0.008, 0.   , 0.008, 0.016,
        0.008, 0.   , 0.   , 0.   , 0.   , 0.   , 0.102, 0.   , 0.133,
        0.   , 0.109, 0.008, 0.   , 0.   , 0.008, 0.   , 0.266],
       [0.006, 0.002, 0.   , 0.002, 0.   , 0.   , 0.006, 0.   , 0.004,
        0.   , 0.002, 0.   , 0.002, 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.