<a href="https://colab.research.google.com/github/Proton214/hmm_test/blob/master/read_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import pandas as pd
import numpy as np
from hmmlearn import hmm
from sklearn.metrics import confusion_matrix

In [2]:
bt_v = pd.read_csv("application_data/CG_variable.csv")

### state : H_D = 0, L_D = 1, L_U = 2, H_U = 3

In [3]:
bt_v

Unnamed: 0 Application  variable  Perf_node01_power_energy_pkg_  a  \
0           1538          CG       127                              2  2   
1           1539          CG         0                              1  2   
2           1540          CG        70                              2  1   
3           1541          CG         0                              1  2   
4           1542          CG        94                              2  1   
5           1543          CG        68                              1  2   
6           1544          CG        94                              2  1   
7           1545          CG        94                              2  2   
8           1546          CG        94                              2  2   
9           1547          CG        94                              2  2   
10          1548          CG        94                              2  2   
11          1549          CG        94                              2  2   
12          1550          CG       126                              2  2   
13          1551          CG       126                              2  2   
14          1552          CG       127                              2  2   
15          1553          CG        95                              2  2   
16          1554          CG       127                              2  2   
17          1555          CG         0                              1  2   
18          1556          CG       127                              2  1   
19          1557          CG         0                              1  2   
20          1558          CG       126                              2  1   
21          1559          CG         0                              1  2   
22          1560          CG       127                              2  1   
23          1561          CG        33                              1  2   
24          1562          CG       127                              2  1   
25          1563          CG       127                              2  2   
26          1564          CG         1                              1  2   
27          1565          CG         0                              1  1   
28          1566          CG       102                              1  1   
29          1567          CG       127                              2  1   
...          ...         ...       ...                            ... ..   
2023        3561          CG         0                              1  1   
2024        3562          CG       127                              2  1   
2025        3563          CG        94                              2  2   
2026        3564          CG       123                              2  2   
2027        3565          CG        70                              1  2   
2028        3566          CG       127                              2  1   
2029        3567          CG        15                              1  2   
2030        3568          CG        96                              2  1   
2031        3569          CG        30                              1  2   
2032        3570          CG       127                              2  1   
2033        3571          CG        39                              2  2   
2034        3572          CG       126                              2  2   
2035        3573          CG        70                              1  2   
2036        3574          CG       127                              2  1   
2037        3575          CG         3                              1  2   
2038        3576          CG       112                              1  1   
2039        3577          CG       127                              2  1   
2040        3578          CG         1                              1  2   
2041        3579          CG       126                              1  1   
2042        3580          CG       127                              2  1   
2043        3581          CG         0                

# pkg, ram, total power matrix

In [4]:
pkg_matrix = np.zeros((4,4))
ram_matrix = np.zeros((4,4))
total_matrix = np.zeros((4,4))

In [5]:
pkg_matrix = confusion_matrix( bt_v['a'], bt_v['Perf_node01_power_energy_pkg_'])
ram_matrix = confusion_matrix( bt_v['b'], bt_v['Perf_node01_power_energy_ram_'])
total_matrix = confusion_matrix( bt_v['c'], bt_v['Perf_node01_power_energy_total_'])

In [6]:
pkg_matrix = pkg_matrix.astype(float)
ram_matrix = ram_matrix.astype(float)
total_matrix = total_matrix.astype(float)

## 1. pkg_matrix

In [7]:
sum = 0

for i in range(len(pkg_matrix)):
    for j in range(len(pkg_matrix)):
        sum = sum + pkg_matrix[i][j]
    for k in range(len(pkg_matrix)):
        po = pkg_matrix[i][k] / sum
        pkg_matrix[i][k] = po.round(3)
    sum = 0

In [8]:
pkg_matrix

array([[0.   , 0.   , 1.   , 0.   ],
       [0.   , 0.308, 0.69 , 0.002],
       [0.003, 0.662, 0.335, 0.   ],
       [0.   , 0.   , 1.   , 0.   ]])

## 2. ram_matrix

In [9]:
sum = 0

for i in range(len(ram_matrix)):
    for j in range(len(ram_matrix)):
        sum = sum + ram_matrix[i][j]
    for k in range(len(ram_matrix)):
        po = ram_matrix[i][k] / sum
        ram_matrix[i][k] = po.round(3)
    sum = 0

In [10]:
ram_matrix

array([[0.055, 0.091, 0.109, 0.745],
       [0.062, 0.349, 0.558, 0.031],
       [0.05 , 0.617, 0.323, 0.01 ],
       [0.023, 0.398, 0.516, 0.062]])

## 3. total_matrix

In [11]:
sum = 0

for i in range(len(total_matrix)):
    for j in range(len(total_matrix)):
        sum = sum + total_matrix[i][j]
    for k in range(len(total_matrix)):
        po = total_matrix[i][k] / sum
        total_matrix[i][k] = po.round(3)
    sum = 0

In [12]:
total_matrix

array([[0.   , 0.667, 0.333, 0.   ],
       [0.   , 0.344, 0.655, 0.001],
       [0.003, 0.636, 0.359, 0.002],
       [0.   , 0.333, 0.667, 0.   ]])

# Variable count

In [13]:
np.set_printoptions(threshold=sys.maxsize)

In [19]:
q = bt_v['variable'].unique()
le = q.size
print(np.sort(q),"\n",q.size)

[  0   1   2   3   4   5   6   7   8   9  10  12  14  15  16  17  20  24
  26  27  28  30  31  32  33  34  35  36  37  38  39  42  46  47  48  49
  56  57  59  60  61  62  63  64  65  66  67  68  69  70  71  78  79  82
  86  88  90  91  92  94  95  96  97  98  99 100 101 102 103 110 111 112
 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127] 
 87


In [20]:
pkg_var_matrix = np.zeros((4,le))
ram_var_matrix = np.zeros((4,le))
total_var_matrix = np.zeros((4,le))

## 1. pkg + variable 

In [21]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_pkg_'], bt_v['variable'])

In [22]:
for i in range(len(pkg_var_matrix)):
    pkg_var_matrix[i] = tem_matrix[i]

In [23]:
pkg_var_matrix

array([[  2.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [157.,  54.,  24.,  22.,   8.,   7.,  45.,  63.,   4.,   2.,   3.,
          2.,  43.,  30.,   5.,   1.,   0.,  10.,   0.,   1.,   7.,  43.,
         40.,   8.,   9.,   0.,   0.,   2.,   1.,   3.,   4.,   0.,   1.,
          2.,   5.,   2.,   9.,   2.,   0.,   5.,   1.,   8.,  23.,  31.,
         10.,   6.,   5.,   3.,   0.,  13.,  15.,   7.,   5.,   1.,   1.,
          2.,   1.,   0.,   4.,  22.,  20.,

In [24]:
sum = 0

for i in range(len(pkg_var_matrix)):
    for j in range(len(pkg_var_matrix[0])):
        sum = sum + pkg_var_matrix[i][j]
    for k in range(len(pkg_var_matrix[0])):
        po = pkg_var_matrix[i][k] / sum
        pkg_var_matrix[i][k] = po.round(3)
    sum = 0

In [25]:
pkg_var_matrix

array([[0.667, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.333, 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.157, 0.054, 0.024, 0.022, 0.008, 0.007, 0.045, 0.063, 0.004,
        0.002, 0.003, 0.002, 0.043, 0.03 , 0.005, 0.001, 0.   , 0.01 ,
        0.   , 0.001, 0.007, 0.043, 0.04 , 0.008, 0.009, 0.   , 0.   ,
        0.002, 0.001, 0.003, 0.004, 0.   , 0.001, 0.002, 0.005, 0.002,
        0.009, 0.002, 0.  

## 2. ram + variable

In [26]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_ram_'], bt_v['variable'])

In [27]:
for i in range(len(ram_var_matrix)):
    ram_var_matrix[i] = tem_matrix[i]

In [28]:
ram_var_matrix

array([[ 17.,   4.,   1.,   2.,   0.,   0.,   2.,   3.,   0.,   0.,   1.,
          1.,   3.,   2.,   0.,   0.,   0.,   2.,   0.,   0.,   1.,   5.,
          5.,   2.,   2.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,
          0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   1.,   0.,   4.,
          0.,   3.,   0.,   0.,   0.,   2.,   1.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   3.,   1.,   4.,   0.,   0.,   1.,   0.,
          1.,   4.,   3.,   0.,   1.,   1.,   0.,   0.,   0.,   1.,   0.,
          2.,   0.,   1.,   0.,   1.,   1.,   0.,   2.,   7.,  11.],
       [ 91.,  36.,  17.,  14.,   8.,   2.,  32.,  43.,   2.,   1.,   2.,
          1.,  26.,  27.,   3.,   1.,   0.,   2.,   0.,   1.,   5.,  20.,
         17.,   6.,   3.,   1.,   2.,   5.,   1.,   4.,   5.,   1.,   0.,
          2.,   5.,   0.,   3.,   0.,   0.,   2.,   1.,   5.,  18.,  27.,
          9.,   6.,   2.,   1.,   0.,  20.,  14.,   7.,   3.,   1.,   1.,
          1.,   1.,   0.,   3.,  21.,  16.,

In [29]:
sum = 0

for i in range(len(ram_var_matrix)):
    for j in range(len(ram_var_matrix[0])):
        sum = sum + ram_var_matrix[i][j]
    for k in range(len(ram_var_matrix[0])):
        po = ram_var_matrix[i][k] / sum
        ram_var_matrix[i][k] = po.round(3)
    sum = 0

In [30]:
ram_var_matrix

array([[0.153, 0.036, 0.009, 0.018, 0.   , 0.   , 0.018, 0.027, 0.   ,
        0.   , 0.009, 0.009, 0.027, 0.018, 0.   , 0.   , 0.   , 0.018,
        0.   , 0.   , 0.009, 0.045, 0.045, 0.018, 0.018, 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.009, 0.   , 0.   , 0.009,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.009, 0.   , 0.036, 0.   ,
        0.027, 0.   , 0.   , 0.   , 0.018, 0.009, 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.027, 0.009, 0.036, 0.   ,
        0.   , 0.009, 0.   , 0.009, 0.036, 0.027, 0.   , 0.009, 0.009,
        0.   , 0.   , 0.   , 0.009, 0.   , 0.018, 0.   , 0.009, 0.   ,
        0.009, 0.009, 0.   , 0.018, 0.063, 0.099],
       [0.098, 0.039, 0.018, 0.015, 0.009, 0.002, 0.034, 0.046, 0.002,
        0.001, 0.002, 0.001, 0.028, 0.029, 0.003, 0.001, 0.   , 0.002,
        0.   , 0.001, 0.005, 0.021, 0.018, 0.006, 0.003, 0.001, 0.002,
        0.005, 0.001, 0.004, 0.005, 0.001, 0.   , 0.002, 0.005, 0.   ,
        0.003, 0.   , 0.  

## 3. total + variable

In [31]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_total_'], bt_v['variable'])

In [32]:
for i in range(len(total_var_matrix)):
    total_var_matrix[i] = tem_matrix[i]

In [33]:
total_var_matrix

array([[  2.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [138.,  50.,  21.,  20.,   9.,   6.,  40.,  59.,   4.,   2.,   3.,
          2.,  40.,  31.,   5.,   1.,   0.,  10.,   0.,   1.,   6.,  36.,
         38.,   8.,   7.,   1.,   1.,   4.,   1.,   3.,   4.,   0.,   1.,
          2.,   5.,   2.,   7.,   2.,   0.,   3.,   1.,   6.,  24.,  30.,
         10.,   7.,   5.,   3.,   0.,  18.,  17.,   7.,   4.,   1.,   1.,
          1.,   1.,   0.,   4.,  21.,  21.,

In [34]:
sum = 0

for i in range(len(total_var_matrix)):
    for j in range(len(total_var_matrix[0])):
        sum = sum + total_var_matrix[i][j]
    for k in range(len(total_var_matrix[0])):
        po = total_var_matrix[i][k] / sum
        total_var_matrix[i][k] = po.round(3)
    sum = 0

In [35]:
total_var_matrix

array([[0.667, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.333, 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.137, 0.05 , 0.021, 0.02 , 0.009, 0.006, 0.04 , 0.058, 0.004,
        0.002, 0.003, 0.002, 0.04 , 0.031, 0.005, 0.001, 0.   , 0.01 ,
        0.   , 0.001, 0.006, 0.036, 0.038, 0.008, 0.007, 0.001, 0.001,
        0.004, 0.001, 0.003, 0.004, 0.   , 0.001, 0.002, 0.005, 0.002,
        0.007, 0.002, 0.  