<a href="https://colab.research.google.com/github/Proton214/hmm_test/blob/master/read_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import pandas as pd
import numpy as np
from hmmlearn import hmm
from sklearn.metrics import confusion_matrix

In [2]:
bt_v = pd.read_csv("application_data/MG_variable.csv")

### state : H_D = 0, L_D = 1, L_U = 2, H_U = 3

In [3]:
bt_v

Unnamed: 0 Application  variable  Perf_node01_power_energy_pkg_  a  \
0          6557          MG        94                              2  2   
1          6558          MG        94                              2  2   
2          6559          MG       127                              2  2   
3          6560          MG       127                              2  2   
4          6561          MG       127                              3  2   
5          6562          MG       126                              3  3   
6          6563          MG       127                              3  3   
7          6564          MG         1                              0  3   
8          6565          MG       126                              3  0   
9          6566          MG         0                              1  3   
10         6567          MG        24                              1  1   
11         6568          MG        96                              2  1   
12         6569          MG       127                              2  2   
13         6570          MG         0                              1  2   
14         6571          MG       127                              2  1   
15         6572          MG         7                              1  2   
16         6573          MG         0                              1  1   
17         6574          MG        96                              1  1   
18         6575          MG       127                              2  1   
19         6576          MG        63                              2  2   
20         6577          MG         0                              0  2   
21         6578          MG         0                              1  0   
22         6579          MG       127                              2  1   
23         6580          MG       127                              2  2   
24         6581          MG         0                              1  2   
25         6582          MG       126                              2  1   
26         6583          MG       127                              2  2   
27         6584          MG        56                              2  2   
28         6585          MG       127                              1  2   
29         6586          MG         0                              1  1   
..          ...         ...       ...                            ... ..   
148        6705          MG        96                              1  1   
149        6706          MG        63                              2  1   
150        6707          MG       123                              2  2   
151        6708          MG       103                              1  2   
152        6709          MG         0                              1  1   
153        6710          MG        63                              2  1   
154        6711          MG       127                              2  2   
155        6712          MG         0                              1  2   
156        6713          MG       112                              2  1   
157        6714          MG       127                              2  2   
158        6715          MG       123                              2  2   
159        6716          MG         2                              1  2   
160        6717          MG        96                              2  1   
161        6718          MG        25                              1  2   
162        6719          MG       127                              2  1   
163        6720          MG         0                              1  2   
164        6721          MG       126                              2  1   
165        6722          MG       127                              2  2   
166        6723          MG        31                              1  2   
167        6724          MG        64                              1  1   
168        6725          MG       127                              2  1   
169        6726          MG   

# pkg, ram, total power matrix

In [4]:
pkg_matrix = np.zeros((4,4))
ram_matrix = np.zeros((4,4))
total_matrix = np.zeros((4,4))

In [5]:
pkg_matrix = confusion_matrix( bt_v['a'], bt_v['Perf_node01_power_energy_pkg_'])
ram_matrix = confusion_matrix( bt_v['b'], bt_v['Perf_node01_power_energy_ram_'])
total_matrix = confusion_matrix( bt_v['c'], bt_v['Perf_node01_power_energy_total_'])

In [6]:
pkg_matrix = pkg_matrix.astype(float)
ram_matrix = ram_matrix.astype(float)
total_matrix = total_matrix.astype(float)

## 1. pkg_matrix

In [7]:
sum = 0

for i in range(len(pkg_matrix)):
    for j in range(len(pkg_matrix)):
        sum = sum + pkg_matrix[i][j]
    for k in range(len(pkg_matrix)):
        po = pkg_matrix[i][k] / sum
        pkg_matrix[i][k] = po.round(3)
    sum = 0

In [8]:
pkg_matrix

array([[0.   , 0.25 , 0.5  , 0.25 ],
       [0.029, 0.357, 0.586, 0.029],
       [0.02 , 0.429, 0.541, 0.01 ],
       [0.167, 0.333, 0.167, 0.333]])

## 2. ram_matrix

In [9]:
sum = 0

for i in range(len(ram_matrix)):
    for j in range(len(ram_matrix)):
        sum = sum + ram_matrix[i][j]
    for k in range(len(ram_matrix)):
        po = ram_matrix[i][k] / sum
        ram_matrix[i][k] = po.round(3)
    sum = 0

In [10]:
ram_matrix

array([[0.25 , 0.125, 0.375, 0.25 ],
       [0.037, 0.432, 0.457, 0.074],
       [0.041, 0.527, 0.392, 0.041],
       [0.067, 0.4  , 0.267, 0.267]])

## 3. total_matrix

In [11]:
sum = 0

for i in range(len(total_matrix)):
    for j in range(len(total_matrix)):
        sum = sum + total_matrix[i][j]
    for k in range(len(total_matrix)):
        po = total_matrix[i][k] / sum
        total_matrix[i][k] = po.round(3)
    sum = 0

In [12]:
total_matrix

array([[0.   , 0.333, 0.333, 0.333],
       [0.028, 0.389, 0.569, 0.014],
       [0.01 , 0.433, 0.536, 0.021],
       [0.167, 0.167, 0.333, 0.333]])

# Variable count

In [13]:
np.set_printoptions(threshold=sys.maxsize)

In [14]:
q = bt_v['variable'].unique()
le = q.size
print(np.sort(q),"\n",q.size)

[  0   1   2   3   4   6   7  13  24  25  27  29  31  39  56  59  61  63
  64  94  96 100 103 112 114 118 119 121 123 124 126 127] 
 32


In [15]:
pkg_var_matrix = np.zeros((4,le))
ram_var_matrix = np.zeros((4,le))
total_var_matrix = np.zeros((4,le))

## 1. pkg + variable 

In [16]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_pkg_'], bt_v['variable'])

In [17]:
for i in range(len(pkg_var_matrix)):
    pkg_var_matrix[i] = tem_matrix[i]

In [18]:
pkg_var_matrix

array([[ 4.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.],
       [35.,  2.,  1.,  3.,  1.,  1.,  2.,  1.,  1.,  3.,  1.,  1.,  2.,
         1.,  0.,  1.,  0.,  0.,  2.,  0.,  6.,  0.,  2.,  0.,  0.,  0.,
         1.,  0.,  0.,  0.,  0.,  3.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  3.,
         0.,  1.,  1.,  1.,  6.,  0.,  3.,  4.,  1.,  1.,  3.,  2.,  1.,
         0.,  1.,  2.,  1., 12., 53.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  2.,  4.]])

In [19]:
sum = 0

for i in range(len(pkg_var_matrix)):
    for j in range(len(pkg_var_matrix[0])):
        sum = sum + pkg_var_matrix[i][j]
    for k in range(len(pkg_var_matrix[0])):
        po = pkg_var_matrix[i][k] / sum
        pkg_var_matrix[i][k] = po.round(3)
    sum = 0

In [20]:
pkg_var_matrix

array([[0.8  , 0.2  , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.5  , 0.029, 0.014, 0.043, 0.014, 0.014, 0.029, 0.014, 0.014,
        0.043, 0.014, 0.014, 0.029, 0.014, 0.   , 0.014, 0.   , 0.   ,
        0.029, 0.   , 0.086, 0.   , 0.029, 0.   , 0.   , 0.   , 0.014,
        0.   , 0.   , 0.   , 0.   , 0.043],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.01 , 0.031, 0.   , 0.01 , 0.01 , 0.01 , 0.062,
        0.   , 0.031, 0.041, 0.01 , 0.01 , 0.031, 0.021, 0.01 , 0.   ,
        0.01 , 0.021, 0.01 , 0.124, 0.546],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0

## 2. ram + variable

In [21]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_ram_'], bt_v['variable'])

In [22]:
for i in range(len(ram_var_matrix)):
    ram_var_matrix[i] = tem_matrix[i]

In [23]:
ram_var_matrix

array([[ 4.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
         1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  2.,  0.],
       [28.,  2.,  1.,  2.,  1.,  1.,  1.,  1.,  0.,  1.,  1.,  1.,  2.,
         0.,  1.,  0.,  0.,  1.,  2.,  0.,  6.,  0.,  2.,  2.,  1.,  0.,
         1.,  0.,  0.,  1.,  4., 18.],
       [ 7.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  2.,  0.,  1.,  3.,
         0.,  0.,  1.,  1.,  5.,  0.,  2.,  4.,  1.,  1.,  1.,  1.,  1.,
         0.,  1.,  1.,  0.,  6., 32.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  1.,  0.,  2., 10.]])

In [24]:
sum = 0

for i in range(len(ram_var_matrix)):
    for j in range(len(ram_var_matrix[0])):
        sum = sum + ram_var_matrix[i][j]
    for k in range(len(ram_var_matrix[0])):
        po = ram_var_matrix[i][k] / sum
        ram_var_matrix[i][k] = po.round(3)
    sum = 0

In [25]:
ram_var_matrix

array([[0.444, 0.111, 0.   , 0.   , 0.   , 0.   , 0.111, 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.111, 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.222, 0.   ],
       [0.346, 0.025, 0.012, 0.025, 0.012, 0.012, 0.012, 0.012, 0.   ,
        0.012, 0.012, 0.012, 0.025, 0.   , 0.012, 0.   , 0.   , 0.012,
        0.025, 0.   , 0.074, 0.   , 0.025, 0.025, 0.012, 0.   , 0.012,
        0.   , 0.   , 0.012, 0.049, 0.222],
       [0.096, 0.   , 0.   , 0.014, 0.   , 0.   , 0.   , 0.   , 0.014,
        0.027, 0.   , 0.014, 0.041, 0.   , 0.   , 0.014, 0.014, 0.068,
        0.   , 0.027, 0.055, 0.014, 0.014, 0.014, 0.014, 0.014, 0.   ,
        0.014, 0.014, 0.   , 0.082, 0.438],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.067, 0.   , 0.   ,
        0.   , 0.067, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0

## 3. total + variable

In [26]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_total_'], bt_v['variable'])

In [27]:
for i in range(len(total_var_matrix)):
    total_var_matrix[i] = tem_matrix[i]

In [28]:
total_var_matrix

array([[ 3.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.],
       [35.,  2.,  1.,  3.,  1.,  1.,  2.,  1.,  1.,  2.,  1.,  2.,  2.,
         1.,  0.,  0.,  0.,  0.,  2.,  0.,  6.,  0.,  3.,  0.,  0.,  0.,
         1.,  0.,  0.,  0.,  1.,  4.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  3.,
         0.,  1.,  2.,  1.,  6.,  0.,  3.,  4.,  1.,  0.,  3.,  2.,  1.,
         0.,  1.,  2.,  1., 11., 52.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  2.,  4.]])

In [29]:
sum = 0

for i in range(len(total_var_matrix)):
    for j in range(len(total_var_matrix[0])):
        sum = sum + total_var_matrix[i][j]
    for k in range(len(total_var_matrix[0])):
        po = total_var_matrix[i][k] / sum
        total_var_matrix[i][k] = po.round(3)
    sum = 0

In [30]:
total_var_matrix

array([[0.75 , 0.25 , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.486, 0.028, 0.014, 0.042, 0.014, 0.014, 0.028, 0.014, 0.014,
        0.028, 0.014, 0.028, 0.028, 0.014, 0.   , 0.   , 0.   , 0.   ,
        0.028, 0.   , 0.083, 0.   , 0.042, 0.   , 0.   , 0.   , 0.014,
        0.   , 0.   , 0.   , 0.014, 0.056],
       [0.01 , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.01 , 0.   , 0.   , 0.031, 0.   , 0.01 , 0.021, 0.01 , 0.062,
        0.   , 0.031, 0.042, 0.01 , 0.   , 0.031, 0.021, 0.01 , 0.   ,
        0.01 , 0.021, 0.01 , 0.115, 0.542],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0