<a href="https://colab.research.google.com/github/Proton214/hmm_test/blob/master/read_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import pandas as pd
import numpy as np
from hmmlearn import hmm
from sklearn.metrics import confusion_matrix

In [2]:
bt_v = pd.read_csv("application_data/BT_variable.csv")

### state : H_D = 0, L_D = 1, L_U = 2, H_U = 3

In [3]:
bt_v

Unnamed: 0 Application  variable  Perf_node01_power_energy_pkg_   a  \
0            0.0          BT        94                              2   2   
1            1.0          BT       127                              2   2   
2            2.0          BT        95                              2   2   
3            3.0          BT       121                              2   2   
4            4.0          BT       127                              3   2   
5            5.0          BT         0                              0   3   
6            6.0          BT       112                              2   0   
7            7.0          BT         0                              1   2   
8            8.0          BT       127                              2   1   
9            9.0          BT         0                              1   2   
10          10.0          BT         6                              2   1   
11          11.0          BT       127                              3   2   
12          12.0          BT         0                              0   3   
13          13.0          BT        64                              2   0   
14          14.0          BT       127                              3   2   
15          15.0          BT         0                              0   3   
16          16.0          BT         0                              2   0   
17          17.0          BT       127                              3   2   
18          18.0          BT         0                              1   3   
19          19.0          BT         0                              1   1   
20          20.0          BT       127                              3   1   
21          21.0          BT         0                              0   3   
22          22.0          BT         0                              1   0   
23          23.0          BT       127                              3   1   
24          24.0          BT         0                              0   3   
25          25.0          BT         0                              1   0   
26          26.0          BT       127                              3   1   
27          27.0          BT         0                              0   3   
28          28.0          BT       112                              2   0   
29          29.0          BT       127                              3   2   
...          ...         ...       ...                            ...  ..   
1636         NaN         NaN        98                             10  10   
1637         NaN         NaN        99                             10  10   
1638         NaN         NaN       100                             10  10   
1639         NaN         NaN       101                             10  10   
1640         NaN         NaN       102                             10  10   
1641         NaN         NaN       103                             10  10   
1642         NaN         NaN       104                             10  10   
1643         NaN         NaN       105                             10  10   
1644         NaN         NaN       106                             10  10   
1645         NaN         NaN       107                             10  10   
1646         NaN         NaN       108                             10  10   
1647         NaN         NaN       109                             10  10   
1648         NaN         NaN       110                             10  10   
1649         NaN         NaN       111                             10  10   
1650         NaN         NaN       112                             10  10   
1651         NaN         NaN       113                             10  10   
1652         NaN         NaN       114                             10  10   
1653         NaN         NaN       115                             10  10   
1654         NaN         NaN       116                             10  10   
1655         NaN         NaN       117                             10  10   
16

# pkg, ram, total power matrix

In [70]:
pkg_matrix = np.zeros((4,4))
ram_matrix = np.zeros((4,4))
total_matrix = np.zeros((4,4))

In [40]:
pkg_matrix = confusion_matrix( bt_v['a'], bt_v['Perf_node01_power_energy_pkg_'])
ram_matrix = confusion_matrix( bt_v['b'], bt_v['Perf_node01_power_energy_ram_'])
total_matrix = confusion_matrix( bt_v['c'], bt_v['Perf_node01_power_energy_total_'])

In [41]:
pkg_matrix = pkg_matrix.astype(float)
ram_matrix = ram_matrix.astype(float)
total_matrix = total_matrix.astype(float)

## 1. pkg_matrix

In [46]:
sum = 0

for i in range(len(pkg_matrix)):
    for j in range(len(pkg_matrix)):
        sum = sum + pkg_matrix[i][j]
    for k in range(len(pkg_matrix)):
        po = pkg_matrix[i][k] / sum
        pkg_matrix[i][k] = po.round(3)
    sum = 0

In [47]:
pkg_matrix

array([[0.004, 0.309, 0.687, 0.   , 0.   ],
       [0.   , 0.106, 0.156, 0.738, 0.   ],
       [0.058, 0.094, 0.163, 0.685, 0.   ],
       [0.964, 0.034, 0.002, 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 1.   ]])

## 2. ram_matrix

In [48]:
sum = 0

for i in range(len(ram_matrix)):
    for j in range(len(ram_matrix)):
        sum = sum + ram_matrix[i][j]
    for k in range(len(ram_matrix)):
        po = ram_matrix[i][k] / sum
        ram_matrix[i][k] = po.round(3)
    sum = 0

In [49]:
ram_matrix

array([[0.206, 0.352, 0.12 , 0.322, 0.   ],
       [0.151, 0.176, 0.074, 0.599, 0.   ],
       [0.188, 0.188, 0.148, 0.477, 0.   ],
       [0.707, 0.229, 0.033, 0.031, 0.   ],
       [0.   , 0.   , 0.   , 0.   , 1.   ]])

## 3. total_matrix

In [50]:
sum = 0

for i in range(len(total_matrix)):
    for j in range(len(total_matrix)):
        sum = sum + total_matrix[i][j]
    for k in range(len(total_matrix)):
        po = total_matrix[i][k] / sum
        total_matrix[i][k] = po.round(3)
    sum = 0

In [51]:
total_matrix

array([[0.004, 0.413, 0.583, 0.   , 0.   ],
       [0.   , 0.101, 0.149, 0.75 , 0.   ],
       [0.037, 0.127, 0.13 , 0.705, 0.   ],
       [0.963, 0.035, 0.002, 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 1.   ]])

# Variable count

In [52]:
np.set_printoptions(threshold=sys.maxsize)

In [53]:
pkg_var_matrix = np.zeros((4,128))
ram_var_matrix = np.zeros((4,128))
total_var_matrix = np.zeros((4,128))

In [54]:
q = bt_v['variable'].unique()
print(np.sort(q),"\n",q.size)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127] 
 128


## 1. pkg + variable 

In [55]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_pkg_'], bt_v['variable'])

In [56]:
for i in range(len(pkg_var_matrix)):
    pkg_var_matrix[i] = tem_matrix[i]

In [57]:
pkg_var_matrix

array([[416.,  33.,   0.,   2.,   0.,   0.,   0.,   4.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [176.,   6.,   0.,   0.,   0.,   0.,   1.,   1.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   2.,   0.,   0.,   0.,   0.,

In [58]:
sum = 0

for i in range(len(pkg_var_matrix)):
    for j in range(len(pkg_var_matrix[0])):
        sum = sum + pkg_var_matrix[i][j]
    for k in range(len(pkg_var_matrix[0])):
        po = pkg_var_matrix[i][k] / sum
        pkg_var_matrix[i][k] = po.round(3)
    sum = 0

In [59]:
pkg_var_matrix

array([[0.91 , 0.072, 0.   , 0.004, 0.   , 0.   , 0.   , 0.009, 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
      

## 2. ram + variable

In [60]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_ram_'], bt_v['variable'])

In [61]:
for i in range(len(ram_var_matrix)):
    ram_var_matrix[i] = tem_matrix[i]

In [62]:
ram_var_matrix

array([[445.,  16.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  12.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  11.,   0.,
          0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  22.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,  12.,   0.,   0.,   0.,   0.,   0.,   1.,   0.,   9.,
          0.,   0.,   0.,   1.,   0.,   2.,   2.],
       [186.,  16.,   1.,   1.,   0.,   0.,   2.,   1.,   1.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,

In [63]:
sum = 0

for i in range(len(ram_var_matrix)):
    for j in range(len(ram_var_matrix[0])):
        sum = sum + ram_var_matrix[i][j]
    for k in range(len(ram_var_matrix[0])):
        po = ram_var_matrix[i][k] / sum
        ram_var_matrix[i][k] = po.round(3)
    sum = 0

In [64]:
ram_var_matrix

array([[0.832, 0.03 , 0.   , 0.   , 0.002, 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.022, 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.021, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.041, 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.022, 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.002, 0.   , 0.017, 0.   , 0.   , 0.   , 0.002, 0.   ,
      

## 3. total + variable

In [65]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_total_'], bt_v['variable'])

In [66]:
for i in range(len(total_var_matrix)):
    total_var_matrix[i] = tem_matrix[i]

In [67]:
total_var_matrix

array([[422.,  30.,   0.,   2.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [198.,   8.,   1.,   0.,   1.,   0.,   2.,   5.,   1.,   0.,   0.,
          0.,   0.,   0.,   0.,   3.,   0.,   0.,   0.,   0.,

In [68]:
sum = 0

for i in range(len(total_var_matrix)):
    for j in range(len(total_var_matrix[0])):
        sum = sum + total_var_matrix[i][j]
    for k in range(len(total_var_matrix[0])):
        po = total_var_matrix[i][k] / sum
        total_var_matrix[i][k] = po.round(3)
    sum = 0

In [69]:
total_var_matrix

array([[0.93 , 0.066, 0.   , 0.004, 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
      