<a href="https://colab.research.google.com/github/Proton214/hmm_test/blob/master/read_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import pandas as pd
import numpy as np
from hmmlearn import hmm
from sklearn.metrics import confusion_matrix

In [2]:
bt_v = pd.read_csv("application_data/TOTAL_variable.csv")

### state : H_D = 0, L_D = 1, L_U = 2, H_U = 3

In [3]:
bt_v

Unnamed: 0 Application  variable  Perf_node01_power_energy_pkg_  a  \
0              0          BT        94                              2  2   
1              1          BT       127                              2  2   
2              2          BT        95                              2  2   
3              3          BT       121                              2  2   
4              4          BT       127                              3  2   
5              5          BT         0                              0  3   
6              6          BT       112                              2  0   
7              7          BT         0                              1  2   
8              8          BT       127                              2  1   
9              9          BT         0                              1  2   
10            10          BT         6                              2  1   
11            11          BT       127                              3  2   
12            12          BT         0                              0  3   
13            13          BT        64                              2  0   
14            14          BT       127                              3  2   
15            15          BT         0                              0  3   
16            16          BT         0                              2  0   
17            17          BT       127                              3  2   
18            18          BT         0                              1  3   
19            19          BT         0                              1  1   
20            20          BT       127                              3  1   
21            21          BT         0                              0  3   
22            22          BT         0                              1  0   
23            23          BT       127                              3  1   
24            24          BT         0                              0  3   
25            25          BT         0                              1  0   
26            26          BT       127                              3  1   
27            27          BT         0                              0  3   
28            28          BT       112                              2  0   
29            29          BT       127                              3  2   
...          ...         ...       ...                            ... ..   
9086        9086          SP       126                              2  0   
9087        9087          SP         0                              1  2   
9088        9088          SP       127                              3  1   
9089        9089          SP       127                              2  3   
9090        9090          SP         0                              1  2   
9091        9091          SP       127                              2  1   
9092        9092          SP         0                              0  2   
9093        9093          SP       127                              2  0   
9094        9094          SP         0                              1  2   
9095        9095          SP       126                              2  1   
9096        9096          SP       127                              2  2   
9097        9097          SP         0                              1  2   
9098        9098          SP        36                              2  1   
9099        9099          SP        11                              1  2   
9100        9100          SP        96                              2  1   
9101        9101          SP        31                              1  2   
9102        9102          SP       120                              2  1   
9103        9103          SP       127                              2  2   
9104        9104          SP         0                              1  2   
9105        9105          SP       114                              2  1   
9106        9106          SP       127                

# pkg, ram, total power matrix

In [4]:
pkg_matrix = np.zeros((4,4))
ram_matrix = np.zeros((4,4))
total_matrix = np.zeros((4,4))

In [5]:
pkg_matrix = confusion_matrix( bt_v['a'], bt_v['Perf_node01_power_energy_pkg_'])
ram_matrix = confusion_matrix( bt_v['b'], bt_v['Perf_node01_power_energy_ram_'])
total_matrix = confusion_matrix( bt_v['c'], bt_v['Perf_node01_power_energy_total_'])

In [6]:
pkg_matrix = pkg_matrix.astype(float)
ram_matrix = ram_matrix.astype(float)
total_matrix = total_matrix.astype(float)

## 1. pkg_matrix

In [7]:
sum = 0

for i in range(len(pkg_matrix)):
    for j in range(len(pkg_matrix)):
        sum = sum + pkg_matrix[i][j]
    for k in range(len(pkg_matrix)):
        po = pkg_matrix[i][k] / sum
        pkg_matrix[i][k] = po.round(3)
    sum = 0

In [8]:
pkg_matrix

array([[0.02 , 0.193, 0.426, 0.36 ],
       [0.021, 0.237, 0.637, 0.105],
       [0.055, 0.56 , 0.303, 0.082],
       [0.771, 0.173, 0.051, 0.006]])

## 2. ram_matrix

In [9]:
sum = 0

for i in range(len(ram_matrix)):
    for j in range(len(ram_matrix)):
        sum = sum + ram_matrix[i][j]
    for k in range(len(ram_matrix)):
        po = ram_matrix[i][k] / sum
        ram_matrix[i][k] = po.round(3)
    sum = 0

In [10]:
ram_matrix

array([[0.118, 0.177, 0.141, 0.564],
       [0.071, 0.269, 0.539, 0.121],
       [0.089, 0.573, 0.3  , 0.038],
       [0.503, 0.269, 0.153, 0.075]])

## 3. total_matrix

In [11]:
sum = 0

for i in range(len(total_matrix)):
    for j in range(len(total_matrix)):
        sum = sum + total_matrix[i][j]
    for k in range(len(total_matrix)):
        po = total_matrix[i][k] / sum
        total_matrix[i][k] = po.round(3)
    sum = 0

In [12]:
total_matrix

array([[0.028, 0.228, 0.403, 0.34 ],
       [0.021, 0.246, 0.616, 0.117],
       [0.052, 0.568, 0.304, 0.075],
       [0.744, 0.175, 0.07 , 0.011]])

# Variable count

In [13]:
np.set_printoptions(threshold=sys.maxsize)

In [14]:
q = bt_v['variable'].unique()
le = q.size
print(np.sort(q),"\n",q.size)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  20  22  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39
  41  42  46  47  48  49  50  54  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  75  78  79  80  82  86  88  89  90  91  92  93
  94  95  96  97  98  99 100 101 102 103 108 109 110 111 112 113 114 115
 116 117 118 119 120 121 122 123 124 125 126 127] 
 102


In [15]:
pkg_var_matrix = np.zeros((4,le))
ram_var_matrix = np.zeros((4,le))
total_var_matrix = np.zeros((4,le))

## 1. pkg + variable 

In [16]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_pkg_'], bt_v['variable'])

In [17]:
for i in range(len(pkg_var_matrix)):
    pkg_var_matrix[i] = tem_matrix[i]

In [18]:
pkg_var_matrix

array([[9.200e+02, 1.250e+02, 0.000e+00, 1.800e+01, 0.000e+00, 1.000e+00,
        0.000e+00, 1.700e+01, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 6.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 1.000e+01, 0.000e+00, 5.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+0

In [19]:
sum = 0

for i in range(len(pkg_var_matrix)):
    for j in range(len(pkg_var_matrix[0])):
        sum = sum + pkg_var_matrix[i][j]
    for k in range(len(pkg_var_matrix[0])):
        po = pkg_var_matrix[i][k] / sum
        pkg_var_matrix[i][k] = po.round(3)
    sum = 0

In [20]:
pkg_var_matrix

array([[0.833, 0.113, 0.   , 0.016, 0.   , 0.001, 0.   , 0.015, 0.   ,
        0.   , 0.   , 0.001, 0.   , 0.   , 0.   , 0.005, 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.009, 0.   , 0.005, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.001, 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   ],
       [0.37 , 0.081, 0.011, 0.023, 0.008, 0.006, 0.018, 0.041, 0.002,
        0.002, 0.001, 0.001, 0.001, 0.001, 0.013, 0.021, 0.002, 0.   ,
        0.   , 0.   , 0.008, 0.006, 0.001, 0.00

## 2. ram + variable

In [21]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_ram_'], bt_v['variable'])

In [22]:
for i in range(len(ram_var_matrix)):
    ram_var_matrix[i] = tem_matrix[i]

In [23]:
ram_var_matrix

array([[8.920e+02, 6.700e+01, 2.000e+00, 8.000e+00, 1.000e+00, 1.000e+00,
        2.000e+00, 1.100e+01, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00,
        1.000e+00, 0.000e+00, 3.000e+00, 3.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 2.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        1.000e+00, 0.000e+00, 5.000e+00, 5.000e+00, 2.000e+01, 5.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00,
        0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 1.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 2.000e+00, 0.000e+00, 2.200e+01, 0.000e+00,
        3.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 6.000e+00, 2.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        8.000e+00, 2.000e+00, 4.500e+01, 4.000e+00, 3.000e+00, 2.000e+00,
        4.000e+00, 5.000e+00, 1.100e+0

In [24]:
sum = 0

for i in range(len(ram_var_matrix)):
    for j in range(len(ram_var_matrix[0])):
        sum = sum + ram_var_matrix[i][j]
    for k in range(len(ram_var_matrix[0])):
        po = ram_var_matrix[i][k] / sum
        ram_var_matrix[i][k] = po.round(3)
    sum = 0

In [25]:
ram_var_matrix

array([[0.654, 0.049, 0.001, 0.006, 0.001, 0.001, 0.001, 0.008, 0.   ,
        0.   , 0.001, 0.   , 0.001, 0.   , 0.002, 0.002, 0.   , 0.   ,
        0.   , 0.   , 0.001, 0.   , 0.   , 0.   , 0.001, 0.   , 0.004,
        0.004, 0.015, 0.004, 0.   , 0.   , 0.   , 0.   , 0.001, 0.001,
        0.   , 0.001, 0.001, 0.   , 0.   , 0.001, 0.   , 0.   , 0.   ,
        0.   , 0.001, 0.   , 0.   , 0.   , 0.001, 0.   , 0.016, 0.   ,
        0.002, 0.   , 0.   , 0.   , 0.004, 0.001, 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.006, 0.001, 0.033, 0.003, 0.002, 0.001, 0.003, 0.004, 0.008,
        0.007, 0.   , 0.   , 0.   , 0.001, 0.01 , 0.   , 0.   , 0.   ,
        0.001, 0.001, 0.002, 0.004, 0.007, 0.   , 0.001, 0.001, 0.004,
        0.001, 0.031, 0.081],
       [0.336, 0.074, 0.008, 0.02 , 0.006, 0.004, 0.013, 0.033, 0.002,
        0.001, 0.001, 0.001, 0.   , 0.001, 0.008, 0.019, 0.001, 0.   ,
        0.   , 0.   , 0.002, 0.001, 0.   , 0.00

## 3. total + variable

In [26]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_total_'], bt_v['variable'])

In [27]:
for i in range(len(total_var_matrix)):
    total_var_matrix[i] = tem_matrix[i]

In [28]:
total_var_matrix

array([[9.130e+02, 1.130e+02, 0.000e+00, 1.700e+01, 0.000e+00, 1.000e+00,
        0.000e+00, 1.200e+01, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 2.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 5.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+0

In [29]:
sum = 0

for i in range(len(total_var_matrix)):
    for j in range(len(total_var_matrix[0])):
        sum = sum + total_var_matrix[i][j]
    for k in range(len(total_var_matrix[0])):
        po = total_var_matrix[i][k] / sum
        total_var_matrix[i][k] = po.round(3)
    sum = 0

In [30]:
total_var_matrix

array([[0.856, 0.106, 0.   , 0.016, 0.   , 0.001, 0.   , 0.011, 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.002, 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.005, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.001, 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.001, 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.001, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   ],
       [0.37 , 0.08 , 0.01 , 0.022, 0.008, 0.006, 0.015, 0.04 , 0.002,
        0.001, 0.001, 0.001, 0.001, 0.001, 0.012, 0.022, 0.001, 0.   ,
        0.   , 0.   , 0.008, 0.005, 0.001, 0.00