<a href="https://colab.research.google.com/github/Proton214/hmm_test/blob/master/read_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sys
import pandas as pd
import numpy as np
from hmmlearn import hmm
from sklearn.metrics import confusion_matrix

In [2]:
bt_v = pd.read_csv("application_data/SP_variable.csv")

### state : H_D = 0, L_D = 1, L_U = 2, H_U = 3

In [3]:
bt_v

Unnamed: 0 Application  variable  Perf_node01_power_energy_pkg_  a  \
0           6735          SP        94                              2  2   
1           6736          SP        94                              2  2   
2           6737          SP       126                              2  2   
3           6738          SP       127                              2  2   
4           6739          SP        95                              2  2   
5           6740          SP       127                              3  2   
6           6741          SP        15                              0  3   
7           6742          SP       118                              3  0   
8           6743          SP         0                              0  3   
9           6744          SP       127                              2  0   
10          6745          SP       127                              2  2   
11          6746          SP       120                              2  2   
12          6747          SP         1                              1  2   
13          6748          SP         0                              1  1   
14          6749          SP       127                              2  1   
15          6750          SP         0                              1  2   
16          6751          SP       127                              2  1   
17          6752          SP       126                              2  2   
18          6753          SP         0                              1  2   
19          6754          SP       127                              2  1   
20          6755          SP         0                              0  2   
21          6756          SP       127                              2  0   
22          6757          SP         0                              1  2   
23          6758          SP       127                              2  1   
24          6759          SP       127                              2  2   
25          6760          SP         0                              1  2   
26          6761          SP         7                              1  1   
27          6762          SP       120                              1  1   
28          6763          SP         7                              1  1   
29          6764          SP         0                              1  1   
...          ...         ...       ...                            ... ..   
2351        9086          SP       126                              2  0   
2352        9087          SP         0                              1  2   
2353        9088          SP       127                              3  1   
2354        9089          SP       127                              2  3   
2355        9090          SP         0                              1  2   
2356        9091          SP       127                              2  1   
2357        9092          SP         0                              0  2   
2358        9093          SP       127                              2  0   
2359        9094          SP         0                              1  2   
2360        9095          SP       126                              2  1   
2361        9096          SP       127                              2  2   
2362        9097          SP         0                              1  2   
2363        9098          SP        36                              2  1   
2364        9099          SP        11                              1  2   
2365        9100          SP        96                              2  1   
2366        9101          SP        31                              1  2   
2367        9102          SP       120                              2  1   
2368        9103          SP       127                              2  2   
2369        9104          SP         0                              1  2   
2370        9105          SP       114                              2  1   
2371        9106          SP       127                

# pkg, ram, total power matrix

In [4]:
pkg_matrix = np.zeros((4,4))
ram_matrix = np.zeros((4,4))
total_matrix = np.zeros((4,4))

In [5]:
pkg_matrix = confusion_matrix( bt_v['a'], bt_v['Perf_node01_power_energy_pkg_'])
ram_matrix = confusion_matrix( bt_v['b'], bt_v['Perf_node01_power_energy_ram_'])
total_matrix = confusion_matrix( bt_v['c'], bt_v['Perf_node01_power_energy_total_'])

In [6]:
pkg_matrix = pkg_matrix.astype(float)
ram_matrix = ram_matrix.astype(float)
total_matrix = total_matrix.astype(float)

## 1. pkg_matrix

In [7]:
sum = 0

for i in range(len(pkg_matrix)):
    for j in range(len(pkg_matrix)):
        sum = sum + pkg_matrix[i][j]
    for k in range(len(pkg_matrix)):
        po = pkg_matrix[i][k] / sum
        pkg_matrix[i][k] = po.round(3)
    sum = 0

In [8]:
pkg_matrix

array([[0.   , 0.   , 0.476, 0.524],
       [0.002, 0.096, 0.877, 0.024],
       [0.124, 0.58 , 0.293, 0.002],
       [0.09 , 0.766, 0.135, 0.009]])

## 2. ram_matrix

In [9]:
sum = 0

for i in range(len(ram_matrix)):
    for j in range(len(ram_matrix)):
        sum = sum + ram_matrix[i][j]
    for k in range(len(ram_matrix)):
        po = ram_matrix[i][k] / sum
        ram_matrix[i][k] = po.round(3)
    sum = 0

In [10]:
ram_matrix

array([[0.   , 0.022, 0.385, 0.593],
       [0.005, 0.165, 0.777, 0.053],
       [0.105, 0.595, 0.299, 0.002],
       [0.058, 0.64 , 0.259, 0.043]])

## 3. total_matrix

In [11]:
sum = 0

for i in range(len(total_matrix)):
    for j in range(len(total_matrix)):
        sum = sum + total_matrix[i][j]
    for k in range(len(total_matrix)):
        po = total_matrix[i][k] / sum
        total_matrix[i][k] = po.round(3)
    sum = 0

In [12]:
total_matrix

array([[0.   , 0.   , 0.464, 0.536],
       [0.002, 0.095, 0.873, 0.029],
       [0.116, 0.592, 0.289, 0.002],
       [0.079, 0.728, 0.167, 0.026]])

# Variable count

In [13]:
np.set_printoptions(threshold=sys.maxsize)

In [14]:
q = bt_v['variable'].unique()
le = q.size
print(np.sort(q),"\n",q.size)

[  0   1   2   3   4   5   6   7   8  11  13  15  26  28  29  30  31  32
  33  34  36  38  39  47  48  56  57  58  59  62  63  64  65  67  70  71
  75  79  89  94  95  96  97  98 100 102 103 111 112 114 116 117 118 119
 120 122 124 126 127] 
 59


In [15]:
pkg_var_matrix = np.zeros((4,le))
ram_var_matrix = np.zeros((4,le))
total_var_matrix = np.zeros((4,le))

## 1. pkg + variable 

In [16]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_pkg_'], bt_v['variable'])

In [17]:
for i in range(len(pkg_var_matrix)):
    pkg_var_matrix[i] = tem_matrix[i]

In [18]:
pkg_var_matrix

array([[152.,  11.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.],
       [495.,  88.,   1.,  22.,   1.,   2.,   1.,  40.,   2.,   2.,   1.,
         29.,   1.,   1.,   1.,   1.,  77.,   5.,   1.,   0.,   0.,   0.,
          0.,   0.,   1.,   1.,   1.,   0.,   0.,   0.,  14.,  23.,   2.,
          1.,   0.,   1.,   2.,   1.,   1.,   1.,  18.,   7.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,
          0.,   0.,   0.,  35.],
       [ 17.,   1.,   0.,   1.,   0.,   1.,   1.,   1.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   4.,   9.,   0.,   1.,   1.,   1.,
          2.,   2.,   1.,   0.,   0.,   1.,   

In [19]:
sum = 0

for i in range(len(pkg_var_matrix)):
    for j in range(len(pkg_var_matrix[0])):
        sum = sum + pkg_var_matrix[i][j]
    for k in range(len(pkg_var_matrix[0])):
        po = pkg_var_matrix[i][k] / sum
        pkg_var_matrix[i][k] = po.round(3)
    sum = 0

In [20]:
pkg_var_matrix

array([[0.927, 0.067, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.006, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.562, 0.1  , 0.001, 0.025, 0.001, 0.002, 0.001, 0.045, 0.002,
        0.002, 0.001, 0.033, 0.001, 0.001, 0.001, 0.001, 0.087, 0.006,
        0.001, 0.   , 0.   , 0.   , 0.   , 0.   , 0.001, 0.001, 0.001,
        0.   , 0.   , 0.   , 0.016, 0.026, 0.002, 0.001, 0.   , 0.001,
        0.002, 0.001, 0.001, 0.001, 0.02 , 0.008, 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.001, 0.   , 0.   , 0.   , 0.04 ],
       [0.014, 0.001, 0.   , 0.001, 0.   , 0.001, 0.001, 0.0

## 2. ram + variable

In [21]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_ram_'], bt_v['variable'])

In [22]:
for i in range(len(ram_var_matrix)):
    ram_var_matrix[i] = tem_matrix[i]

In [23]:
ram_var_matrix

array([[125.,   8.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.],
       [510.,  91.,   1.,  22.,   1.,   3.,   1.,  41.,   2.,   2.,   1.,
         28.,   1.,   1.,   1.,   1.,  71.,   6.,   1.,   0.,   1.,   0.,
          1.,   1.,   1.,   0.,   1.,   0.,   1.,   0.,  12.,  24.,   3.,
          1.,   1.,   1.,   2.,   2.,   0.,   2.,  13.,  20.,   0.,   0.,
          1.,   3.,   4.,   1.,   1.,   0.,   0.,   0.,   1.,   0.,   2.,
          0.,   0.,   1.,  55.],
       [ 29.,   1.,   0.,   1.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,
          1.,   0.,   0.,   0.,   0.,  10.,   8.,   0.,   1.,   0.,   1.,
          1.,   1.,   1.,   1.,   0.,   1.,   

In [24]:
sum = 0

for i in range(len(ram_var_matrix)):
    for j in range(len(ram_var_matrix[0])):
        sum = sum + ram_var_matrix[i][j]
    for k in range(len(ram_var_matrix[0])):
        po = ram_var_matrix[i][k] / sum
        ram_var_matrix[i][k] = po.round(3)
    sum = 0

In [25]:
ram_var_matrix

array([[0.926, 0.059, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.007, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.007, 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.542, 0.097, 0.001, 0.023, 0.001, 0.003, 0.001, 0.044, 0.002,
        0.002, 0.001, 0.03 , 0.001, 0.001, 0.001, 0.001, 0.075, 0.006,
        0.001, 0.   , 0.001, 0.   , 0.001, 0.001, 0.001, 0.   , 0.001,
        0.   , 0.001, 0.   , 0.013, 0.026, 0.003, 0.001, 0.001, 0.001,
        0.002, 0.002, 0.   , 0.002, 0.014, 0.021, 0.   , 0.   , 0.001,
        0.003, 0.004, 0.001, 0.001, 0.   , 0.   , 0.   , 0.001, 0.   ,
        0.002, 0.   , 0.   , 0.001, 0.058],
       [0.025, 0.001, 0.   , 0.001, 0.   , 0.   , 0.001, 0. 

## 3. total + variable

In [26]:
tem_matrix = confusion_matrix(bt_v['Perf_node01_power_energy_total_'], bt_v['variable'])

In [27]:
for i in range(len(total_var_matrix)):
    total_var_matrix[i] = tem_matrix[i]

In [28]:
total_var_matrix

array([[141.,  11.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.],
       [510.,  88.,   1.,  22.,   1.,   2.,   1.,  40.,   2.,   2.,   1.,
         29.,   1.,   1.,   1.,   1.,  78.,   4.,   1.,   0.,   0.,   0.,
          0.,   0.,   1.,   1.,   1.,   0.,   0.,   0.,  13.,  24.,   2.,
          1.,   0.,   1.,   2.,   1.,   1.,   1.,  17.,   6.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   2.,
          0.,   0.,   0.,  32.],
       [ 13.,   1.,   0.,   1.,   0.,   1.,   1.,   1.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   3.,  10.,   0.,   1.,   1.,   1.,
          2.,   2.,   1.,   0.,   0.,   1.,   

In [29]:
sum = 0

for i in range(len(total_var_matrix)):
    for j in range(len(total_var_matrix[0])):
        sum = sum + total_var_matrix[i][j]
    for k in range(len(total_var_matrix[0])):
        po = total_var_matrix[i][k] / sum
        total_var_matrix[i][k] = po.round(3)
    sum = 0

In [30]:
total_var_matrix

array([[0.922, 0.072, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.007, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.572, 0.099, 0.001, 0.025, 0.001, 0.002, 0.001, 0.045, 0.002,
        0.002, 0.001, 0.033, 0.001, 0.001, 0.001, 0.001, 0.087, 0.004,
        0.001, 0.   , 0.   , 0.   , 0.   , 0.   , 0.001, 0.001, 0.001,
        0.   , 0.   , 0.   , 0.015, 0.027, 0.002, 0.001, 0.   , 0.001,
        0.002, 0.001, 0.001, 0.001, 0.019, 0.007, 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.002, 0.   , 0.   , 0.   , 0.036],
       [0.011, 0.001, 0.   , 0.001, 0.   , 0.001, 0.001, 0.0