In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## pkg, ram, total의 전위 확률 구하기

In [2]:
bt = pd.read_csv("ep.csv")

In [3]:
bt

Application Perf_node01_task_clock Perf_node01_cpu_bus_cycles_  \
0            EP                   Down                          Up   
1            EP                   Down                          Up   
2            EP                     Up                          Up   
3            EP                     Up                          Up   
4            EP                     Up                          Up   
..          ...                    ...                         ...   
184          EP                     Up                       Same1   
185          EP                   Down                       Same1   
186          EP                     Up                          Up   
187          EP                     Up                        Down   
188         NaN                    NaN                         NaN   

    Perf_node01_cpu_cpu_cycles_ Perf_node01_msr_aperf_ Perf_node01_msr_mperf_  \
0                            Up                     Up                     Up   
1                            Up                     Up                     Up   
2                            Up                     Up                     Up   
3                            Up                     Up                     Up   
4                            Up                     Up                     Up   
..                          ...                    ...                    ...   
184                       Same1                   Down                   Down   
185                        Down                   Down                   Down   
186                          Up                     Up                     Up   
187                        Down                   Down                   Down   
188                         NaN                    NaN                    NaN   

    Perf_node01_msr_tsc_ Perf_node01_cpu_ref_cycles_  \
0                   Down                          Up   
1                  Same1                          Up   
2                  Same1                          Up   
3                     Up                          Up   
4                  Same1                          Up   
..                   ...                         ...   
184                Same1                        Down   
185                 Down                       Same1   
186                   Up                          Up   
187                   Up                        Down   
188                  NaN                         NaN   

    Perf_node01_power_energy_pkg_         a Perf_node01_power_energy_ram_  \
0                          Low_Up       NaN                      Low_Down   
1                          Low_Up    Low_Up                     High_Down   
2                          Low_Up    Low_Up                       High_Up   
3                          Low_Up    Low_Up                       High_Up   
4                          Low_Up    Low_Up                       High_Up   
..                            ...       ...                           ...   
184                      Low_Down  Low_Down                      Low_Down   
185                        Low_Up  Low_Down                       High_Up   
186                        Low_Up    Low_Up                      Low_Down   
187                      Low_Down    Low_Up                       High_Up   
188                           NaN  Low_Down                           NaN   

             b Perf_node01_power_energy_total_         c  
0          NaN                          Low_Up       NaN  
1     Low_Down                          Low_Up    Low_Up  
2    High_Down                          Low_Up    Low_Up  
3      High_Up                          Low_Up    Low_Up  
4      High_Up                         High_Up    Low_Up  
..         ...                             ...       ...  
184   Low_Down                        Low_Down  Low_Down  
185   Low_Down                          Low_Up  Low_Down  
186    High_Up                        Low_Down    Low_Up  
18

편한 비교를 위해 만듬

In [4]:
df = bt[['Perf_node01_power_energy_pkg_', 'a']]

In [5]:
ef = bt[['Perf_node01_power_energy_ram_', 'b']]

In [6]:
ff = bt[['Perf_node01_power_energy_total_', 'c']]

각 전력에 대한 전위확률 매트릭스 정의

In [7]:
pkg_matrix = np.zeros((5,5))
ram_matrix = np.zeros((5,5))
total_matrix = np.zeros((5,5))

# pkg 전위확률 계산

In [8]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "High_Up")].count()
print("High_Up to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "High_Up")].count()
print("High_Up to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "High_Up")].count()
print("High_Up to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "High_Up")].count()
print("High_Up to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "High_Up")].count()
print("High_Up to High_Down :\n",i, "\n")

High_Up to High_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Up to Low_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Up to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Up to Low_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Up to High_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 



In [9]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "Low_Up")].count()
print("Low_Up to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "Low_Up")].count()
print("Low_Up to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "Low_Up")].count()
print("Low_Up to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "Low_Up")].count()
print("Low_Up to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "Low_Up")].count()
print("Low_Up to High_Down :\n",i, "\n")

Low_Up to High_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Low_Up to Low_Up :
 Perf_node01_power_energy_pkg_    48
a                                48
dtype: int64 

Low_Up to Same2 :
 Perf_node01_power_energy_pkg_    2
a                                2
dtype: int64 

Low_Up to Low_Down :
 Perf_node01_power_energy_pkg_    53
a                                53
dtype: int64 

Low_Up to High_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 



In [10]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "Same2")].count()
print("Same2 to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "Same2")].count()
print("Same2 to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "Same2")].count()
print("Same2 to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "Same2")].count()
print("Same2 to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "Same2")].count()
print("Same2 to High_Down :\n",i, "\n")

Same2 to High_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Same2 to Low_Up :
 Perf_node01_power_energy_pkg_    3
a                                3
dtype: int64 

Same2 to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Same2 to Low_Down :
 Perf_node01_power_energy_pkg_    2
a                                2
dtype: int64 

Same2 to High_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 



In [11]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "Low_Down")].count()
print("Low_Down to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "Low_Down")].count()
print("Low_Down to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "Low_Down")].count()
print("Low_Down to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "Low_Down")].count()
print("Low_Down to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "Low_Down")].count()
print("Low_Down to High_Down :\n",i, "\n")

Low_Down to High_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Low_Down to Low_Up :
 Perf_node01_power_energy_pkg_    51
a                                51
dtype: int64 

Low_Down to Same2 :
 Perf_node01_power_energy_pkg_    3
a                                3
dtype: int64 

Low_Down to Low_Down :
 Perf_node01_power_energy_pkg_    25
a                                25
dtype: int64 

Low_Down to High_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 



In [12]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "High_Down")].count()
print("High_Down to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "High_Down")].count()
print("High_Down to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "High_Down")].count()
print("High_Down to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "High_Down")].count()
print("High_Down to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "High_Down")].count()
print("High_Down to High_Down :\n",i, "\n")

High_Down to High_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Down to Low_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Down to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Down to Low_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Down to High_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 



In [13]:
pkg_matrix[1] = [0, 48/103, 2/103, 53/103,0]
pkg_matrix[2] = [0, 3/5, 0, 2/5, 0]
pkg_matrix[3] = [0, 51/79, 3/79, 25/79, 0]

In [14]:
pkg_matrix

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.46601942, 0.01941748, 0.51456311, 0.        ],
       [0.        , 0.6       , 0.        , 0.4       , 0.        ],
       [0.        , 0.64556962, 0.03797468, 0.3164557 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [15]:
pkg_matrix = pkg_matrix.round(3)
pkg_matrix

array([[0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.466, 0.019, 0.515, 0.   ],
       [0.   , 0.6  , 0.   , 0.4  , 0.   ],
       [0.   , 0.646, 0.038, 0.316, 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   ]])

# ram 전위확률 계산

In [16]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "High_Up")].count()
print("High_Up to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "High_Up")].count()
print("High_Up to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "High_Up")].count()
print("High_Up to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "High_Up")].count()
print("High_Up to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "High_Up")].count()
print("High_Up to High_Down :\n",i, "\n")

High_Up to High_Up :
 Perf_node01_power_energy_ram_    3
b                                3
dtype: int64 

High_Up to Low_Up :
 Perf_node01_power_energy_ram_    5
b                                5
dtype: int64 

High_Up to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

High_Up to Low_Down :
 Perf_node01_power_energy_ram_    11
b                                11
dtype: int64 

High_Up to High_Down :
 Perf_node01_power_energy_ram_    6
b                                6
dtype: int64 



In [17]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "Low_Up")].count()
print("Low_Up to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "Low_Up")].count()
print("Low_Up to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "Low_Up")].count()
print("Low_Up to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "Low_Up")].count()
print("Low_Up to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "Low_Up")].count()
print("Low_Up to High_Down :\n",i, "\n")

Low_Up to High_Up :
 Perf_node01_power_energy_ram_    4
b                                4
dtype: int64 

Low_Up to Low_Up :
 Perf_node01_power_energy_ram_    22
b                                22
dtype: int64 

Low_Up to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Low_Up to Low_Down :
 Perf_node01_power_energy_ram_    31
b                                31
dtype: int64 

Low_Up to High_Down :
 Perf_node01_power_energy_ram_    9
b                                9
dtype: int64 



In [18]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "Same2")].count()
print("Same2 to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "Same2")].count()
print("Same2 to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "Same2")].count()
print("Same2 to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "Same2")].count()
print("Same2 to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "Same2")].count()
print("Same2 to High_Down :\n",i, "\n")

Same2 to High_Up :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Same2 to Low_Up :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Same2 to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Same2 to Low_Down :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Same2 to High_Down :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 



In [19]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "Low_Down")].count()
print("Low_Down to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "Low_Down")].count()
print("Low_Down to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "Low_Down")].count()
print("Low_Down to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "Low_Down")].count()
print("Low_Down to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "Low_Down")].count()
print("Low_Down to High_Down :\n",i, "\n")

Low_Down to High_Up :
 Perf_node01_power_energy_ram_    12
b                                12
dtype: int64 

Low_Down to Low_Up :
 Perf_node01_power_energy_ram_    31
b                                31
dtype: int64 

Low_Down to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Low_Down to Low_Down :
 Perf_node01_power_energy_ram_    20
b                                20
dtype: int64 

Low_Down to High_Down :
 Perf_node01_power_energy_ram_    7
b                                7
dtype: int64 



In [20]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "High_Down")].count()
print("High_Down to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "High_Down")].count()
print("High_Down to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "High_Down")].count()
print("High_Down to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "High_Down")].count()
print("High_Down to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "High_Down")].count()
print("High_Down to High_Down :\n",i, "\n")

High_Down to High_Up :
 Perf_node01_power_energy_ram_    7
b                                7
dtype: int64 

High_Down to Low_Up :
 Perf_node01_power_energy_ram_    8
b                                8
dtype: int64 

High_Down to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

High_Down to Low_Down :
 Perf_node01_power_energy_ram_    7
b                                7
dtype: int64 

High_Down to High_Down :
 Perf_node01_power_energy_ram_    4
b                                4
dtype: int64 



In [21]:
ram_matrix[0] = [3/25, 5/25, 0, 11/25, 6/25]
ram_matrix[1] = [4/66, 22/66, 0, 31/66, 9/66]
ram_matrix[3] = [12/70, 31/70, 0, 20/70, 7/70]
ram_matrix[4] = [7/26, 8/26, 0, 7/26, 4/26]

In [22]:
ram_matrix

array([[0.12      , 0.2       , 0.        , 0.44      , 0.24      ],
       [0.06060606, 0.33333333, 0.        , 0.46969697, 0.13636364],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.17142857, 0.44285714, 0.        , 0.28571429, 0.1       ],
       [0.26923077, 0.30769231, 0.        , 0.26923077, 0.15384615]])

In [23]:
ram_matrix = ram_matrix.round(3)
ram_matrix

array([[0.12 , 0.2  , 0.   , 0.44 , 0.24 ],
       [0.061, 0.333, 0.   , 0.47 , 0.136],
       [0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.171, 0.443, 0.   , 0.286, 0.1  ],
       [0.269, 0.308, 0.   , 0.269, 0.154]])

# total 전위확률 계산

In [24]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "High_Up")].count()
print("High_Up to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "High_Up")].count()
print("High_Up to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "High_Up")].count()
print("High_Up to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "High_Up")].count()
print("High_Up to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "High_Up")].count()
print("High_Up to High_Down :\n",i, "\n")

High_Up to High_Up :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Up to Low_Up :
 Perf_node01_power_energy_total_    1
c                                  1
dtype: int64 

High_Up to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Up to Low_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Up to High_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 



In [25]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "Low_Up")].count()
print("Low_Up to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "Low_Up")].count()
print("Low_Up to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "Low_Up")].count()
print("Low_Up to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "Low_Up")].count()
print("Low_Up to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "Low_Up")].count()
print("Low_Up to High_Down :\n",i, "\n")

Low_Up to High_Up :
 Perf_node01_power_energy_total_    1
c                                  1
dtype: int64 

Low_Up to Low_Up :
 Perf_node01_power_energy_total_    41
c                                  41
dtype: int64 

Low_Up to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Low_Up to Low_Down :
 Perf_node01_power_energy_total_    54
c                                  54
dtype: int64 

Low_Up to High_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 



In [26]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "Same2")].count()
print("Same2 to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "Same2")].count()
print("Same2 to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "Same2")].count()
print("Same2 to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "Same2")].count()
print("Same2 to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "Same2")].count()
print("Same2 to High_Down :\n",i, "\n")

Same2 to High_Up :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to Low_Up :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to Low_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to High_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 



In [27]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "Low_Down")].count()
print("Low_Down to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "Low_Down")].count()
print("Low_Down to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "Low_Down")].count()
print("Low_Down to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "Low_Down")].count()
print("Low_Down to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "Low_Down")].count()
print("Low_Down to High_Down :\n",i, "\n")

Low_Down to High_Up :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Low_Down to Low_Up :
 Perf_node01_power_energy_total_    53
c                                  53
dtype: int64 

Low_Down to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Low_Down to Low_Down :
 Perf_node01_power_energy_total_    37
c                                  37
dtype: int64 

Low_Down to High_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 



In [28]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "High_Down")].count()
print("High_Down to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "High_Down")].count()
print("High_Down to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "High_Down")].count()
print("High_Down to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "High_Down")].count()
print("High_Down to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "High_Down")].count()
print("High_Down to High_Down :\n",i, "\n")

High_Down to High_Up :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Down to Low_Up :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Down to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Down to Low_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Down to High_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 



In [29]:
total_matrix[0] = [0,1,0,0,0]
total_matrix[1] = [1/96, 41/96, 0, 54/96, 0]
total_matrix[3] = [0, 53/90, 0, 37/90, 0]

In [30]:
total_matrix

array([[0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.01041667, 0.42708333, 0.        , 0.5625    , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.58888889, 0.        , 0.41111111, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [31]:
total_matrix = total_matrix.round(3)
total_matrix

array([[0.   , 1.   , 0.   , 0.   , 0.   ],
       [0.01 , 0.427, 0.   , 0.562, 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.589, 0.   , 0.411, 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   ]])

# 결론

In [32]:
print(pkg_matrix)
print(ram_matrix)
print(total_matrix)

[[0.    0.    0.    0.    0.   ]
 [0.    0.466 0.019 0.515 0.   ]
 [0.    0.6   0.    0.4   0.   ]
 [0.    0.646 0.038 0.316 0.   ]
 [0.    0.    0.    0.    0.   ]]
[[0.12  0.2   0.    0.44  0.24 ]
 [0.061 0.333 0.    0.47  0.136]
 [0.    0.    0.    0.    0.   ]
 [0.171 0.443 0.    0.286 0.1  ]
 [0.269 0.308 0.    0.269 0.154]]
[[0.    1.    0.    0.    0.   ]
 [0.01  0.427 0.    0.562 0.   ]
 [0.    0.    0.    0.    0.   ]
 [0.    0.589 0.    0.411 0.   ]
 [0.    0.    0.    0.    0.   ]]
