In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## pkg, ram, total의 전위 확률 구하기

In [2]:
bt = pd.read_csv("mg.csv")

In [3]:
bt

Application Perf_node01_task_clock Perf_node01_cpu_bus_cycles_  \
0            MG                   Down                          Up   
1            MG                   Down                          Up   
2            MG                     Up                          Up   
3            MG                     Up                          Up   
4            MG                     Up                          Up   
..          ...                    ...                         ...   
174          MG                     Up                        Down   
175          MG                   Down                        Down   
176          MG                     Up                          Up   
177          MG                   Down                        Down   
178         NaN                    NaN                         NaN   

    Perf_node01_cpu_cpu_cycles_ Perf_node01_msr_aperf_ Perf_node01_msr_mperf_  \
0                            Up                     Up                     Up   
1                            Up                     Up                     Up   
2                            Up                     Up                     Up   
3                            Up                     Up                     Up   
4                            Up                     Up                     Up   
..                          ...                    ...                    ...   
174                       Same1                     Up                   Down   
175                        Down                   Down                   Down   
176                          Up                   Down                   Down   
177                        Down                   Down                   Down   
178                         NaN                    NaN                    NaN   

    Perf_node01_msr_tsc_ Perf_node01_cpu_ref_cycles_  \
0                   Down                          Up   
1                   Down                          Up   
2                     Up                          Up   
3                  Same1                          Up   
4                     Up                          Up   
..                   ...                         ...   
174                 Down                        Down   
175                   Up                          Up   
176                   Up                        Down   
177                 Down                        Down   
178                  NaN                         NaN   

    Perf_node01_power_energy_pkg_          a Perf_node01_power_energy_ram_  \
0                          Low_Up        NaN                        Low_Up   
1                          Low_Up     Low_Up                         Same2   
2                          Low_Up     Low_Up                      Low_Down   
3                          Low_Up     Low_Up                      Low_Down   
4                         High_Up     Low_Up                       High_Up   
..                            ...        ...                           ...   
174                      Low_Down     Low_Up                      Low_Down   
175                      Low_Down   Low_Down                      Low_Down   
176                      Low_Down   Low_Down                     High_Down   
177                     High_Down   Low_Down                     High_Down   
178                           NaN  High_Down                           NaN   

             b Perf_node01_power_energy_total_          c  
0          NaN                          Low_Up        NaN  
1       Low_Up                          Low_Up     Low_Up  
2        Same2                          Low_Up     Low_Up  
3     Low_Down                          Low_Up     Low_Up  
4     Low_Down                         High_Up     Low_Up  
..         ...                             ...        ...  
174   Low_Down                        Low_Down     Low_Up  
175   Low_Down                        Low_Down   Low_Down  
176   Low_Down                        Lo

편한 비교를 위해 만듬

In [4]:
df = bt[['Perf_node01_power_energy_pkg_', 'a']]

In [5]:
ef = bt[['Perf_node01_power_energy_ram_', 'b']]

In [6]:
ff = bt[['Perf_node01_power_energy_total_', 'c']]

각 전력에 대한 전위확률 매트릭스 정의

In [7]:
pkg_matrix = np.zeros((5,5))
ram_matrix = np.zeros((5,5))
total_matrix = np.zeros((5,5))

# pkg 전위확률 계산

In [8]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "High_Up")].count()
print("High_Up to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "High_Up")].count()
print("High_Up to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "High_Up")].count()
print("High_Up to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "High_Up")].count()
print("High_Up to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "High_Up")].count()
print("High_Up to High_Down :\n",i, "\n")

High_Up to High_Up :
 Perf_node01_power_energy_pkg_    2
a                                2
dtype: int64 

High_Up to Low_Up :
 Perf_node01_power_energy_pkg_    1
a                                1
dtype: int64 

High_Up to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Up to Low_Down :
 Perf_node01_power_energy_pkg_    2
a                                2
dtype: int64 

High_Up to High_Down :
 Perf_node01_power_energy_pkg_    1
a                                1
dtype: int64 



In [9]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "Low_Up")].count()
print("Low_Up to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "Low_Up")].count()
print("Low_Up to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "Low_Up")].count()
print("Low_Up to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "Low_Up")].count()
print("Low_Up to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "Low_Up")].count()
print("Low_Up to High_Down :\n",i, "\n")

Low_Up to High_Up :
 Perf_node01_power_energy_pkg_    1
a                                1
dtype: int64 

Low_Up to Low_Up :
 Perf_node01_power_energy_pkg_    52
a                                52
dtype: int64 

Low_Up to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Low_Up to Low_Down :
 Perf_node01_power_energy_pkg_    42
a                                42
dtype: int64 

Low_Up to High_Down :
 Perf_node01_power_energy_pkg_    2
a                                2
dtype: int64 



In [10]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "Same2")].count()
print("Same2 to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "Same2")].count()
print("Same2 to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "Same2")].count()
print("Same2 to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "Same2")].count()
print("Same2 to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "Same2")].count()
print("Same2 to High_Down :\n",i, "\n")

Same2 to High_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Same2 to Low_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Same2 to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Same2 to Low_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Same2 to High_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 



In [11]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "Low_Down")].count()
print("Low_Down to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "Low_Down")].count()
print("Low_Down to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "Low_Down")].count()
print("Low_Down to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "Low_Down")].count()
print("Low_Down to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "Low_Down")].count()
print("Low_Down to High_Down :\n",i, "\n")

Low_Down to High_Up :
 Perf_node01_power_energy_pkg_    2
a                                2
dtype: int64 

Low_Down to Low_Up :
 Perf_node01_power_energy_pkg_    41
a                                41
dtype: int64 

Low_Down to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Low_Down to Low_Down :
 Perf_node01_power_energy_pkg_    25
a                                25
dtype: int64 

Low_Down to High_Down :
 Perf_node01_power_energy_pkg_    2
a                                2
dtype: int64 



In [12]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "High_Down")].count()
print("High_Down to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "High_Down")].count()
print("High_Down to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "High_Down")].count()
print("High_Down to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "High_Down")].count()
print("High_Down to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "High_Down")].count()
print("High_Down to High_Down :\n",i, "\n")

High_Down to High_Up :
 Perf_node01_power_energy_pkg_    1
a                                1
dtype: int64 

High_Down to Low_Up :
 Perf_node01_power_energy_pkg_    2
a                                2
dtype: int64 

High_Down to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Down to Low_Down :
 Perf_node01_power_energy_pkg_    1
a                                1
dtype: int64 

High_Down to High_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 



In [13]:
pkg_matrix[0] = [2/6, 1/6, 0, 2/6, 1/6]
pkg_matrix[1] = [1/97, 52/97, 0, 42/97, 2/97]
pkg_matrix[3] = [2/70, 41/70, 0, 25/70, 2/70]
pkg_matrix[4] = [1/4, 2/4, 0, 1/4, 0]

In [14]:
pkg_matrix

array([[0.33333333, 0.16666667, 0.        , 0.33333333, 0.16666667],
       [0.01030928, 0.53608247, 0.        , 0.43298969, 0.02061856],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.02857143, 0.58571429, 0.        , 0.35714286, 0.02857143],
       [0.25      , 0.5       , 0.        , 0.25      , 0.        ]])

In [15]:
pkg_matrix = pkg_matrix.round(3)
pkg_matrix

array([[0.333, 0.167, 0.   , 0.333, 0.167],
       [0.01 , 0.536, 0.   , 0.433, 0.021],
       [0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.029, 0.586, 0.   , 0.357, 0.029],
       [0.25 , 0.5  , 0.   , 0.25 , 0.   ]])

# ram 전위확률 계산

In [16]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "High_Up")].count()
print("High_Up to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "High_Up")].count()
print("High_Up to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "High_Up")].count()
print("High_Up to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "High_Up")].count()
print("High_Up to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "High_Up")].count()
print("High_Up to High_Down :\n",i, "\n")

High_Up to High_Up :
 Perf_node01_power_energy_ram_    4
b                                4
dtype: int64 

High_Up to Low_Up :
 Perf_node01_power_energy_ram_    4
b                                4
dtype: int64 

High_Up to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

High_Up to Low_Down :
 Perf_node01_power_energy_ram_    6
b                                6
dtype: int64 

High_Up to High_Down :
 Perf_node01_power_energy_ram_    1
b                                1
dtype: int64 



In [17]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "Low_Up")].count()
print("Low_Up to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "Low_Up")].count()
print("Low_Up to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "Low_Up")].count()
print("Low_Up to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "Low_Up")].count()
print("Low_Up to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "Low_Up")].count()
print("Low_Up to High_Down :\n",i, "\n")

Low_Up to High_Up :
 Perf_node01_power_energy_ram_    3
b                                3
dtype: int64 

Low_Up to Low_Up :
 Perf_node01_power_energy_ram_    27
b                                27
dtype: int64 

Low_Up to Same2 :
 Perf_node01_power_energy_ram_    1
b                                1
dtype: int64 

Low_Up to Low_Down :
 Perf_node01_power_energy_ram_    38
b                                38
dtype: int64 

Low_Up to High_Down :
 Perf_node01_power_energy_ram_    3
b                                3
dtype: int64 



In [18]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "Same2")].count()
print("Same2 to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "Same2")].count()
print("Same2 to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "Same2")].count()
print("Same2 to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "Same2")].count()
print("Same2 to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "Same2")].count()
print("Same2 to High_Down :\n",i, "\n")

Same2 to High_Up :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Same2 to Low_Up :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Same2 to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Same2 to Low_Down :
 Perf_node01_power_energy_ram_    1
b                                1
dtype: int64 

Same2 to High_Down :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 



In [19]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "Low_Down")].count()
print("Low_Down to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "Low_Down")].count()
print("Low_Down to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "Low_Down")].count()
print("Low_Down to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "Low_Down")].count()
print("Low_Down to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "Low_Down")].count()
print("Low_Down to High_Down :\n",i, "\n")

Low_Down to High_Up :
 Perf_node01_power_energy_ram_    6
b                                6
dtype: int64 

Low_Down to Low_Up :
 Perf_node01_power_energy_ram_    37
b                                37
dtype: int64 

Low_Down to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Low_Down to Low_Down :
 Perf_node01_power_energy_ram_    35
b                                35
dtype: int64 

Low_Down to High_Down :
 Perf_node01_power_energy_ram_    3
b                                3
dtype: int64 



In [20]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "High_Down")].count()
print("High_Down to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "High_Down")].count()
print("High_Down to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "High_Down")].count()
print("High_Down to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "High_Down")].count()
print("High_Down to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "High_Down")].count()
print("High_Down to High_Down :\n",i, "\n")

High_Down to High_Up :
 Perf_node01_power_energy_ram_    2
b                                2
dtype: int64 

High_Down to Low_Up :
 Perf_node01_power_energy_ram_    3
b                                3
dtype: int64 

High_Down to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

High_Down to Low_Down :
 Perf_node01_power_energy_ram_    1
b                                1
dtype: int64 

High_Down to High_Down :
 Perf_node01_power_energy_ram_    2
b                                2
dtype: int64 



In [21]:
ram_matrix[0] = [4/15, 4/15, 0, 6/15, 1/15]
ram_matrix[1] = [3/72, 27/72, 1/72, 38/72, 3/72]
ram_matrix[2] = [0,0,0,1,0]
ram_matrix[3] = [6/81, 37/81, 0, 35/81, 3/81]
ram_matrix[4] = [2/8, 3/8, 0, 1/8, 2/8]

In [22]:
ram_matrix

array([[0.26666667, 0.26666667, 0.        , 0.4       , 0.06666667],
       [0.04166667, 0.375     , 0.01388889, 0.52777778, 0.04166667],
       [0.        , 0.        , 0.        , 1.        , 0.        ],
       [0.07407407, 0.45679012, 0.        , 0.43209877, 0.03703704],
       [0.25      , 0.375     , 0.        , 0.125     , 0.25      ]])

In [23]:
ram_matrix = ram_matrix.round(3)
ram_matrix

array([[0.267, 0.267, 0.   , 0.4  , 0.067],
       [0.042, 0.375, 0.014, 0.528, 0.042],
       [0.   , 0.   , 0.   , 1.   , 0.   ],
       [0.074, 0.457, 0.   , 0.432, 0.037],
       [0.25 , 0.375, 0.   , 0.125, 0.25 ]])

# total 전위확률 계산

In [24]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "High_Up")].count()
print("High_Up to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "High_Up")].count()
print("High_Up to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "High_Up")].count()
print("High_Up to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "High_Up")].count()
print("High_Up to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "High_Up")].count()
print("High_Up to High_Down :\n",i, "\n")

High_Up to High_Up :
 Perf_node01_power_energy_total_    2
c                                  2
dtype: int64 

High_Up to Low_Up :
 Perf_node01_power_energy_total_    2
c                                  2
dtype: int64 

High_Up to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Up to Low_Down :
 Perf_node01_power_energy_total_    1
c                                  1
dtype: int64 

High_Up to High_Down :
 Perf_node01_power_energy_total_    1
c                                  1
dtype: int64 



In [25]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "Low_Up")].count()
print("Low_Up to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "Low_Up")].count()
print("Low_Up to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "Low_Up")].count()
print("Low_Up to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "Low_Up")].count()
print("Low_Up to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "Low_Up")].count()
print("Low_Up to High_Down :\n",i, "\n")

Low_Up to High_Up :
 Perf_node01_power_energy_total_    2
c                                  2
dtype: int64 

Low_Up to Low_Up :
 Perf_node01_power_energy_total_    51
c                                  51
dtype: int64 

Low_Up to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Low_Up to Low_Down :
 Perf_node01_power_energy_total_    42
c                                  42
dtype: int64 

Low_Up to High_Down :
 Perf_node01_power_energy_total_    1
c                                  1
dtype: int64 



In [26]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "Same2")].count()
print("Same2 to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "Same2")].count()
print("Same2 to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "Same2")].count()
print("Same2 to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "Same2")].count()
print("Same2 to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "Same2")].count()
print("Same2 to High_Down :\n",i, "\n")

Same2 to High_Up :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to Low_Up :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to Low_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to High_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 



In [27]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "Low_Down")].count()
print("Low_Down to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "Low_Down")].count()
print("Low_Down to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "Low_Down")].count()
print("Low_Down to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "Low_Down")].count()
print("Low_Down to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "Low_Down")].count()
print("Low_Down to High_Down :\n",i, "\n")

Low_Down to High_Up :
 Perf_node01_power_energy_total_    1
c                                  1
dtype: int64 

Low_Down to Low_Up :
 Perf_node01_power_energy_total_    41
c                                  41
dtype: int64 

Low_Down to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Low_Down to Low_Down :
 Perf_node01_power_energy_total_    28
c                                  28
dtype: int64 

Low_Down to High_Down :
 Perf_node01_power_energy_total_    2
c                                  2
dtype: int64 



In [28]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "High_Down")].count()
print("High_Down to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "High_Down")].count()
print("High_Down to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "High_Down")].count()
print("High_Down to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "High_Down")].count()
print("High_Down to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "High_Down")].count()
print("High_Down to High_Down :\n",i, "\n")

High_Down to High_Up :
 Perf_node01_power_energy_total_    1
c                                  1
dtype: int64 

High_Down to Low_Up :
 Perf_node01_power_energy_total_    1
c                                  1
dtype: int64 

High_Down to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Down to Low_Down :
 Perf_node01_power_energy_total_    1
c                                  1
dtype: int64 

High_Down to High_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 



In [29]:
total_matrix[0] = [2/6, 2/6, 0, 1/6, 1/6]
total_matrix[1] = [2/96, 51/96, 0, 42/96, 1/96]
total_matrix[3] = [1/72, 41/72, 0, 28/72, 2/72]
total_matrix[4] = [1/3, 1/3, 0, 1/3, 0]

In [30]:
total_matrix

array([[0.33333333, 0.33333333, 0.        , 0.16666667, 0.16666667],
       [0.02083333, 0.53125   , 0.        , 0.4375    , 0.01041667],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.01388889, 0.56944444, 0.        , 0.38888889, 0.02777778],
       [0.33333333, 0.33333333, 0.        , 0.33333333, 0.        ]])

In [31]:
total_matrix = total_matrix.round(3)
total_matrix

array([[0.333, 0.333, 0.   , 0.167, 0.167],
       [0.021, 0.531, 0.   , 0.438, 0.01 ],
       [0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.014, 0.569, 0.   , 0.389, 0.028],
       [0.333, 0.333, 0.   , 0.333, 0.   ]])

# 결론

In [32]:
print(pkg_matrix)
print(ram_matrix)
print(total_matrix)

[[0.333 0.167 0.    0.333 0.167]
 [0.01  0.536 0.    0.433 0.021]
 [0.    0.    0.    0.    0.   ]
 [0.029 0.586 0.    0.357 0.029]
 [0.25  0.5   0.    0.25  0.   ]]
[[0.267 0.267 0.    0.4   0.067]
 [0.042 0.375 0.014 0.528 0.042]
 [0.    0.    0.    1.    0.   ]
 [0.074 0.457 0.    0.432 0.037]
 [0.25  0.375 0.    0.125 0.25 ]]
[[0.333 0.333 0.    0.167 0.167]
 [0.021 0.531 0.    0.438 0.01 ]
 [0.    0.    0.    0.    0.   ]
 [0.014 0.569 0.    0.389 0.028]
 [0.333 0.333 0.    0.333 0.   ]]
