In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## pkg, ram, total의 전위 확률 구하기

In [2]:
bt = pd.read_csv("lu.csv")

In [3]:
bt

Application Perf_node01_task_clock Perf_node01_cpu_bus_cycles_  \
0             LU                   Down                          Up   
1             LU                   Down                          Up   
2             LU                     Up                          Up   
3             LU                     Up                          Up   
4             LU                   Down                        Down   
...          ...                    ...                         ...   
1104          LU                   Down                        Down   
1105          LU                     Up                          Up   
1106          LU                     Up                        Down   
1107          LU                   Down                        Down   
1108         NaN                    NaN                         NaN   

     Perf_node01_cpu_cpu_cycles_ Perf_node01_msr_aperf_  \
0                             Up                     Up   
1                             Up                     Up   
2                             Up                     Up   
3                             Up                     Up   
4                           Down                   Down   
...                          ...                    ...   
1104                        Down                   Down   
1105                          Up                     Up   
1106                        Down                   Down   
1107                        Down                   Down   
1108                         NaN                    NaN   

     Perf_node01_msr_mperf_ Perf_node01_msr_tsc_ Perf_node01_cpu_ref_cycles_  \
0                        Up                 Down                          Up   
1                        Up                 Down                          Up   
2                        Up                   Up                          Up   
3                        Up                   Up                          Up   
4                      Down                 Down                        Down   
...                     ...                  ...                         ...   
1104                   Down                Same1                        Down   
1105                     Up                   Up                          Up   
1106                   Down                   Up                        Down   
1107                   Down                 Down                        Down   
1108                    NaN                  NaN                         NaN   

     Perf_node01_power_energy_pkg_          a Perf_node01_power_energy_ram_  \
0                           Low_Up        NaN                      Low_Down   
1                           Low_Up     Low_Up                        Low_Up   
2                           Low_Up     Low_Up                       High_Up   
3                          High_Up     Low_Up                       High_Up   
4                        High_Down    High_Up                     High_Down   
...                            ...        ...                           ...   
1104                        Low_Up   Low_Down                     High_Down   
1105                      Low_Down     Low_Up                       High_Up   
1106                     High_Down   Low_Down                     High_Down   
1107                      Low_Down  High_Down                     High_Down   
1108                           NaN   Low_Down                           NaN   

              b Perf_node01_power_energy_total_          c  
0           NaN                          Low_Up        NaN  
1      Low_Down                          Low_Up     Low_Up  
2        Low_Up                          Low_Up     Low_Up  
3       High_Up                         High_Up     Low_Up  
4       High_Up                       High_Down    High_Up  
...         ...                             ...        ...  
1104    High_Up                        Low_Down     Low_Up  
1105  High_Down                          Low_

편한 비교를 위해 만듬

In [4]:
df = bt[['Perf_node01_power_energy_pkg_', 'a']]

In [5]:
ef = bt[['Perf_node01_power_energy_ram_', 'b']]

In [6]:
ff = bt[['Perf_node01_power_energy_total_', 'c']]

각 전력에 대한 전위확률 매트릭스 정의

In [7]:
pkg_matrix = np.zeros((5,5))
ram_matrix = np.zeros((5,5))
total_matrix = np.zeros((5,5))

# pkg 전위확률 계산

In [8]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "High_Up")].count()
print("High_Up to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "High_Up")].count()
print("High_Up to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "High_Up")].count()
print("High_Up to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "High_Up")].count()
print("High_Up to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "High_Up")].count()
print("High_Up to High_Down :\n",i, "\n")

High_Up to High_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Up to Low_Up :
 Perf_node01_power_energy_pkg_    2
a                                2
dtype: int64 

High_Up to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Up to Low_Down :
 Perf_node01_power_energy_pkg_    25
a                                25
dtype: int64 

High_Up to High_Down :
 Perf_node01_power_energy_pkg_    361
a                                361
dtype: int64 



In [9]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "Low_Up")].count()
print("Low_Up to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "Low_Up")].count()
print("Low_Up to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "Low_Up")].count()
print("Low_Up to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "Low_Up")].count()
print("Low_Up to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "Low_Up")].count()
print("Low_Up to High_Down :\n",i, "\n")

Low_Up to High_Up :
 Perf_node01_power_energy_pkg_    3
a                                3
dtype: int64 

Low_Up to Low_Up :
 Perf_node01_power_energy_pkg_    17
a                                17
dtype: int64 

Low_Up to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Low_Up to Low_Down :
 Perf_node01_power_energy_pkg_    102
a                                102
dtype: int64 

Low_Up to High_Down :
 Perf_node01_power_energy_pkg_    4
a                                4
dtype: int64 



In [10]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "Same2")].count()
print("Same2 to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "Same2")].count()
print("Same2 to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "Same2")].count()
print("Same2 to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "Same2")].count()
print("Same2 to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "Same2")].count()
print("Same2 to High_Down :\n",i, "\n")

Same2 to High_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Same2 to Low_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Same2 to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Same2 to Low_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Same2 to High_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 



In [11]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "Low_Down")].count()
print("Low_Down to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "Low_Down")].count()
print("Low_Down to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "Low_Down")].count()
print("Low_Down to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "Low_Down")].count()
print("Low_Down to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "Low_Down")].count()
print("Low_Down to High_Down :\n",i, "\n")

Low_Down to High_Up :
 Perf_node01_power_energy_pkg_    121
a                                121
dtype: int64 

Low_Down to Low_Up :
 Perf_node01_power_energy_pkg_    47
a                                47
dtype: int64 

Low_Down to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Low_Down to Low_Down :
 Perf_node01_power_energy_pkg_    55
a                                55
dtype: int64 

Low_Down to High_Down :
 Perf_node01_power_energy_pkg_    2
a                                2
dtype: int64 



In [12]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "High_Down")].count()
print("High_Down to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "High_Down")].count()
print("High_Down to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "High_Down")].count()
print("High_Down to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "High_Down")].count()
print("High_Down to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "High_Down")].count()
print("High_Down to High_Down :\n",i, "\n")

High_Down to High_Up :
 Perf_node01_power_energy_pkg_    264
a                                264
dtype: int64 

High_Down to Low_Up :
 Perf_node01_power_energy_pkg_    59
a                                59
dtype: int64 

High_Down to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Down to Low_Down :
 Perf_node01_power_energy_pkg_    44
a                                44
dtype: int64 

High_Down to High_Down :
 Perf_node01_power_energy_pkg_    1
a                                1
dtype: int64 



In [13]:
pkg_matrix[0] = [0, 2/388, 0, 25/388, 361/388]
pkg_matrix[1] = [3/126, 17/126, 0, 102/126, 4/126]
pkg_matrix[3] = [121/225, 47/225, 0, 55/225, 2/225]
pkg_matrix[4] = [264/368, 59/368, 0, 44/368, 1/368]

In [14]:
pkg_matrix

array([[0.        , 0.00515464, 0.        , 0.06443299, 0.93041237],
       [0.02380952, 0.13492063, 0.        , 0.80952381, 0.03174603],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.53777778, 0.20888889, 0.        , 0.24444444, 0.00888889],
       [0.7173913 , 0.16032609, 0.        , 0.11956522, 0.00271739]])

In [15]:
pkg_matrix = pkg_matrix.round(3)
pkg_matrix

array([[0.   , 0.005, 0.   , 0.064, 0.93 ],
       [0.024, 0.135, 0.   , 0.81 , 0.032],
       [0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.538, 0.209, 0.   , 0.244, 0.009],
       [0.717, 0.16 , 0.   , 0.12 , 0.003]])

# ram 전위확률 계산

In [16]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "High_Up")].count()
print("High_Up to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "High_Up")].count()
print("High_Up to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "High_Up")].count()
print("High_Up to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "High_Up")].count()
print("High_Up to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "High_Up")].count()
print("High_Up to High_Down :\n",i, "\n")

High_Up to High_Up :
 Perf_node01_power_energy_ram_    17
b                                17
dtype: int64 

High_Up to Low_Up :
 Perf_node01_power_energy_ram_    27
b                                27
dtype: int64 

High_Up to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

High_Up to Low_Down :
 Perf_node01_power_energy_ram_    64
b                                64
dtype: int64 

High_Up to High_Down :
 Perf_node01_power_energy_ram_    328
b                                328
dtype: int64 



In [17]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "Low_Up")].count()
print("Low_Up to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "Low_Up")].count()
print("Low_Up to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "Low_Up")].count()
print("Low_Up to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "Low_Up")].count()
print("Low_Up to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "Low_Up")].count()
print("Low_Up to High_Down :\n",i, "\n")

Low_Up to High_Up :
 Perf_node01_power_energy_ram_    27
b                                27
dtype: int64 

Low_Up to Low_Up :
 Perf_node01_power_energy_ram_    26
b                                26
dtype: int64 

Low_Up to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Low_Up to Low_Down :
 Perf_node01_power_energy_ram_    25
b                                25
dtype: int64 

Low_Up to High_Down :
 Perf_node01_power_energy_ram_    52
b                                52
dtype: int64 



In [18]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "Same2")].count()
print("Same2 to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "Same2")].count()
print("Same2 to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "Same2")].count()
print("Same2 to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "Same2")].count()
print("Same2 to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "Same2")].count()
print("Same2 to High_Down :\n",i, "\n")

Same2 to High_Up :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Same2 to Low_Up :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Same2 to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Same2 to Low_Down :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Same2 to High_Down :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 



In [19]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "Low_Down")].count()
print("Low_Down to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "Low_Down")].count()
print("Low_Down to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "Low_Down")].count()
print("Low_Down to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "Low_Down")].count()
print("Low_Down to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "Low_Down")].count()
print("Low_Down to High_Down :\n",i, "\n")

Low_Down to High_Up :
 Perf_node01_power_energy_ram_    45
b                                45
dtype: int64 

Low_Down to Low_Up :
 Perf_node01_power_energy_ram_    38
b                                38
dtype: int64 

Low_Down to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Low_Down to Low_Down :
 Perf_node01_power_energy_ram_    24
b                                24
dtype: int64 

Low_Down to High_Down :
 Perf_node01_power_energy_ram_    25
b                                25
dtype: int64 



In [20]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "High_Down")].count()
print("High_Down to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "High_Down")].count()
print("High_Down to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "High_Down")].count()
print("High_Down to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "High_Down")].count()
print("High_Down to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "High_Down")].count()
print("High_Down to High_Down :\n",i, "\n")

High_Down to High_Up :
 Perf_node01_power_energy_ram_    347
b                                347
dtype: int64 

High_Down to Low_Up :
 Perf_node01_power_energy_ram_    39
b                                39
dtype: int64 

High_Down to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

High_Down to Low_Down :
 Perf_node01_power_energy_ram_    18
b                                18
dtype: int64 

High_Down to High_Down :
 Perf_node01_power_energy_ram_    5
b                                5
dtype: int64 



In [21]:
ram_matrix[0] = [17/436, 27/436, 0, 64/436, 328/436]
ram_matrix[1] = [27/130, 26/130, 0, 25/130, 52/130]
ram_matrix[3] = [45/132, 38/132, 0, 24/132, 25/132]
ram_matrix[4] = [347/409, 39/409, 0, 18/409, 5/409]

In [22]:
ram_matrix

array([[0.03899083, 0.06192661, 0.        , 0.14678899, 0.75229358],
       [0.20769231, 0.2       , 0.        , 0.19230769, 0.4       ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.34090909, 0.28787879, 0.        , 0.18181818, 0.18939394],
       [0.84841076, 0.09535452, 0.        , 0.04400978, 0.01222494]])

In [23]:
ram_matrix = ram_matrix.round(3)
ram_matrix

array([[0.039, 0.062, 0.   , 0.147, 0.752],
       [0.208, 0.2  , 0.   , 0.192, 0.4  ],
       [0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.341, 0.288, 0.   , 0.182, 0.189],
       [0.848, 0.095, 0.   , 0.044, 0.012]])

# total 전위확률 계산

In [24]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "High_Up")].count()
print("High_Up to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "High_Up")].count()
print("High_Up to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "High_Up")].count()
print("High_Up to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "High_Up")].count()
print("High_Up to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "High_Up")].count()
print("High_Up to High_Down :\n",i, "\n")

High_Up to High_Up :
 Perf_node01_power_energy_total_    1
c                                  1
dtype: int64 

High_Up to Low_Up :
 Perf_node01_power_energy_total_    2
c                                  2
dtype: int64 

High_Up to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Up to Low_Down :
 Perf_node01_power_energy_total_    43
c                                  43
dtype: int64 

High_Up to High_Down :
 Perf_node01_power_energy_total_    321
c                                  321
dtype: int64 



In [25]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "Low_Up")].count()
print("Low_Up to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "Low_Up")].count()
print("Low_Up to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "Low_Up")].count()
print("Low_Up to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "Low_Up")].count()
print("Low_Up to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "Low_Up")].count()
print("Low_Up to High_Down :\n",i, "\n")

Low_Up to High_Up :
 Perf_node01_power_energy_total_    9
c                                  9
dtype: int64 

Low_Up to Low_Up :
 Perf_node01_power_energy_total_    32
c                                  32
dtype: int64 

Low_Up to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Low_Up to Low_Down :
 Perf_node01_power_energy_total_    114
c                                  114
dtype: int64 

Low_Up to High_Down :
 Perf_node01_power_energy_total_    13
c                                  13
dtype: int64 



In [26]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "Same2")].count()
print("Same2 to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "Same2")].count()
print("Same2 to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "Same2")].count()
print("Same2 to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "Same2")].count()
print("Same2 to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "Same2")].count()
print("Same2 to High_Down :\n",i, "\n")

Same2 to High_Up :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to Low_Up :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to Low_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to High_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 



In [27]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "Low_Down")].count()
print("Low_Down to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "Low_Down")].count()
print("Low_Down to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "Low_Down")].count()
print("Low_Down to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "Low_Down")].count()
print("Low_Down to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "Low_Down")].count()
print("Low_Down to High_Down :\n",i, "\n")

Low_Down to High_Up :
 Perf_node01_power_energy_total_    133
c                                  133
dtype: int64 

Low_Down to Low_Up :
 Perf_node01_power_energy_total_    58
c                                  58
dtype: int64 

Low_Down to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Low_Down to Low_Down :
 Perf_node01_power_energy_total_    46
c                                  46
dtype: int64 

Low_Down to High_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 



In [28]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "High_Down")].count()
print("High_Down to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "High_Down")].count()
print("High_Down to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "High_Down")].count()
print("High_Down to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "High_Down")].count()
print("High_Down to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "High_Down")].count()
print("High_Down to High_Down :\n",i, "\n")

High_Down to High_Up :
 Perf_node01_power_energy_total_    224
c                                  224
dtype: int64 

High_Down to Low_Up :
 Perf_node01_power_energy_total_    75
c                                  75
dtype: int64 

High_Down to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Down to Low_Down :
 Perf_node01_power_energy_total_    35
c                                  35
dtype: int64 

High_Down to High_Down :
 Perf_node01_power_energy_total_    1
c                                  1
dtype: int64 



In [29]:
total_matrix[0] = [1/367, 2/367, 0, 43/367, 321/367]
total_matrix[1] = [9/168, 32/168, 0, 114/168, 13/168]
total_matrix[3] = [133/237, 58/237, 0, 46/237, 0]
total_matrix[4] = [224/335, 75/335, 0, 35/335, 1/335]

In [30]:
total_matrix

array([[0.0027248 , 0.00544959, 0.        , 0.11716621, 0.8746594 ],
       [0.05357143, 0.19047619, 0.        , 0.67857143, 0.07738095],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.56118143, 0.24472574, 0.        , 0.19409283, 0.        ],
       [0.66865672, 0.2238806 , 0.        , 0.10447761, 0.00298507]])

In [31]:
total_matrix = total_matrix.round(3)
total_matrix

array([[0.003, 0.005, 0.   , 0.117, 0.875],
       [0.054, 0.19 , 0.   , 0.679, 0.077],
       [0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.561, 0.245, 0.   , 0.194, 0.   ],
       [0.669, 0.224, 0.   , 0.104, 0.003]])

# 결론

In [32]:
print(pkg_matrix)
print(ram_matrix)
print(total_matrix)

[[0.    0.005 0.    0.064 0.93 ]
 [0.024 0.135 0.    0.81  0.032]
 [0.    0.    0.    0.    0.   ]
 [0.538 0.209 0.    0.244 0.009]
 [0.717 0.16  0.    0.12  0.003]]
[[0.039 0.062 0.    0.147 0.752]
 [0.208 0.2   0.    0.192 0.4  ]
 [0.    0.    0.    0.    0.   ]
 [0.341 0.288 0.    0.182 0.189]
 [0.848 0.095 0.    0.044 0.012]]
[[0.003 0.005 0.    0.117 0.875]
 [0.054 0.19  0.    0.679 0.077]
 [0.    0.    0.    0.    0.   ]
 [0.561 0.245 0.    0.194 0.   ]
 [0.669 0.224 0.    0.104 0.003]]
