In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## pkg, ram, total의 전위 확률 구하기

In [2]:
bt = pd.read_csv("is.csv")

In [3]:
bt

Application Perf_node01_task_clock Perf_node01_cpu_bus_cycles_  \
0           IS                   Down                          Up   
1           IS                     Up                          Up   
2           IS                     Up                          Up   
3           IS                     Up                          Up   
4           IS                   Down                          Up   
..         ...                    ...                         ...   
66          IS                   Down                        Down   
67          IS                   Down                        Down   
68          IS                     Up                        Down   
69          IS                   Down                        Down   
70         NaN                    NaN                         NaN   

   Perf_node01_cpu_cpu_cycles_ Perf_node01_msr_aperf_ Perf_node01_msr_mperf_  \
0                           Up                     Up                     Up   
1                           Up                     Up                     Up   
2                           Up                     Up                     Up   
3                           Up                     Up                     Up   
4                           Up                     Up                     Up   
..                         ...                    ...                    ...   
66                        Down                   Down                   Down   
67                        Down                   Down                   Down   
68                        Down                   Down                   Down   
69                        Down                   Down                   Down   
70                         NaN                    NaN                    NaN   

   Perf_node01_msr_tsc_ Perf_node01_cpu_ref_cycles_  \
0                  Down                          Up   
1                 Same1                          Up   
2                    Up                          Up   
3                    Up                          Up   
4                  Down                          Up   
..                  ...                         ...   
66                 Down                        Down   
67                 Down                        Down   
68                   Up                        Down   
69                 Down                        Down   
70                  NaN                         NaN   

   Perf_node01_power_energy_pkg_          a Perf_node01_power_energy_ram_  \
0                         Low_Up        NaN                        Low_Up   
1                         Low_Up     Low_Up                      Low_Down   
2                         Low_Up     Low_Up                      Low_Down   
3                         Low_Up     Low_Up                       High_Up   
4                         Low_Up     Low_Up                      Low_Down   
..                           ...        ...                           ...   
66                      Low_Down     Low_Up                        Low_Up   
67                      Low_Down   Low_Down                      Low_Down   
68                     High_Down   Low_Down                     High_Down   
69                        Low_Up  High_Down                     High_Down   
70                           NaN     Low_Up                           NaN   

            b Perf_node01_power_energy_total_          c  
0         NaN                          Low_Up        NaN  
1      Low_Up                          Low_Up     Low_Up  
2    Low_Down                          Low_Up     Low_Up  
3    Low_Down                          Low_Up     Low_Up  
4     High_Up                          Low_Up     Low_Up  
..        ...                             ...        ...  
66   Low_Down                        Low_Down   Low_Down  
67     Low_Up                        Low_Down   Low_Down  
68   Low_Down                       High_Down   Low_Down  
69  High_Down                        

편한 비교를 위해 만듬

In [4]:
df = bt[['Perf_node01_power_energy_pkg_', 'a']]

In [5]:
ef = bt[['Perf_node01_power_energy_ram_', 'b']]

In [6]:
ff = bt[['Perf_node01_power_energy_total_', 'c']]

각 전력에 대한 전위확률 매트릭스 정의

In [7]:
pkg_matrix = np.zeros((5,5))
ram_matrix = np.zeros((5,5))
total_matrix = np.zeros((5,5))

# pkg 전위확률 계산

In [8]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "High_Up")].count()
print("High_Up to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "High_Up")].count()
print("High_Up to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "High_Up")].count()
print("High_Up to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "High_Up")].count()
print("High_Up to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "High_Up")].count()
print("High_Up to High_Down :\n",i, "\n")

High_Up to High_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Up to Low_Up :
 Perf_node01_power_energy_pkg_    2
a                                2
dtype: int64 

High_Up to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Up to Low_Down :
 Perf_node01_power_energy_pkg_    3
a                                3
dtype: int64 

High_Up to High_Down :
 Perf_node01_power_energy_pkg_    3
a                                3
dtype: int64 



In [9]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "Low_Up")].count()
print("Low_Up to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "Low_Up")].count()
print("Low_Up to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "Low_Up")].count()
print("Low_Up to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "Low_Up")].count()
print("Low_Up to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "Low_Up")].count()
print("Low_Up to High_Down :\n",i, "\n")

Low_Up to High_Up :
 Perf_node01_power_energy_pkg_    2
a                                2
dtype: int64 

Low_Up to Low_Up :
 Perf_node01_power_energy_pkg_    8
a                                8
dtype: int64 

Low_Up to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Low_Up to Low_Down :
 Perf_node01_power_energy_pkg_    18
a                                18
dtype: int64 

Low_Up to High_Down :
 Perf_node01_power_energy_pkg_    2
a                                2
dtype: int64 



In [10]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "Same2")].count()
print("Same2 to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "Same2")].count()
print("Same2 to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "Same2")].count()
print("Same2 to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "Same2")].count()
print("Same2 to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "Same2")].count()
print("Same2 to High_Down :\n",i, "\n")

Same2 to High_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Same2 to Low_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Same2 to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Same2 to Low_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Same2 to High_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 



In [11]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "Low_Down")].count()
print("Low_Down to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "Low_Down")].count()
print("Low_Down to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "Low_Down")].count()
print("Low_Down to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "Low_Down")].count()
print("Low_Down to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "Low_Down")].count()
print("Low_Down to High_Down :\n",i, "\n")

Low_Down to High_Up :
 Perf_node01_power_energy_pkg_    1
a                                1
dtype: int64 

Low_Down to Low_Up :
 Perf_node01_power_energy_pkg_    18
a                                18
dtype: int64 

Low_Down to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Low_Down to Low_Down :
 Perf_node01_power_energy_pkg_    1
a                                1
dtype: int64 

Low_Down to High_Down :
 Perf_node01_power_energy_pkg_    3
a                                3
dtype: int64 



In [12]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "High_Down")].count()
print("High_Down to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "High_Down")].count()
print("High_Down to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "High_Down")].count()
print("High_Down to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "High_Down")].count()
print("High_Down to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "High_Down")].count()
print("High_Down to High_Down :\n",i, "\n")

High_Down to High_Up :
 Perf_node01_power_energy_pkg_    5
a                                5
dtype: int64 

High_Down to Low_Up :
 Perf_node01_power_energy_pkg_    2
a                                2
dtype: int64 

High_Down to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Down to Low_Down :
 Perf_node01_power_energy_pkg_    1
a                                1
dtype: int64 

High_Down to High_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 



In [13]:
pkg_matrix[0] = [0, 2/8, 0, 3/8, 3/8]
pkg_matrix[1] = [2/30, 8/30, 0, 18/30, 2/30]
pkg_matrix[3] = [1/23, 18/23, 0, 1/23, 3/23]
pkg_matrix[4] = [5/8, 2/8, 0, 1/8, 0]

In [14]:
pkg_matrix

array([[0.        , 0.25      , 0.        , 0.375     , 0.375     ],
       [0.06666667, 0.26666667, 0.        , 0.6       , 0.06666667],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.04347826, 0.7826087 , 0.        , 0.04347826, 0.13043478],
       [0.625     , 0.25      , 0.        , 0.125     , 0.        ]])

In [15]:
pkg_matrix = pkg_matrix.round(3)
pkg_matrix

array([[0.   , 0.25 , 0.   , 0.375, 0.375],
       [0.067, 0.267, 0.   , 0.6  , 0.067],
       [0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.043, 0.783, 0.   , 0.043, 0.13 ],
       [0.625, 0.25 , 0.   , 0.125, 0.   ]])

# ram 전위확률 계산

In [16]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "High_Up")].count()
print("High_Up to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "High_Up")].count()
print("High_Up to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "High_Up")].count()
print("High_Up to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "High_Up")].count()
print("High_Up to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "High_Up")].count()
print("High_Up to High_Down :\n",i, "\n")

High_Up to High_Up :
 Perf_node01_power_energy_ram_    3
b                                3
dtype: int64 

High_Up to Low_Up :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

High_Up to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

High_Up to Low_Down :
 Perf_node01_power_energy_ram_    4
b                                4
dtype: int64 

High_Up to High_Down :
 Perf_node01_power_energy_ram_    6
b                                6
dtype: int64 



In [17]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "Low_Up")].count()
print("Low_Up to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "Low_Up")].count()
print("Low_Up to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "Low_Up")].count()
print("Low_Up to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "Low_Up")].count()
print("Low_Up to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "Low_Up")].count()
print("Low_Up to High_Down :\n",i, "\n")

Low_Up to High_Up :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Low_Up to Low_Up :
 Perf_node01_power_energy_ram_    5
b                                5
dtype: int64 

Low_Up to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Low_Up to Low_Down :
 Perf_node01_power_energy_ram_    12
b                                12
dtype: int64 

Low_Up to High_Down :
 Perf_node01_power_energy_ram_    3
b                                3
dtype: int64 



In [18]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "Same2")].count()
print("Same2 to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "Same2")].count()
print("Same2 to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "Same2")].count()
print("Same2 to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "Same2")].count()
print("Same2 to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "Same2")].count()
print("Same2 to High_Down :\n",i, "\n")

Same2 to High_Up :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Same2 to Low_Up :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Same2 to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Same2 to Low_Down :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Same2 to High_Down :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 



In [19]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "Low_Down")].count()
print("Low_Down to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "Low_Down")].count()
print("Low_Down to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "Low_Down")].count()
print("Low_Down to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "Low_Down")].count()
print("Low_Down to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "Low_Down")].count()
print("Low_Down to High_Down :\n",i, "\n")

Low_Down to High_Up :
 Perf_node01_power_energy_ram_    5
b                                5
dtype: int64 

Low_Down to Low_Up :
 Perf_node01_power_energy_ram_    11
b                                11
dtype: int64 

Low_Down to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Low_Down to Low_Down :
 Perf_node01_power_energy_ram_    6
b                                6
dtype: int64 

Low_Down to High_Down :
 Perf_node01_power_energy_ram_    2
b                                2
dtype: int64 



In [20]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "High_Down")].count()
print("High_Down to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "High_Down")].count()
print("High_Down to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "High_Down")].count()
print("High_Down to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "High_Down")].count()
print("High_Down to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "High_Down")].count()
print("High_Down to High_Down :\n",i, "\n")

High_Down to High_Up :
 Perf_node01_power_energy_ram_    5
b                                5
dtype: int64 

High_Down to Low_Up :
 Perf_node01_power_energy_ram_    3
b                                3
dtype: int64 

High_Down to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

High_Down to Low_Down :
 Perf_node01_power_energy_ram_    2
b                                2
dtype: int64 

High_Down to High_Down :
 Perf_node01_power_energy_ram_    2
b                                2
dtype: int64 



In [21]:
ram_matrix[0] = [3/13, 0, 0, 4/13, 6/13]
ram_matrix[1] = [0, 5/20, 0, 12/20, 3/20]
ram_matrix[3] = [5/24, 11/24, 0, 6/24, 2/24]
ram_matrix[4] = [5/12, 3/12, 0, 2/12, 2/12]

In [22]:
ram_matrix

array([[0.23076923, 0.        , 0.        , 0.30769231, 0.46153846],
       [0.        , 0.25      , 0.        , 0.6       , 0.15      ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.20833333, 0.45833333, 0.        , 0.25      , 0.08333333],
       [0.41666667, 0.25      , 0.        , 0.16666667, 0.16666667]])

In [23]:
ram_matrix = ram_matrix.round(3)
ram_matrix

array([[0.231, 0.   , 0.   , 0.308, 0.462],
       [0.   , 0.25 , 0.   , 0.6  , 0.15 ],
       [0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.208, 0.458, 0.   , 0.25 , 0.083],
       [0.417, 0.25 , 0.   , 0.167, 0.167]])

# total 전위확률 계산

In [24]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "High_Up")].count()
print("High_Up to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "High_Up")].count()
print("High_Up to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "High_Up")].count()
print("High_Up to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "High_Up")].count()
print("High_Up to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "High_Up")].count()
print("High_Up to High_Down :\n",i, "\n")

High_Up to High_Up :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Up to Low_Up :
 Perf_node01_power_energy_total_    2
c                                  2
dtype: int64 

High_Up to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Up to Low_Down :
 Perf_node01_power_energy_total_    1
c                                  1
dtype: int64 

High_Up to High_Down :
 Perf_node01_power_energy_total_    3
c                                  3
dtype: int64 



In [25]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "Low_Up")].count()
print("Low_Up to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "Low_Up")].count()
print("Low_Up to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "Low_Up")].count()
print("Low_Up to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "Low_Up")].count()
print("Low_Up to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "Low_Up")].count()
print("Low_Up to High_Down :\n",i, "\n")

Low_Up to High_Up :
 Perf_node01_power_energy_total_    1
c                                  1
dtype: int64 

Low_Up to Low_Up :
 Perf_node01_power_energy_total_    7
c                                  7
dtype: int64 

Low_Up to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Low_Up to Low_Down :
 Perf_node01_power_energy_total_    18
c                                  18
dtype: int64 

Low_Up to High_Down :
 Perf_node01_power_energy_total_    3
c                                  3
dtype: int64 



In [26]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "Same2")].count()
print("Same2 to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "Same2")].count()
print("Same2 to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "Same2")].count()
print("Same2 to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "Same2")].count()
print("Same2 to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "Same2")].count()
print("Same2 to High_Down :\n",i, "\n")

Same2 to High_Up :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to Low_Up :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to Low_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to High_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 



In [27]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "Low_Down")].count()
print("Low_Down to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "Low_Down")].count()
print("Low_Down to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "Low_Down")].count()
print("Low_Down to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "Low_Down")].count()
print("Low_Down to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "Low_Down")].count()
print("Low_Down to High_Down :\n",i, "\n")

Low_Down to High_Up :
 Perf_node01_power_energy_total_    1
c                                  1
dtype: int64 

Low_Down to Low_Up :
 Perf_node01_power_energy_total_    17
c                                  17
dtype: int64 

Low_Down to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Low_Down to Low_Down :
 Perf_node01_power_energy_total_    6
c                                  6
dtype: int64 

Low_Down to High_Down :
 Perf_node01_power_energy_total_    2
c                                  2
dtype: int64 



In [28]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "High_Down")].count()
print("High_Down to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "High_Down")].count()
print("High_Down to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "High_Down")].count()
print("High_Down to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "High_Down")].count()
print("High_Down to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "High_Down")].count()
print("High_Down to High_Down :\n",i, "\n")

High_Down to High_Up :
 Perf_node01_power_energy_total_    4
c                                  4
dtype: int64 

High_Down to Low_Up :
 Perf_node01_power_energy_total_    2
c                                  2
dtype: int64 

High_Down to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Down to Low_Down :
 Perf_node01_power_energy_total_    2
c                                  2
dtype: int64 

High_Down to High_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 



In [29]:
total_matrix[0] = [0, 2/6, 0, 1/6, 3/6]
total_matrix[1] = [1/29, 7/29, 0, 18/29, 3/29]
total_matrix[3] = [1/26, 17/26, 0, 6/26,2/26]
total_matrix[4] = [4/8, 2/8, 0, 2/8, 0]

In [30]:
total_matrix

array([[0.        , 0.33333333, 0.        , 0.16666667, 0.5       ],
       [0.03448276, 0.24137931, 0.        , 0.62068966, 0.10344828],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.03846154, 0.65384615, 0.        , 0.23076923, 0.07692308],
       [0.5       , 0.25      , 0.        , 0.25      , 0.        ]])

In [31]:
total_matrix = total_matrix.round(3)
total_matrix

array([[0.   , 0.333, 0.   , 0.167, 0.5  ],
       [0.034, 0.241, 0.   , 0.621, 0.103],
       [0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.038, 0.654, 0.   , 0.231, 0.077],
       [0.5  , 0.25 , 0.   , 0.25 , 0.   ]])

# 결론

In [32]:
print(pkg_matrix)
print(ram_matrix)
print(total_matrix)

[[0.    0.25  0.    0.375 0.375]
 [0.067 0.267 0.    0.6   0.067]
 [0.    0.    0.    0.    0.   ]
 [0.043 0.783 0.    0.043 0.13 ]
 [0.625 0.25  0.    0.125 0.   ]]
[[0.231 0.    0.    0.308 0.462]
 [0.    0.25  0.    0.6   0.15 ]
 [0.    0.    0.    0.    0.   ]
 [0.208 0.458 0.    0.25  0.083]
 [0.417 0.25  0.    0.167 0.167]]
[[0.    0.333 0.    0.167 0.5  ]
 [0.034 0.241 0.    0.621 0.103]
 [0.    0.    0.    0.    0.   ]
 [0.038 0.654 0.    0.231 0.077]
 [0.5   0.25  0.    0.25  0.   ]]
