In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## pkg, ram, total의 전위 확률 구하기

In [2]:
bt = pd.read_csv("bt.csv")

In [3]:
bt

Application Perf_node01_task_clock Perf_node01_cpu_bus_cycles_  \
0             BT                   Down                          Up   
1             BT                     Up                          Up   
2             BT                     Up                          Up   
3             BT                     Up                        Down   
4             BT                     Up                          Up   
...          ...                    ...                         ...   
1534          BT                   Down                       Same1   
1535          BT                     Up                          Up   
1536          BT                     Up                        Down   
1537          BT                   Down                        Down   
1538         NaN                    NaN                         NaN   

     Perf_node01_cpu_cpu_cycles_ Perf_node01_msr_aperf_  \
0                             Up                     Up   
1                             Up                     Up   
2                             Up                     Up   
3                           Down                     Up   
4                             Up                     Up   
...                          ...                    ...   
1534                       Same1                     Up   
1535                          Up                     Up   
1536                        Down                   Down   
1537                        Down                   Down   
1538                         NaN                    NaN   

     Perf_node01_msr_mperf_ Perf_node01_msr_tsc_ Perf_node01_cpu_ref_cycles_  \
0                        Up                 Down                          Up   
1                        Up                   Up                          Up   
2                        Up                 Down                          Up   
3                        Up                   Up                          Up   
4                        Up                   Up                          Up   
...                     ...                  ...                         ...   
1534                     Up                   Up                          Up   
1535                     Up                   Up                          Up   
1536                   Down                 Down                        Down   
1537                   Down                 Down                        Down   
1538                    NaN                  NaN                         NaN   

     Perf_node01_power_energy_pkg_          a Perf_node01_power_energy_ram_  \
0                           Low_Up        NaN                       High_Up   
1                           Low_Up     Low_Up                      Low_Down   
2                           Low_Up     Low_Up                      Low_Down   
3                           Low_Up     Low_Up                       High_Up   
4                          High_Up     Low_Up                       High_Up   
...                            ...        ...                           ...   
1534                        Low_Up     Low_Up                      Low_Down   
1535                       High_Up     Low_Up                       High_Up   
1536                     High_Down    High_Up                     High_Down   
1537                     High_Down  High_Down                     High_Down   
1538                           NaN  High_Down                           NaN   

              b Perf_node01_power_energy_total_          c  
0           NaN                          Low_Up        NaN  
1       High_Up                          Low_Up     Low_Up  
2      Low_Down                          Low_Up     Low_Up  
3      Low_Down                          Low_Up     Low_Up  
4       High_Up                         High_Up     Low_Up  
...         ...                             ...        ...  
1534  High_Down                          Low_Up   Low_Down  
1535   Low_Down                         High_

편한 비교를 위해 만듬

In [4]:
df = bt[['Perf_node01_power_energy_pkg_', 'a']]

In [5]:
ef = bt[['Perf_node01_power_energy_ram_', 'b']]

In [6]:
ff = bt[['Perf_node01_power_energy_total_', 'c']]

각 전력에 대한 전위확률 매트릭스 정의

In [7]:
pkg_matrix = np.zeros((5,5))
ram_matrix = np.zeros((5,5))
total_matrix = np.zeros((5,5))

# pkg 전위확률 계산

In [8]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "High_Up")].count()
print("High_Up to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "High_Up")].count()
print("High_Up to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "High_Up")].count()
print("High_Up to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "High_Up")].count()
print("High_Up to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "High_Up")].count()
print("High_Up to High_Down :\n",i, "\n")

High_Up to High_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Up to Low_Up :
 Perf_node01_power_energy_pkg_    1
a                                1
dtype: int64 

High_Up to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Up to Low_Down :
 Perf_node01_power_energy_pkg_    15
a                                15
dtype: int64 

High_Up to High_Down :
 Perf_node01_power_energy_pkg_    431
a                                431
dtype: int64 



In [9]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "Low_Up")].count()
print("Low_Up to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "Low_Up")].count()
print("Low_Up to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "Low_Up")].count()
print("Low_Up to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "Low_Up")].count()
print("Low_Up to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "Low_Up")].count()
print("Low_Up to High_Down :\n",i, "\n")

Low_Up to High_Up :
 Perf_node01_power_energy_pkg_    286
a                                286
dtype: int64 

Low_Up to Low_Up :
 Perf_node01_power_energy_pkg_    67
a                                67
dtype: int64 

Low_Up to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Low_Up to Low_Down :
 Perf_node01_power_energy_pkg_    39
a                                39
dtype: int64 

Low_Up to High_Down :
 Perf_node01_power_energy_pkg_    24
a                                24
dtype: int64 



In [10]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "Same2")].count()
print("Same2 to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "Same2")].count()
print("Same2 to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "Same2")].count()
print("Same2 to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "Same2")].count()
print("Same2 to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "Same2")].count()
print("Same2 to High_Down :\n",i, "\n")

Same2 to High_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Same2 to Low_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Same2 to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Same2 to Low_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Same2 to High_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 



In [11]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "Low_Down")].count()
print("Low_Down to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "Low_Down")].count()
print("Low_Down to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "Low_Down")].count()
print("Low_Down to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "Low_Down")].count()
print("Low_Down to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "Low_Down")].count()
print("Low_Down to High_Down :\n",i, "\n")

Low_Down to High_Up :
 Perf_node01_power_energy_pkg_    161
a                                161
dtype: int64 

Low_Down to Low_Up :
 Perf_node01_power_energy_pkg_    34
a                                34
dtype: int64 

Low_Down to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Low_Down to Low_Down :
 Perf_node01_power_energy_pkg_    23
a                                23
dtype: int64 

Low_Down to High_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 



In [12]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "High_Down")].count()
print("High_Down to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "High_Down")].count()
print("High_Down to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "High_Down")].count()
print("High_Down to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "High_Down")].count()
print("High_Down to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "High_Down")].count()
print("High_Down to High_Down :\n",i, "\n")

High_Down to High_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Down to Low_Up :
 Perf_node01_power_energy_pkg_    313
a                                313
dtype: int64 

High_Down to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Down to Low_Down :
 Perf_node01_power_energy_pkg_    141
a                                141
dtype: int64 

High_Down to High_Down :
 Perf_node01_power_energy_pkg_    2
a                                2
dtype: int64 



In [13]:
pkg_matrix[0][1] = 1/447
pkg_matrix[0][3] = 15/447
pkg_matrix[0][4] = 431/447

In [14]:
pkg_matrix[1][0] = 286/416
pkg_matrix[1][1] = 67/416
pkg_matrix[1][3] = 39/416
pkg_matrix[1][4] = 24/416

In [15]:
pkg_matrix[3][0] = 161/218
pkg_matrix[3][1] = 34/218
pkg_matrix[3][3] = 23/218

In [16]:
pkg_matrix[4][1] = 313/456
pkg_matrix[4][3] = 141/456
pkg_matrix[4][4] = 2/456

In [17]:
pkg_matrix

array([[0.        , 0.00223714, 0.        , 0.03355705, 0.96420582],
       [0.6875    , 0.16105769, 0.        , 0.09375   , 0.05769231],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.73853211, 0.1559633 , 0.        , 0.10550459, 0.        ],
       [0.        , 0.68640351, 0.        , 0.30921053, 0.00438596]])

In [18]:
pkg_matrix = pkg_matrix.round(3)
pkg_matrix

array([[0.   , 0.002, 0.   , 0.034, 0.964],
       [0.688, 0.161, 0.   , 0.094, 0.058],
       [0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.739, 0.156, 0.   , 0.106, 0.   ],
       [0.   , 0.686, 0.   , 0.309, 0.004]])

# ram 전위확률 계산

In [19]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "High_Up")].count()
print("High_Up to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "High_Up")].count()
print("High_Up to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "High_Up")].count()
print("High_Up to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "High_Up")].count()
print("High_Up to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "High_Up")].count()
print("High_Up to High_Down :\n",i, "\n")

High_Up to High_Up :
 Perf_node01_power_energy_ram_    14
b                                14
dtype: int64 

High_Up to Low_Up :
 Perf_node01_power_energy_ram_    15
b                                15
dtype: int64 

High_Up to Same2 :
 Perf_node01_power_energy_ram_    1
b                                1
dtype: int64 

High_Up to Low_Down :
 Perf_node01_power_energy_ram_    111
b                                111
dtype: int64 

High_Up to High_Down :
 Perf_node01_power_energy_ram_    342
b                                342
dtype: int64 



In [20]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "Low_Up")].count()
print("Low_Up to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "Low_Up")].count()
print("Low_Up to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "Low_Up")].count()
print("Low_Up to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "Low_Up")].count()
print("Low_Up to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "Low_Up")].count()
print("Low_Up to High_Down :\n",i, "\n")

Low_Up to High_Up :
 Perf_node01_power_energy_ram_    60
b                                60
dtype: int64 

Low_Up to Low_Up :
 Perf_node01_power_energy_ram_    18
b                                18
dtype: int64 

Low_Up to Same2 :
 Perf_node01_power_energy_ram_    1
b                                1
dtype: int64 

Low_Up to Low_Down :
 Perf_node01_power_energy_ram_    24
b                                24
dtype: int64 

Low_Up to High_Down :
 Perf_node01_power_energy_ram_    22
b                                22
dtype: int64 



In [21]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "Same2")].count()
print("Same2 to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "Same2")].count()
print("Same2 to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "Same2")].count()
print("Same2 to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "Same2")].count()
print("Same2 to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "Same2")].count()
print("Same2 to High_Down :\n",i, "\n")

Same2 to High_Up :
 Perf_node01_power_energy_ram_    1
b                                1
dtype: int64 

Same2 to Low_Up :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Same2 to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Same2 to Low_Down :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Same2 to High_Down :
 Perf_node01_power_energy_ram_    2
b                                2
dtype: int64 



In [22]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "Low_Down")].count()
print("Low_Down to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "Low_Down")].count()
print("Low_Down to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "Low_Down")].count()
print("Low_Down to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "Low_Down")].count()
print("Low_Down to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "Low_Down")].count()
print("Low_Down to High_Down :\n",i, "\n")

Low_Down to High_Up :
 Perf_node01_power_energy_ram_    235
b                                235
dtype: int64 

Low_Down to Low_Up :
 Perf_node01_power_energy_ram_    28
b                                28
dtype: int64 

Low_Down to Same2 :
 Perf_node01_power_energy_ram_    1
b                                1
dtype: int64 

Low_Down to Low_Down :
 Perf_node01_power_energy_ram_    69
b                                69
dtype: int64 

Low_Down to High_Down :
 Perf_node01_power_energy_ram_    59
b                                59
dtype: int64 



In [23]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "High_Down")].count()
print("High_Down to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "High_Down")].count()
print("High_Down to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "High_Down")].count()
print("High_Down to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "High_Down")].count()
print("High_Down to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "High_Down")].count()
print("High_Down to High_Down :\n",i, "\n")

High_Down to High_Up :
 Perf_node01_power_energy_ram_    172
b                                172
dtype: int64 

High_Down to Low_Up :
 Perf_node01_power_energy_ram_    64
b                                64
dtype: int64 

High_Down to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

High_Down to Low_Down :
 Perf_node01_power_energy_ram_    188
b                                188
dtype: int64 

High_Down to High_Down :
 Perf_node01_power_energy_ram_    110
b                                110
dtype: int64 



In [24]:
ram_matrix[0] = [14/483, 15/483, 1/483, 111/483, 342/483]
ram_matrix[1] = [60/125, 18/125, 1/125, 24/125, 22/125]
ram_matrix[2] = [1/3, 0, 0, 0, 2/3]
ram_matrix[3] = [235/392, 28/392, 1/392, 69/392, 59/392]
ram_matrix[4] = [172/534, 64/534, 0, 188/534, 110/534]

In [25]:
ram_matrix

array([[0.02898551, 0.0310559 , 0.00207039, 0.22981366, 0.70807453],
       [0.48      , 0.144     , 0.008     , 0.192     , 0.176     ],
       [0.33333333, 0.        , 0.        , 0.        , 0.66666667],
       [0.5994898 , 0.07142857, 0.00255102, 0.17602041, 0.1505102 ],
       [0.32209738, 0.11985019, 0.        , 0.35205993, 0.20599251]])

In [26]:
ram_matrix = ram_matrix.round(3)
ram_matrix

array([[0.029, 0.031, 0.002, 0.23 , 0.708],
       [0.48 , 0.144, 0.008, 0.192, 0.176],
       [0.333, 0.   , 0.   , 0.   , 0.667],
       [0.599, 0.071, 0.003, 0.176, 0.151],
       [0.322, 0.12 , 0.   , 0.352, 0.206]])

# total 전위확률 계산

In [27]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "High_Up")].count()
print("High_Up to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "High_Up")].count()
print("High_Up to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "High_Up")].count()
print("High_Up to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "High_Up")].count()
print("High_Up to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "High_Up")].count()
print("High_Up to High_Down :\n",i, "\n")

High_Up to High_Up :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Up to Low_Up :
 Perf_node01_power_energy_total_    1
c                                  1
dtype: int64 

High_Up to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Up to Low_Down :
 Perf_node01_power_energy_total_    16
c                                  16
dtype: int64 

High_Up to High_Down :
 Perf_node01_power_energy_total_    439
c                                  439
dtype: int64 



In [28]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "Low_Up")].count()
print("Low_Up to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "Low_Up")].count()
print("Low_Up to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "Low_Up")].count()
print("Low_Up to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "Low_Up")].count()
print("Low_Up to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "Low_Up")].count()
print("Low_Up to High_Down :\n",i, "\n")

Low_Up to High_Up :
 Perf_node01_power_energy_total_    249
c                                  249
dtype: int64 

Low_Up to Low_Up :
 Perf_node01_power_energy_total_    45
c                                  45
dtype: int64 

Low_Up to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Low_Up to Low_Down :
 Perf_node01_power_energy_total_    45
c                                  45
dtype: int64 

Low_Up to High_Down :
 Perf_node01_power_energy_total_    13
c                                  13
dtype: int64 



In [29]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "Same2")].count()
print("Same2 to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "Same2")].count()
print("Same2 to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "Same2")].count()
print("Same2 to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "Same2")].count()
print("Same2 to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "Same2")].count()
print("Same2 to High_Down :\n",i, "\n")

Same2 to High_Up :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to Low_Up :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to Low_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to High_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 



In [30]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "Low_Down")].count()
print("Low_Down to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "Low_Down")].count()
print("Low_Down to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "Low_Down")].count()
print("Low_Down to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "Low_Down")].count()
print("Low_Down to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "Low_Down")].count()
print("Low_Down to High_Down :\n",i, "\n")

Low_Down to High_Up :
 Perf_node01_power_energy_total_    207
c                                  207
dtype: int64 

Low_Down to Low_Up :
 Perf_node01_power_energy_total_    41
c                                  41
dtype: int64 

Low_Down to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Low_Down to Low_Down :
 Perf_node01_power_energy_total_    28
c                                  28
dtype: int64 

Low_Down to High_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 



In [31]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "High_Down")].count()
print("High_Down to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "High_Down")].count()
print("High_Down to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "High_Down")].count()
print("High_Down to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "High_Down")].count()
print("High_Down to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "High_Down")].count()
print("High_Down to High_Down :\n",i, "\n")

High_Down to High_Up :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Down to Low_Up :
 Perf_node01_power_energy_total_    264
c                                  264
dtype: int64 

High_Down to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Down to Low_Down :
 Perf_node01_power_energy_total_    187
c                                  187
dtype: int64 

High_Down to High_Down :
 Perf_node01_power_energy_total_    2
c                                  2
dtype: int64 



In [32]:
total_matrix[0] = [0, 1/456, 0, 16/456, 439/456]
total_matrix[1] = [249/352, 45/352, 0, 45/352, 13/352]
total_matrix[3] = [207/276, 41/276, 0, 28/276, 0]
total_matrix[4] = [0, 264/453, 0, 187/453, 2/453]

In [33]:
total_matrix

array([[0.        , 0.00219298, 0.        , 0.03508772, 0.9627193 ],
       [0.70738636, 0.12784091, 0.        , 0.12784091, 0.03693182],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.75      , 0.14855072, 0.        , 0.10144928, 0.        ],
       [0.        , 0.58278146, 0.        , 0.41280353, 0.00441501]])

In [34]:
total_matrix = total_matrix.round(3)
total_matrix

array([[0.   , 0.002, 0.   , 0.035, 0.963],
       [0.707, 0.128, 0.   , 0.128, 0.037],
       [0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.75 , 0.149, 0.   , 0.101, 0.   ],
       [0.   , 0.583, 0.   , 0.413, 0.004]])

# 결론

In [35]:
print(pkg_matrix)
print(ram_matrix)
print(total_matrix)

[[0.    0.002 0.    0.034 0.964]
 [0.688 0.161 0.    0.094 0.058]
 [0.    0.    0.    0.    0.   ]
 [0.739 0.156 0.    0.106 0.   ]
 [0.    0.686 0.    0.309 0.004]]
[[0.029 0.031 0.002 0.23  0.708]
 [0.48  0.144 0.008 0.192 0.176]
 [0.333 0.    0.    0.    0.667]
 [0.599 0.071 0.003 0.176 0.151]
 [0.322 0.12  0.    0.352 0.206]]
[[0.    0.002 0.    0.035 0.963]
 [0.707 0.128 0.    0.128 0.037]
 [0.    0.    0.    0.    0.   ]
 [0.75  0.149 0.    0.101 0.   ]
 [0.    0.583 0.    0.413 0.004]]
