In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## pkg, ram, total의 전위 확률 구하기

In [2]:
bt = pd.read_csv("cg.csv")

In [3]:
bt

Application Perf_node01_task_clock Perf_node01_cpu_bus_cycles_  \
0             CG                     Up                          Up   
1             CG                   Down                        Down   
2             CG                   Down                          Up   
3             CG                   Down                        Down   
4             CG                   Down                          Up   
...          ...                    ...                         ...   
2049          CG                   Down                        Down   
2050          CG                   Down                        Down   
2051          CG                     Up                        Down   
2052          CG                   Down                        Down   
2053         NaN                    NaN                         NaN   

     Perf_node01_cpu_cpu_cycles_ Perf_node01_msr_aperf_  \
0                             Up                     Up   
1                           Down                   Down   
2                             Up                   Down   
3                           Down                   Down   
4                             Up                     Up   
...                          ...                    ...   
2049                        Down                   Down   
2050                        Down                   Down   
2051                        Down                   Down   
2052                        Down                   Down   
2053                         NaN                    NaN   

     Perf_node01_msr_mperf_ Perf_node01_msr_tsc_ Perf_node01_cpu_ref_cycles_  \
0                        Up                   Up                          Up   
1                      Down                 Down                        Down   
2                      Down                 Down                          Up   
3                      Down                 Down                        Down   
4                        Up                 Down                          Up   
...                     ...                  ...                         ...   
2049                   Down                 Down                       Same1   
2050                   Down                 Down                        Down   
2051                   Down                   Up                        Down   
2052                   Down                 Down                        Down   
2053                    NaN                  NaN                         NaN   

     Perf_node01_power_energy_pkg_          a Perf_node01_power_energy_ram_  \
0                           Low_Up        NaN                      Low_Down   
1                         Low_Down     Low_Up                        Low_Up   
2                           Low_Up   Low_Down                        Low_Up   
3                         Low_Down     Low_Up                      Low_Down   
4                           Low_Up   Low_Down                       High_Up   
...                            ...        ...                           ...   
2049                      Low_Down   Low_Down                      Low_Down   
2050                        Low_Up   Low_Down                      Low_Down   
2051                     High_Down     Low_Up                     High_Down   
2052                        Low_Up  High_Down                     High_Down   
2053                           NaN     Low_Up                           NaN   

              b Perf_node01_power_energy_total_          c  
0           NaN                        Low_Down        NaN  
1      Low_Down                          Low_Up   Low_Down  
2        Low_Up                          Low_Up     Low_Up  
3        Low_Up                        Low_Down     Low_Up  
4      Low_Down                          Low_Up   Low_Down  
...         ...                             ...        ...  
2049   Low_Down                        Low_Down   Low_Down  
2050   Low_Down                          Low_

편한 비교를 위해 만듬

In [4]:
df = bt[['Perf_node01_power_energy_pkg_', 'a']]

In [5]:
ef = bt[['Perf_node01_power_energy_ram_', 'b']]

In [6]:
ff = bt[['Perf_node01_power_energy_total_', 'c']]

각 전력에 대한 전위확률 매트릭스 정의

In [7]:
pkg_matrix = np.zeros((5,5))
ram_matrix = np.zeros((5,5))
total_matrix = np.zeros((5,5))

# pkg 전위확률 계산

In [25]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "High_Up")].count()
print("High_Up to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "High_Up")].count()
print("High_Up to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "High_Up")].count()
print("High_Up to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "High_Up")].count()
print("High_Up to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "High_Up")].count()
print("High_Up to High_Down :\n",i, "\n")

High_Up to High_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Up to Low_Up :
 Perf_node01_power_energy_pkg_    1
a                                1
dtype: int64 

High_Up to Same2 :
 Perf_node01_power_energy_pkg_    1
a                                1
dtype: int64 

High_Up to Low_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Up to High_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 



In [26]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "Low_Up")].count()
print("Low_Up to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "Low_Up")].count()
print("Low_Up to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "Low_Up")].count()
print("Low_Up to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "Low_Up")].count()
print("Low_Up to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "Low_Up")].count()
print("Low_Up to High_Down :\n",i, "\n")

Low_Up to High_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Low_Up to Low_Up :
 Perf_node01_power_energy_pkg_    343
a                                343
dtype: int64 

Low_Up to Same2 :
 Perf_node01_power_energy_pkg_    3
a                                3
dtype: int64 

Low_Up to Low_Down :
 Perf_node01_power_energy_pkg_    691
a                                691
dtype: int64 

Low_Up to High_Down :
 Perf_node01_power_energy_pkg_    3
a                                3
dtype: int64 



In [27]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "Same2")].count()
print("Same2 to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "Same2")].count()
print("Same2 to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "Same2")].count()
print("Same2 to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "Same2")].count()
print("Same2 to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "Same2")].count()
print("Same2 to High_Down :\n",i, "\n")

Same2 to High_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Same2 to Low_Up :
 Perf_node01_power_energy_pkg_    4
a                                4
dtype: int64 

Same2 to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Same2 to Low_Down :
 Perf_node01_power_energy_pkg_    2
a                                2
dtype: int64 

Same2 to High_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 



In [28]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "Low_Down")].count()
print("Low_Down to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "Low_Down")].count()
print("Low_Down to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "Low_Down")].count()
print("Low_Down to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "Low_Down")].count()
print("Low_Down to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "Low_Down")].count()
print("Low_Down to High_Down :\n",i, "\n")

Low_Down to High_Up :
 Perf_node01_power_energy_pkg_    2
a                                2
dtype: int64 

Low_Down to Low_Up :
 Perf_node01_power_energy_pkg_    689
a                                689
dtype: int64 

Low_Down to Same2 :
 Perf_node01_power_energy_pkg_    2
a                                2
dtype: int64 

Low_Down to Low_Down :
 Perf_node01_power_energy_pkg_    308
a                                308
dtype: int64 

Low_Down to High_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 



In [29]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "High_Down")].count()
print("High_Down to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "High_Down")].count()
print("High_Down to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "High_Down")].count()
print("High_Down to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "High_Down")].count()
print("High_Down to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "High_Down")].count()
print("High_Down to High_Down :\n",i, "\n")

High_Down to High_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Down to Low_Up :
 Perf_node01_power_energy_pkg_    3
a                                3
dtype: int64 

High_Down to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Down to Low_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Down to High_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 



In [30]:
pkg_matrix[0] = [0, 1/2, 1/2, 0, 0]
pkg_matrix[1] = [0, 343/1040, 3/1040, 691/1040, 3/1040]
pkg_matrix[2] = [0, 4/6, 0, 2/6, 0]
pkg_matrix[3] = [2/1001, 689/1001, 2/1001, 308/1001, 0]
pkg_matrix[4] = [0, 1, 0, 0, 0]

In [242]:
pkg_matrix[4][1] = 313/456
pkg_matrix[4][3] = 141/456
pkg_matrix[4][4] = 2/456

In [31]:
pkg_matrix

array([[0.        , 0.5       , 0.5       , 0.        , 0.        ],
       [0.        , 0.32980769, 0.00288462, 0.66442308, 0.00288462],
       [0.        , 0.66666667, 0.        , 0.33333333, 0.        ],
       [0.001998  , 0.68831169, 0.001998  , 0.30769231, 0.        ],
       [0.        , 1.        , 0.        , 0.        , 0.        ]])

In [32]:
pkg_matrix = pkg_matrix.round(3)
pkg_matrix

array([[0.   , 0.5  , 0.5  , 0.   , 0.   ],
       [0.   , 0.33 , 0.003, 0.664, 0.003],
       [0.   , 0.667, 0.   , 0.333, 0.   ],
       [0.002, 0.688, 0.002, 0.308, 0.   ],
       [0.   , 1.   , 0.   , 0.   , 0.   ]])

# ram 전위확률 계산

In [33]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "High_Up")].count()
print("High_Up to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "High_Up")].count()
print("High_Up to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "High_Up")].count()
print("High_Up to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "High_Up")].count()
print("High_Up to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "High_Up")].count()
print("High_Up to High_Down :\n",i, "\n")

High_Up to High_Up :
 Perf_node01_power_energy_ram_    8
b                                8
dtype: int64 

High_Up to Low_Up :
 Perf_node01_power_energy_ram_    64
b                                64
dtype: int64 

High_Up to Same2 :
 Perf_node01_power_energy_ram_    2
b                                2
dtype: int64 

High_Up to Low_Down :
 Perf_node01_power_energy_ram_    51
b                                51
dtype: int64 

High_Up to High_Down :
 Perf_node01_power_energy_ram_    3
b                                3
dtype: int64 



In [34]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "Low_Up")].count()
print("Low_Up to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "Low_Up")].count()
print("Low_Up to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "Low_Up")].count()
print("Low_Up to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "Low_Up")].count()
print("Low_Up to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "Low_Up")].count()
print("Low_Up to High_Down :\n",i, "\n")

Low_Up to High_Up :
 Perf_node01_power_energy_ram_    9
b                                9
dtype: int64 

Low_Up to Low_Up :
 Perf_node01_power_energy_ram_    279
b                                279
dtype: int64 

Low_Up to Same2 :
 Perf_node01_power_energy_ram_    3
b                                3
dtype: int64 

Low_Up to Low_Down :
 Perf_node01_power_energy_ram_    542
b                                542
dtype: int64 

Low_Up to High_Down :
 Perf_node01_power_energy_ram_    42
b                                42
dtype: int64 



In [35]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "Same2")].count()
print("Same2 to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "Same2")].count()
print("Same2 to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "Same2")].count()
print("Same2 to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "Same2")].count()
print("Same2 to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "Same2")].count()
print("Same2 to High_Down :\n",i, "\n")

Same2 to High_Up :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Same2 to Low_Up :
 Perf_node01_power_energy_ram_    3
b                                3
dtype: int64 

Same2 to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Same2 to Low_Down :
 Perf_node01_power_energy_ram_    3
b                                3
dtype: int64 

Same2 to High_Down :
 Perf_node01_power_energy_ram_    2
b                                2
dtype: int64 



In [36]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "Low_Down")].count()
print("Low_Down to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "Low_Down")].count()
print("Low_Down to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "Low_Down")].count()
print("Low_Down to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "Low_Down")].count()
print("Low_Down to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "Low_Down")].count()
print("Low_Down to High_Down :\n",i, "\n")

Low_Down to High_Up :
 Perf_node01_power_energy_ram_    29
b                                29
dtype: int64 

Low_Down to Low_Up :
 Perf_node01_power_energy_ram_    517
b                                517
dtype: int64 

Low_Down to Same2 :
 Perf_node01_power_energy_ram_    3
b                                3
dtype: int64 

Low_Down to Low_Down :
 Perf_node01_power_energy_ram_    324
b                                324
dtype: int64 

Low_Down to High_Down :
 Perf_node01_power_energy_ram_    58
b                                58
dtype: int64 



In [37]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "High_Down")].count()
print("High_Down to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "High_Down")].count()
print("High_Down to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "High_Down")].count()
print("High_Down to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "High_Down")].count()
print("High_Down to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "High_Down")].count()
print("High_Down to High_Down :\n",i, "\n")

High_Down to High_Up :
 Perf_node01_power_energy_ram_    82
b                                82
dtype: int64 

High_Down to Low_Up :
 Perf_node01_power_energy_ram_    12
b                                12
dtype: int64 

High_Down to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

High_Down to Low_Down :
 Perf_node01_power_energy_ram_    10
b                                10
dtype: int64 

High_Down to High_Down :
 Perf_node01_power_energy_ram_    6
b                                6
dtype: int64 



In [38]:
ram_matrix[0] = [8/128, 64/128, 2/128, 51/128, 3/128]
ram_matrix[1] = [9/875, 279/875, 3/875, 542/875, 42/875]
ram_matrix[2] = [0, 3/8, 0, 3/8, 2/8]
ram_matrix[3] = [29/931, 517/931, 3/931, 324/931, 58/931]
ram_matrix[4] = [82/110, 12/110, 0, 10/110, 6/110]

In [39]:
ram_matrix

array([[0.0625    , 0.5       , 0.015625  , 0.3984375 , 0.0234375 ],
       [0.01028571, 0.31885714, 0.00342857, 0.61942857, 0.048     ],
       [0.        , 0.375     , 0.        , 0.375     , 0.25      ],
       [0.0311493 , 0.55531686, 0.00322234, 0.34801289, 0.0622986 ],
       [0.74545455, 0.10909091, 0.        , 0.09090909, 0.05454545]])

In [40]:
ram_matrix = ram_matrix.round(3)
ram_matrix

array([[0.062, 0.5  , 0.016, 0.398, 0.023],
       [0.01 , 0.319, 0.003, 0.619, 0.048],
       [0.   , 0.375, 0.   , 0.375, 0.25 ],
       [0.031, 0.555, 0.003, 0.348, 0.062],
       [0.745, 0.109, 0.   , 0.091, 0.055]])

# total 전위확률 계산

In [41]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "High_Up")].count()
print("High_Up to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "High_Up")].count()
print("High_Up to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "High_Up")].count()
print("High_Up to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "High_Up")].count()
print("High_Up to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "High_Up")].count()
print("High_Up to High_Down :\n",i, "\n")

High_Up to High_Up :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Up to Low_Up :
 Perf_node01_power_energy_total_    2
c                                  2
dtype: int64 

High_Up to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Up to Low_Down :
 Perf_node01_power_energy_total_    1
c                                  1
dtype: int64 

High_Up to High_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 



In [42]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "Low_Up")].count()
print("Low_Up to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "Low_Up")].count()
print("Low_Up to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "Low_Up")].count()
print("Low_Up to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "Low_Up")].count()
print("Low_Up to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "Low_Up")].count()
print("Low_Up to High_Down :\n",i, "\n")

Low_Up to High_Up :
 Perf_node01_power_energy_total_    2
c                                  2
dtype: int64 

Low_Up to Low_Up :
 Perf_node01_power_energy_total_    369
c                                  369
dtype: int64 

Low_Up to Same2 :
 Perf_node01_power_energy_total_    2
c                                  2
dtype: int64 

Low_Up to Low_Down :
 Perf_node01_power_energy_total_    659
c                                  659
dtype: int64 

Low_Up to High_Down :
 Perf_node01_power_energy_total_    3
c                                  3
dtype: int64 



In [43]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "Same2")].count()
print("Same2 to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "Same2")].count()
print("Same2 to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "Same2")].count()
print("Same2 to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "Same2")].count()
print("Same2 to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "Same2")].count()
print("Same2 to High_Down :\n",i, "\n")

Same2 to High_Up :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to Low_Up :
 Perf_node01_power_energy_total_    1
c                                  1
dtype: int64 

Same2 to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to Low_Down :
 Perf_node01_power_energy_total_    1
c                                  1
dtype: int64 

Same2 to High_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 



In [44]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "Low_Down")].count()
print("Low_Down to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "Low_Down")].count()
print("Low_Down to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "Low_Down")].count()
print("Low_Down to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "Low_Down")].count()
print("Low_Down to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "Low_Down")].count()
print("Low_Down to High_Down :\n",i, "\n")

Low_Down to High_Up :
 Perf_node01_power_energy_total_    1
c                                  1
dtype: int64 

Low_Down to Low_Up :
 Perf_node01_power_energy_total_    662
c                                  662
dtype: int64 

Low_Down to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Low_Down to Low_Down :
 Perf_node01_power_energy_total_    346
c                                  346
dtype: int64 

Low_Down to High_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 



In [45]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "High_Down")].count()
print("High_Down to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "High_Down")].count()
print("High_Down to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "High_Down")].count()
print("High_Down to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "High_Down")].count()
print("High_Down to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "High_Down")].count()
print("High_Down to High_Down :\n",i, "\n")

High_Down to High_Up :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Down to Low_Up :
 Perf_node01_power_energy_total_    1
c                                  1
dtype: int64 

High_Down to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Down to Low_Down :
 Perf_node01_power_energy_total_    2
c                                  2
dtype: int64 

High_Down to High_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 



In [48]:
total_matrix[0] = [0, 2/3, 0, 1/3, 0]
total_matrix[1] = [2/1035, 369/1035, 2/1035, 659/1035, 3/1035]
total_matrix[2] = [0, 1/2, 0, 1/2, 0]
total_matrix[3] = [1/1009, 662/1009, 0, 346/1009, 0]
total_matrix[4] = [0, 1/3, 0, 2/3, 0]

In [49]:
total_matrix

array([[0.        , 0.66666667, 0.        , 0.33333333, 0.        ],
       [0.00193237, 0.35652174, 0.00193237, 0.63671498, 0.00289855],
       [0.        , 0.5       , 0.        , 0.5       , 0.        ],
       [0.00099108, 0.65609514, 0.        , 0.34291378, 0.        ],
       [0.        , 0.33333333, 0.        , 0.66666667, 0.        ]])

In [50]:
total_matrix = total_matrix.round(3)
total_matrix

array([[0.   , 0.667, 0.   , 0.333, 0.   ],
       [0.002, 0.357, 0.002, 0.637, 0.003],
       [0.   , 0.5  , 0.   , 0.5  , 0.   ],
       [0.001, 0.656, 0.   , 0.343, 0.   ],
       [0.   , 0.333, 0.   , 0.667, 0.   ]])

# 결론

In [51]:
print(pkg_matrix)
print(ram_matrix)
print(total_matrix)

[[0.    0.5   0.5   0.    0.   ]
 [0.    0.33  0.003 0.664 0.003]
 [0.    0.667 0.    0.333 0.   ]
 [0.002 0.688 0.002 0.308 0.   ]
 [0.    1.    0.    0.    0.   ]]
[[0.062 0.5   0.016 0.398 0.023]
 [0.01  0.319 0.003 0.619 0.048]
 [0.    0.375 0.    0.375 0.25 ]
 [0.031 0.555 0.003 0.348 0.062]
 [0.745 0.109 0.    0.091 0.055]]
[[0.    0.667 0.    0.333 0.   ]
 [0.002 0.357 0.002 0.637 0.003]
 [0.    0.5   0.    0.5   0.   ]
 [0.001 0.656 0.    0.343 0.   ]
 [0.    0.333 0.    0.667 0.   ]]
