In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## pkg, ram, total의 전위 확률 구하기

In [2]:
bt = pd.read_csv("ft.csv")

In [3]:
bt

Application Perf_node01_task_clock Perf_node01_cpu_bus_cycles_  \
0             FT                     Up                          Up   
1             FT                     Up                          Up   
2             FT                     Up                        Down   
3             FT                   Down                          Up   
4             FT                     Up                          Up   
...          ...                    ...                         ...   
1596          FT                   Down                        Down   
1597          FT                   Down                        Down   
1598          FT                     Up                        Down   
1599          FT                   Down                        Down   
1600         NaN                    NaN                         NaN   

     Perf_node01_cpu_cpu_cycles_ Perf_node01_msr_aperf_  \
0                             Up                     Up   
1                             Up                     Up   
2                           Down                   Down   
3                             Up                     Up   
4                             Up                     Up   
...                          ...                    ...   
1596                        Down                   Down   
1597                        Down                   Down   
1598                        Down                   Down   
1599                        Down                   Down   
1600                         NaN                    NaN   

     Perf_node01_msr_mperf_ Perf_node01_msr_tsc_ Perf_node01_cpu_ref_cycles_  \
0                        Up                 Down                          Up   
1                        Up                   Up                          Up   
2                      Down                 Down                        Down   
3                        Up                 Down                          Up   
4                        Up                   Up                          Up   
...                     ...                  ...                         ...   
1596                   Down                 Down                        Down   
1597                   Down                 Down                        Down   
1598                   Down                 Down                        Down   
1599                   Down                 Down                          Up   
1600                    NaN                  NaN                         NaN   

     Perf_node01_power_energy_pkg_          a Perf_node01_power_energy_ram_  \
0                           Low_Up        NaN                        Low_Up   
1                           Low_Up     Low_Up                        Low_Up   
2                         Low_Down     Low_Up                       High_Up   
3                          High_Up   Low_Down                       High_Up   
4                          High_Up    High_Up                       High_Up   
...                            ...        ...                           ...   
1596                      Low_Down     Low_Up                      Low_Down   
1597                     High_Down   Low_Down                     High_Down   
1598                     High_Down  High_Down                     High_Down   
1599                        Low_Up  High_Down                      Low_Down   
1600                           NaN     Low_Up                           NaN   

              b Perf_node01_power_energy_total_          c  
0           NaN                          Low_Up        NaN  
1        Low_Up                          Low_Up     Low_Up  
2        Low_Up                        Low_Down     Low_Up  
3       High_Up                         High_Up   Low_Down  
4       High_Up                         High_Up    High_Up  
...         ...                             ...        ...  
1596   Low_Down                        Low_Down     Low_Up  
1597   Low_Down                       High_Do

편한 비교를 위해 만듬

In [4]:
df = bt[['Perf_node01_power_energy_pkg_', 'a']]

In [5]:
ef = bt[['Perf_node01_power_energy_ram_', 'b']]

In [6]:
ff = bt[['Perf_node01_power_energy_total_', 'c']]

각 전력에 대한 전위확률 매트릭스 정의

In [7]:
pkg_matrix = np.zeros((5,5))
ram_matrix = np.zeros((5,5))
total_matrix = np.zeros((5,5))

# pkg 전위확률 계산

In [8]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "High_Up")].count()
print("High_Up to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "High_Up")].count()
print("High_Up to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "High_Up")].count()
print("High_Up to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "High_Up")].count()
print("High_Up to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "High_Up")].count()
print("High_Up to High_Down :\n",i, "\n")

High_Up to High_Up :
 Perf_node01_power_energy_pkg_    3
a                                3
dtype: int64 

High_Up to Low_Up :
 Perf_node01_power_energy_pkg_    30
a                                30
dtype: int64 

High_Up to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Up to Low_Down :
 Perf_node01_power_energy_pkg_    51
a                                51
dtype: int64 

High_Up to High_Down :
 Perf_node01_power_energy_pkg_    2
a                                2
dtype: int64 



In [9]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "Low_Up")].count()
print("Low_Up to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "Low_Up")].count()
print("Low_Up to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "Low_Up")].count()
print("Low_Up to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "Low_Up")].count()
print("Low_Up to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "Low_Up")].count()
print("Low_Up to High_Down :\n",i, "\n")

Low_Up to High_Up :
 Perf_node01_power_energy_pkg_    9
a                                9
dtype: int64 

Low_Up to Low_Up :
 Perf_node01_power_energy_pkg_    208
a                                208
dtype: int64 

Low_Up to Same2 :
 Perf_node01_power_energy_pkg_    1
a                                1
dtype: int64 

Low_Up to Low_Down :
 Perf_node01_power_energy_pkg_    423
a                                423
dtype: int64 

Low_Up to High_Down :
 Perf_node01_power_energy_pkg_    19
a                                19
dtype: int64 



In [10]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "Same2")].count()
print("Same2 to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "Same2")].count()
print("Same2 to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "Same2")].count()
print("Same2 to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "Same2")].count()
print("Same2 to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "Same2")].count()
print("Same2 to High_Down :\n",i, "\n")

Same2 to High_Up :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Same2 to Low_Up :
 Perf_node01_power_energy_pkg_    7
a                                7
dtype: int64 

Same2 to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Same2 to Low_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

Same2 to High_Down :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 



In [11]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "Low_Down")].count()
print("Low_Down to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "Low_Down")].count()
print("Low_Down to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "Low_Down")].count()
print("Low_Down to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "Low_Down")].count()
print("Low_Down to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "Low_Down")].count()
print("Low_Down to High_Down :\n",i, "\n")

Low_Down to High_Up :
 Perf_node01_power_energy_pkg_    33
a                                33
dtype: int64 

Low_Down to Low_Up :
 Perf_node01_power_energy_pkg_    402
a                                402
dtype: int64 

Low_Down to Same2 :
 Perf_node01_power_energy_pkg_    6
a                                6
dtype: int64 

Low_Down to Low_Down :
 Perf_node01_power_energy_pkg_    247
a                                247
dtype: int64 

Low_Down to High_Down :
 Perf_node01_power_energy_pkg_    59
a                                59
dtype: int64 



In [12]:
i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Up") & (df["a"] == "High_Down")].count()
print("High_Down to High_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Up") & (df["a"] == "High_Down")].count()
print("High_Down to Low_Up :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Same2") & (df["a"] == "High_Down")].count()
print("High_Down to Same2 :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "Low_Down") & (df["a"] == "High_Down")].count()
print("High_Down to Low_Down :\n",i, "\n")

i = df.loc[(df["Perf_node01_power_energy_pkg_"] == "High_Down") & (df["a"] == "High_Down")].count()
print("High_Down to High_Down :\n",i, "\n")

High_Down to High_Up :
 Perf_node01_power_energy_pkg_    41
a                                41
dtype: int64 

High_Down to Low_Up :
 Perf_node01_power_energy_pkg_    13
a                                13
dtype: int64 

High_Down to Same2 :
 Perf_node01_power_energy_pkg_    0
a                                0
dtype: int64 

High_Down to Low_Down :
 Perf_node01_power_energy_pkg_    26
a                                26
dtype: int64 

High_Down to High_Down :
 Perf_node01_power_energy_pkg_    19
a                                19
dtype: int64 



In [13]:
pkg_matrix[0] = [3/86, 30/86, 0, 51/86, 2/86]
pkg_matrix[1] = [9/660, 208/660, 1/660, 423/660, 19/660]
pkg_matrix[2] = [0, 1, 0, 0, 0]
pkg_matrix[3] = [33/747, 402/747, 6/747, 247/747, 59/747]
pkg_matrix[4] = [41/99, 13/99, 0, 26/99, 19/99]

In [14]:
pkg_matrix

array([[0.03488372, 0.34883721, 0.        , 0.59302326, 0.02325581],
       [0.01363636, 0.31515152, 0.00151515, 0.64090909, 0.02878788],
       [0.        , 1.        , 0.        , 0.        , 0.        ],
       [0.04417671, 0.53815261, 0.00803213, 0.33065596, 0.0789826 ],
       [0.41414141, 0.13131313, 0.        , 0.26262626, 0.19191919]])

In [15]:
pkg_matrix = pkg_matrix.round(3)
pkg_matrix

array([[0.035, 0.349, 0.   , 0.593, 0.023],
       [0.014, 0.315, 0.002, 0.641, 0.029],
       [0.   , 1.   , 0.   , 0.   , 0.   ],
       [0.044, 0.538, 0.008, 0.331, 0.079],
       [0.414, 0.131, 0.   , 0.263, 0.192]])

# ram 전위확률 계산

In [16]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "High_Up")].count()
print("High_Up to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "High_Up")].count()
print("High_Up to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "High_Up")].count()
print("High_Up to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "High_Up")].count()
print("High_Up to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "High_Up")].count()
print("High_Up to High_Down :\n",i, "\n")

High_Up to High_Up :
 Perf_node01_power_energy_ram_    48
b                                48
dtype: int64 

High_Up to Low_Up :
 Perf_node01_power_energy_ram_    58
b                                58
dtype: int64 

High_Up to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

High_Up to Low_Down :
 Perf_node01_power_energy_ram_    37
b                                37
dtype: int64 

High_Up to High_Down :
 Perf_node01_power_energy_ram_    2
b                                2
dtype: int64 



In [17]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "Low_Up")].count()
print("Low_Up to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "Low_Up")].count()
print("Low_Up to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "Low_Up")].count()
print("Low_Up to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "Low_Up")].count()
print("Low_Up to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "Low_Up")].count()
print("Low_Up to High_Down :\n",i, "\n")

Low_Up to High_Up :
 Perf_node01_power_energy_ram_    10
b                                10
dtype: int64 

Low_Up to Low_Up :
 Perf_node01_power_energy_ram_    191
b                                191
dtype: int64 

Low_Up to Same2 :
 Perf_node01_power_energy_ram_    1
b                                1
dtype: int64 

Low_Up to Low_Down :
 Perf_node01_power_energy_ram_    406
b                                406
dtype: int64 

Low_Up to High_Down :
 Perf_node01_power_energy_ram_    18
b                                18
dtype: int64 



In [18]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "Same2")].count()
print("Same2 to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "Same2")].count()
print("Same2 to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "Same2")].count()
print("Same2 to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "Same2")].count()
print("Same2 to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "Same2")].count()
print("Same2 to High_Down :\n",i, "\n")

Same2 to High_Up :
 Perf_node01_power_energy_ram_    1
b                                1
dtype: int64 

Same2 to Low_Up :
 Perf_node01_power_energy_ram_    2
b                                2
dtype: int64 

Same2 to Same2 :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 

Same2 to Low_Down :
 Perf_node01_power_energy_ram_    1
b                                1
dtype: int64 

Same2 to High_Down :
 Perf_node01_power_energy_ram_    0
b                                0
dtype: int64 



In [19]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "Low_Down")].count()
print("Low_Down to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "Low_Down")].count()
print("Low_Down to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "Low_Down")].count()
print("Low_Down to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "Low_Down")].count()
print("Low_Down to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "Low_Down")].count()
print("Low_Down to High_Down :\n",i, "\n")

Low_Down to High_Up :
 Perf_node01_power_energy_ram_    14
b                                14
dtype: int64 

Low_Down to Low_Up :
 Perf_node01_power_energy_ram_    365
b                                365
dtype: int64 

Low_Down to Same2 :
 Perf_node01_power_energy_ram_    2
b                                2
dtype: int64 

Low_Down to Low_Down :
 Perf_node01_power_energy_ram_    245
b                                245
dtype: int64 

Low_Down to High_Down :
 Perf_node01_power_energy_ram_    73
b                                73
dtype: int64 



In [20]:
i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Up") & (ef["b"] == "High_Down")].count()
print("High_Down to High_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Up") & (ef["b"] == "High_Down")].count()
print("High_Down to Low_Up :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Same2") & (ef["b"] == "High_Down")].count()
print("High_Down to Same2 :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "Low_Down") & (ef["b"] == "High_Down")].count()
print("High_Down to Low_Down :\n",i, "\n")

i = ef.loc[(ef["Perf_node01_power_energy_ram_"] == "High_Down") & (ef["b"] == "High_Down")].count()
print("High_Down to High_Down :\n",i, "\n")

High_Down to High_Up :
 Perf_node01_power_energy_ram_    72
b                                72
dtype: int64 

High_Down to Low_Up :
 Perf_node01_power_energy_ram_    9
b                                9
dtype: int64 

High_Down to Same2 :
 Perf_node01_power_energy_ram_    1
b                                1
dtype: int64 

High_Down to Low_Down :
 Perf_node01_power_energy_ram_    11
b                                11
dtype: int64 

High_Down to High_Down :
 Perf_node01_power_energy_ram_    32
b                                32
dtype: int64 



In [21]:
ram_matrix[0] = [48/145, 58/145, 0, 37/145, 2/145]
ram_matrix[1] = [10/626, 191/626, 1/626, 406/626, 18/626]
ram_matrix[2] = [1/4, 2/4, 0, 1/4, 0]
ram_matrix[3] = [14/699, 365/699, 2/699, 245/699, 73/699]
ram_matrix[4] = [72/125, 9/125, 1/125, 11/125, 32/125]

In [22]:
ram_matrix

array([[0.33103448, 0.4       , 0.        , 0.25517241, 0.0137931 ],
       [0.01597444, 0.30511182, 0.00159744, 0.6485623 , 0.02875399],
       [0.25      , 0.5       , 0.        , 0.25      , 0.        ],
       [0.02002861, 0.52217454, 0.00286123, 0.35050072, 0.10443491],
       [0.576     , 0.072     , 0.008     , 0.088     , 0.256     ]])

In [23]:
ram_matrix = ram_matrix.round(3)
ram_matrix

array([[0.331, 0.4  , 0.   , 0.255, 0.014],
       [0.016, 0.305, 0.002, 0.649, 0.029],
       [0.25 , 0.5  , 0.   , 0.25 , 0.   ],
       [0.02 , 0.522, 0.003, 0.351, 0.104],
       [0.576, 0.072, 0.008, 0.088, 0.256]])

# total 전위확률 계산

In [24]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "High_Up")].count()
print("High_Up to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "High_Up")].count()
print("High_Up to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "High_Up")].count()
print("High_Up to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "High_Up")].count()
print("High_Up to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "High_Up")].count()
print("High_Up to High_Down :\n",i, "\n")

High_Up to High_Up :
 Perf_node01_power_energy_total_    5
c                                  5
dtype: int64 

High_Up to Low_Up :
 Perf_node01_power_energy_total_    44
c                                  44
dtype: int64 

High_Up to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Up to Low_Down :
 Perf_node01_power_energy_total_    37
c                                  37
dtype: int64 

High_Up to High_Down :
 Perf_node01_power_energy_total_    1
c                                  1
dtype: int64 



In [25]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "Low_Up")].count()
print("Low_Up to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "Low_Up")].count()
print("Low_Up to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "Low_Up")].count()
print("Low_Up to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "Low_Up")].count()
print("Low_Up to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "Low_Up")].count()
print("Low_Up to High_Down :\n",i, "\n")

Low_Up to High_Up :
 Perf_node01_power_energy_total_    10
c                                  10
dtype: int64 

Low_Up to Low_Up :
 Perf_node01_power_energy_total_    210
c                                  210
dtype: int64 

Low_Up to Same2 :
 Perf_node01_power_energy_total_    1
c                                  1
dtype: int64 

Low_Up to Low_Down :
 Perf_node01_power_energy_total_    431
c                                  431
dtype: int64 

Low_Up to High_Down :
 Perf_node01_power_energy_total_    18
c                                  18
dtype: int64 



In [26]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "Same2")].count()
print("Same2 to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "Same2")].count()
print("Same2 to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "Same2")].count()
print("Same2 to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "Same2")].count()
print("Same2 to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "Same2")].count()
print("Same2 to High_Down :\n",i, "\n")

Same2 to High_Up :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to Low_Up :
 Perf_node01_power_energy_total_    1
c                                  1
dtype: int64 

Same2 to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

Same2 to Low_Down :
 Perf_node01_power_energy_total_    2
c                                  2
dtype: int64 

Same2 to High_Down :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 



In [27]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "Low_Down")].count()
print("Low_Down to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "Low_Down")].count()
print("Low_Down to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "Low_Down")].count()
print("Low_Down to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "Low_Down")].count()
print("Low_Down to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "Low_Down")].count()
print("Low_Down to High_Down :\n",i, "\n")

Low_Down to High_Up :
 Perf_node01_power_energy_total_    21
c                                  21
dtype: int64 

Low_Down to Low_Up :
 Perf_node01_power_energy_total_    400
c                                  400
dtype: int64 

Low_Down to Same2 :
 Perf_node01_power_energy_total_    2
c                                  2
dtype: int64 

Low_Down to Low_Down :
 Perf_node01_power_energy_total_    244
c                                  244
dtype: int64 

Low_Down to High_Down :
 Perf_node01_power_energy_total_    63
c                                  63
dtype: int64 



In [28]:
i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Up") & (ff["c"] == "High_Down")].count()
print("High_Down to High_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Up") & (ff["c"] == "High_Down")].count()
print("High_Down to Low_Up :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Same2") & (ff["c"] == "High_Down")].count()
print("High_Down to Same2 :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "Low_Down") & (ff["c"] == "High_Down")].count()
print("High_Down to Low_Down :\n",i, "\n")

i = ff.loc[(ff["Perf_node01_power_energy_total_"] == "High_Down") & (ff["c"] == "High_Down")].count()
print("High_Down to High_Down :\n",i, "\n")

High_Down to High_Up :
 Perf_node01_power_energy_total_    51
c                                  51
dtype: int64 

High_Down to Low_Up :
 Perf_node01_power_energy_total_    15
c                                  15
dtype: int64 

High_Down to Same2 :
 Perf_node01_power_energy_total_    0
c                                  0
dtype: int64 

High_Down to Low_Down :
 Perf_node01_power_energy_total_    16
c                                  16
dtype: int64 

High_Down to High_Down :
 Perf_node01_power_energy_total_    27
c                                  27
dtype: int64 



In [29]:
total_matrix[0] = [5/87, 44/87, 0, 37/87, 1/87]
total_matrix[1] = [10/670, 210/670, 1/670, 431/670, 18/670]
total_matrix[2] = [0, 1/3, 0, 2/3, 0]
total_matrix[3] = [21/730, 400/730, 2/730, 244/730, 63/730]
total_matrix[4] = [51/109, 15/109, 0, 16/109, 27/109]

In [30]:
total_matrix

array([[0.05747126, 0.50574713, 0.        , 0.42528736, 0.01149425],
       [0.01492537, 0.31343284, 0.00149254, 0.64328358, 0.02686567],
       [0.        , 0.33333333, 0.        , 0.66666667, 0.        ],
       [0.02876712, 0.54794521, 0.00273973, 0.33424658, 0.08630137],
       [0.46788991, 0.13761468, 0.        , 0.14678899, 0.24770642]])

In [31]:
total_matrix = total_matrix.round(3)
total_matrix

array([[0.057, 0.506, 0.   , 0.425, 0.011],
       [0.015, 0.313, 0.001, 0.643, 0.027],
       [0.   , 0.333, 0.   , 0.667, 0.   ],
       [0.029, 0.548, 0.003, 0.334, 0.086],
       [0.468, 0.138, 0.   , 0.147, 0.248]])

# 결론

In [32]:
print(pkg_matrix)
print(ram_matrix)
print(total_matrix)

[[0.035 0.349 0.    0.593 0.023]
 [0.014 0.315 0.002 0.641 0.029]
 [0.    1.    0.    0.    0.   ]
 [0.044 0.538 0.008 0.331 0.079]
 [0.414 0.131 0.    0.263 0.192]]
[[0.331 0.4   0.    0.255 0.014]
 [0.016 0.305 0.002 0.649 0.029]
 [0.25  0.5   0.    0.25  0.   ]
 [0.02  0.522 0.003 0.351 0.104]
 [0.576 0.072 0.008 0.088 0.256]]
[[0.057 0.506 0.    0.425 0.011]
 [0.015 0.313 0.001 0.643 0.027]
 [0.    0.333 0.    0.667 0.   ]
 [0.029 0.548 0.003 0.334 0.086]
 [0.468 0.138 0.    0.147 0.248]]
