In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
bt = pd.read_csv("bt.csv")

In [5]:
bt

Application Perf_node01_task_clock Perf_node01_cpu_bus_cycles_  \
0             BT                   Down                          Up   
1             BT                     Up                          Up   
2             BT                     Up                          Up   
3             BT                     Up                        Down   
4             BT                     Up                          Up   
...          ...                    ...                         ...   
1534          BT                   Down                       Same1   
1535          BT                     Up                          Up   
1536          BT                     Up                        Down   
1537          BT                   Down                        Down   
1538         NaN                    NaN                         NaN   

     Perf_node01_cpu_cpu_cycles_ Perf_node01_msr_aperf_  \
0                             Up                     Up   
1                             Up                     Up   
2                             Up                     Up   
3                           Down                     Up   
4                             Up                     Up   
...                          ...                    ...   
1534                       Same1                     Up   
1535                          Up                     Up   
1536                        Down                   Down   
1537                        Down                   Down   
1538                         NaN                    NaN   

     Perf_node01_msr_mperf_ Perf_node01_msr_tsc_ Perf_node01_cpu_ref_cycles_  \
0                        Up                 Down                          Up   
1                        Up                   Up                          Up   
2                        Up                 Down                          Up   
3                        Up                   Up                          Up   
4                        Up                   Up                          Up   
...                     ...                  ...                         ...   
1534                     Up                   Up                          Up   
1535                     Up                   Up                          Up   
1536                   Down                 Down                        Down   
1537                   Down                 Down                        Down   
1538                    NaN                  NaN                         NaN   

     Perf_node01_power_energy_pkg_          a Perf_node01_power_energy_ram_  \
0                           Low_Up        NaN                       High_Up   
1                           Low_Up     Low_Up                      Low_Down   
2                           Low_Up     Low_Up                      Low_Down   
3                           Low_Up     Low_Up                       High_Up   
4                          High_Up     Low_Up                       High_Up   
...                            ...        ...                           ...   
1534                        Low_Up     Low_Up                      Low_Down   
1535                       High_Up     Low_Up                       High_Up   
1536                     High_Down    High_Up                     High_Down   
1537                     High_Down  High_Down                     High_Down   
1538                           NaN  High_Down                           NaN   

              b Perf_node01_power_energy_total_          c  
0           NaN                          Low_Up        NaN  
1       High_Up                          Low_Up     Low_Up  
2      Low_Down                          Low_Up     Low_Up  
3      Low_Down                          Low_Up     Low_Up  
4       High_Up                         High_Up     Low_Up  
...         ...                             ...        ...  
1534  High_Down                          Low_Up   Low_Down  
1535   Low_Down                         High_

In [42]:
observation = "Perf_node01_cpu_ref_cycles_"
energy = "Perf_node01_power_energy_ram_"

In [43]:
df = bt[[observation, energy]]

In [44]:
i = df.loc[(df[energy] == "High_Up") & (df[observation] == "Up")].count()
print("Up :\n",i, "\n")

i = df.loc[(df[energy] == "High_Up") & (df[observation] == "Same1")].count()
print("Same :\n",i, "\n")

i = df.loc[(df[energy] == "High_Up") & (df[observation] == "Down")].count()
print("Down :\n",i, "\n")

Up :
 Perf_node01_cpu_ref_cycles_      469
Perf_node01_power_energy_ram_    469
dtype: int64 

Same :
 Perf_node01_cpu_ref_cycles_      2
Perf_node01_power_energy_ram_    2
dtype: int64 

Down :
 Perf_node01_cpu_ref_cycles_      12
Perf_node01_power_energy_ram_    12
dtype: int64 



In [45]:
i = df.loc[(df[energy] == "Low_Up") & (df[observation] == "Up")].count()
print("Up :\n",i, "\n")

i = df.loc[(df[energy] == "Low_Up") & (df[observation] == "Same1")].count()
print("Same :\n",i, "\n")

i = df.loc[(df[energy] == "Low_Up") & (df[observation] == "Down")].count()
print("Down :\n",i, "\n")

Up :
 Perf_node01_cpu_ref_cycles_      77
Perf_node01_power_energy_ram_    77
dtype: int64 

Same :
 Perf_node01_cpu_ref_cycles_      6
Perf_node01_power_energy_ram_    6
dtype: int64 

Down :
 Perf_node01_cpu_ref_cycles_      42
Perf_node01_power_energy_ram_    42
dtype: int64 



In [46]:
i = df.loc[(df[energy] == "Low_Down") & (df[observation] == "Up")].count()
print("Up :\n",i, "\n")

i = df.loc[(df[energy] == "Low_Down") & (df[observation] == "Same1")].count()
print("Same :\n",i, "\n")

i = df.loc[(df[energy] == "Low_Down") & (df[observation] == "Down")].count()
print("Down :\n",i, "\n")

Up :
 Perf_node01_cpu_ref_cycles_      154
Perf_node01_power_energy_ram_    154
dtype: int64 

Same :
 Perf_node01_cpu_ref_cycles_      23
Perf_node01_power_energy_ram_    23
dtype: int64 

Down :
 Perf_node01_cpu_ref_cycles_      215
Perf_node01_power_energy_ram_    215
dtype: int64 



In [47]:
i = df.loc[(df[energy] == "High_Down") & (df[observation] == "Up")].count()
print("Up :\n",i, "\n")

i = df.loc[(df[energy] == "High_Down") & (df[observation] == "Same1")].count()
print("Same :\n",i, "\n")

i = df.loc[(df[energy] == "High_Down") & (df[observation] == "Down")].count()
print("Down :\n",i, "\n")

Up :
 Perf_node01_cpu_ref_cycles_      45
Perf_node01_power_energy_ram_    45
dtype: int64 

Same :
 Perf_node01_cpu_ref_cycles_      16
Perf_node01_power_energy_ram_    16
dtype: int64 

Down :
 Perf_node01_cpu_ref_cycles_      474
Perf_node01_power_energy_ram_    474
dtype: int64 



In [42]:
cpu_bus_matrix = np.zeros((4,3))

In [44]:
cpu_bus_matrix[0] = [1,0,0]
cpu_bus_matrix[1] = [64/416, 15/416, 337/416]
cpu_bus_matrix[2] = [14/218, 4/218, 200/218]
cpu_bus_matrix[3] = [8/457, 0, 449/457]

In [45]:
cpu_bus_matrix = cpu_bus_matrix.round(3)
cpu_bus_matrix

array([[1.   , 0.   , 0.   ],
       [0.154, 0.036, 0.81 ],
       [0.064, 0.018, 0.917],
       [0.018, 0.   , 0.982]])

In [52]:
matrix_1 = np.zeros((4,3))
matrix_3 = np.zeros((4,3))
matrix_4 = np.zeros((4,3))
matrix_5 = np.zeros((4,3))
matrix_6 = np.zeros((4,3))
matrix_7 = np.zeros((4,3))

In [54]:
matrix_1[0] = [1,0,0]
matrix_1[1] = [61/416, 0, 355/416]
matrix_1[2] = [22/218, 0, 196/218]
matrix_1[3] = [41/457, 0, 416/457]
matrix_1 = matrix_1.round(3)
matrix_1

array([[1.   , 0.   , 0.   ],
       [0.147, 0.   , 0.853],
       [0.101, 0.   , 0.899],
       [0.09 , 0.   , 0.91 ]])

In [61]:
matrix_3[0] = [1,0,0]
matrix_3[1] = [66/416, 18/416, 332/416]
matrix_3[2] = [16/218, 2/218, 200/218]
matrix_3[3] = [6/457, 0, 451/457]
matrix_3 = matrix_3.round(3)
matrix_3

array([[1.   , 0.   , 0.   ],
       [0.159, 0.043, 0.798],
       [0.073, 0.009, 0.917],
       [0.013, 0.   , 0.987]])

In [68]:
matrix_4[0] = [1,0,0]
matrix_4[1] = [129/416, 0, 287/416]
matrix_4[2] = [15/218, 0, 203/218]
matrix_4[3] = [1/457, 0, 456/457]
matrix_4 = matrix_4.round(3)
matrix_4

array([[1.   , 0.   , 0.   ],
       [0.31 , 0.   , 0.69 ],
       [0.069, 0.   , 0.931],
       [0.002, 0.   , 0.998]])

In [75]:
matrix_5[0] = [1,0,0]
matrix_5[1] = [205/416, 0, 211/416]
matrix_5[2] = [13/218, 0, 205/218]
matrix_5[3] = [0,0,1]
matrix_5 = matrix_5.round(3)
matrix_5

array([[1.   , 0.   , 0.   ],
       [0.493, 0.   , 0.507],
       [0.06 , 0.   , 0.94 ],
       [0.   , 0.   , 1.   ]])

In [82]:
matrix_6[0] = [1,0,0]
matrix_6[1] = [290/416, 20/416, 106/416]
matrix_6[2] = [18/218, 3/218, 197/218]
matrix_6[3] = [0,0,1]
matrix_6 = matrix_6.round(3)
matrix_6

array([[1.   , 0.   , 0.   ],
       [0.697, 0.048, 0.255],
       [0.083, 0.014, 0.904],
       [0.   , 0.   , 1.   ]])

In [89]:
matrix_7[0] = [1,0,0]
matrix_7[1] = [280/416, 34/416, 102/416]
matrix_7[2] = [17/218, 13/218, 188/218]
matrix_7[3] = [1/457,0,456/457]
matrix_7 = matrix_7.round(3)
matrix_7

array([[1.   , 0.   , 0.   ],
       [0.673, 0.082, 0.245],
       [0.078, 0.06 , 0.862],
       [0.002, 0.   , 0.998]])

0.9772256728778468